{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-ui-242",
    "version": "0.26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-foundation-242",
          "version": {
            "requires": "0.26.2"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-ui-242-0.26.2.jar",
          "url": "jewel-ui-242-0.26.2.jar",
          "size": 1781237,
          "sha512": "0d7d8e6c655f92f5db73fd4a9e76b79e58c96505d72cb243754ad2b82cdc5526260e8422170280e7688ce3a819f68fe71c11f2a89d03a99a181fff2c613c77ca",
          "sha256": "6e705e44ed98f9af6f539cca9a83ef7be4e5e424622c78b085e2f9b50129b6c8",
          "sha1": "af71e2bdab666449e7144f7e373c54dd7abb6507",
          "md5": "5e9dda498f5def0d8f945953b039fb60"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-foundation-242",
          "version": {
            "requires": "0.26.2"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-ui-242-0.26.2.jar",
          "url": "jewel-ui-242-0.26.2.jar",
          "size": 1781237,
          "sha512": "0d7d8e6c655f92f5db73fd4a9e76b79e58c96505d72cb243754ad2b82cdc5526260e8422170280e7688ce3a819f68fe71c11f2a89d03a99a181fff2c613c77ca",
          "sha256": "6e705e44ed98f9af6f539cca9a83ef7be4e5e424622c78b085e2f9b50129b6c8",
          "sha1": "af71e2bdab666449e7144f7e373c54dd7abb6507",
          "md5": "5e9dda498f5def0d8f945953b039fb60"
        }
      ]
    }
  ]
}
