{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle",
    "module": "gradle-tooling-api",
    "version": "8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12-rc-2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-tooling-api-8.12-sources.jar",
          "url": "gradle-tooling-api-8.12-sources.jar",
          "size": 6033111,
          "sha512": "5b9942e832dbd06e4e92d775cc68ab279e81b252570a888262307f0be90f2f36a905b0260340c211d0983c54788b180e8f19fb2da90eb8a532471c8ebd7cb5e4",
          "sha256": "6f722d962a62578b1f761237853b47be0adcd9218933fd1d076a82ba52ce238a",
          "sha1": "789162054744e026bcb0c4091836efff999f2ee3",
          "md5": "4d53972b7eeb3b4654056ce9ac8374ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-tooling-api-8.12-javadoc.jar",
          "url": "gradle-tooling-api-8.12-javadoc.jar",
          "size": 2030707,
          "sha512": "21b69883420170ea04340158fa8b3a29b93d998d0812fc538f18e1e51f1d30be145752f7c3ff5963319af3f17c70b0f617dc2a0f736a19e5a2424fa9f9f1e0fd",
          "sha256": "6426a7ad7841c7bcd497fab595a3d819dc0779b98bab6d363d3e419f08961623",
          "sha1": "e04e8113e3bf2f120a207f0ef6cf24bbbf2b66c7",
          "md5": "9f2bcb24f5bfdf6035af4899e2ee4232"
        }
      ]
    },
    {
      "name": "shadedRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-tooling-api-8.12.jar",
          "url": "gradle-tooling-api-8.12.jar",
          "size": 3098700,
          "sha512": "704d8f16df1f083d5bee011cff29fb2069d51698022fce4247b01c79a860ac22783b068252a643fd35448831244c1c086cb75f8cbd39d3e1daac1eff4b66a790",
          "sha256": "13cdc225b5e8a9f52e990d4658d9e63c6af3f0301cd155afd949699b950fe4c9",
          "sha1": "03971af8e5d4163396ffd9e4ca7d0ca12092fa78",
          "md5": "186ca8d9ef977ac59d751f1f37b7b2fd"
        }
      ]
    }
  ]
}
