{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-foundation-241",
    "version": "0.19.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-desktop",
          "version": {
            "requires": "1.6.10-dev1584"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-foundation-241-0.19.5.jar",
          "url": "jewel-foundation-241-0.19.5.jar",
          "size": 391240,
          "sha512": "dd634b2b7d1749cec5627352240e70e395e8eed57d3791d94ce4dbaf060379c281234e849be6f66f001ff091f84085ef477e4c01bccf07f73f55742b0fd23e3a",
          "sha256": "173cabad49a76719d7001e264f15c1ea7f69e4c4fe987133aa4f737773d2af93",
          "sha1": "0f7091a1118cfab3ffdf8c17538684bce2da56ad",
          "md5": "dce9cd54abaafd1af4b4714b554b0153"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-desktop",
          "version": {
            "requires": "1.6.10-dev1584"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-foundation-241-0.19.5.jar",
          "url": "jewel-foundation-241-0.19.5.jar",
          "size": 391240,
          "sha512": "dd634b2b7d1749cec5627352240e70e395e8eed57d3791d94ce4dbaf060379c281234e849be6f66f001ff091f84085ef477e4c01bccf07f73f55742b0fd23e3a",
          "sha256": "173cabad49a76719d7001e264f15c1ea7f69e4c4fe987133aa4f737773d2af93",
          "sha1": "0f7091a1118cfab3ffdf8c17538684bce2da56ad",
          "md5": "dce9cd54abaafd1af4b4714b554b0153"
        }
      ]
    }
  ]
}
