{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-device-info",
    "version": "30.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-30.2.0.jar",
          "url": "android-test-plugin-host-device-info-30.2.0.jar",
          "size": 10220,
          "sha512": "9321b6dce21b5660be43699477cd61185df433c7b341bc67a69f651d20b6aea5c1ae4df76df8dbea1a445143bb9ff3780a93ddd5bc88554631d30911027f5a82",
          "sha256": "bfb394e0fbb9ad583e5d1d664f8b349c14cb33891ae6a2c52c51909ee909e916",
          "sha1": "83ae92d2db13cbe5e8e82cb8a7d8cbb47eb18ad5",
          "md5": "f5c77439ad6dbddfc1534909e61a32b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-device-info-proto",
          "version": {
            "requires": "30.2.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.8-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-device-info-30.2.0.jar",
          "url": "android-test-plugin-host-device-info-30.2.0.jar",
          "size": 10220,
          "sha512": "9321b6dce21b5660be43699477cd61185df433c7b341bc67a69f651d20b6aea5c1ae4df76df8dbea1a445143bb9ff3780a93ddd5bc88554631d30911027f5a82",
          "sha256": "bfb394e0fbb9ad583e5d1d664f8b349c14cb33891ae6a2c52c51909ee909e916",
          "sha1": "83ae92d2db13cbe5e8e82cb8a7d8cbb47eb18ad5",
          "md5": "f5c77439ad6dbddfc1534909e61a32b9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-30.2.0-javadoc.jar",
          "url": "android-test-plugin-host-device-info-30.2.0-javadoc.jar",
          "size": 261,
          "sha512": "853a6943fdc26cf0b889e849039a7cd04e60753d317b893286882f931a373918672fabd7635c275314e76607747255ab65b0a8bafcdb238642462c25396935db",
          "sha256": "d0eeb387c826c5dd8df0a3200e62574266dd46e9672156290e1c2e78d3577806",
          "sha1": "d46437eded6dcff06b596e3fcec26454c2cd0092",
          "md5": "5b535a098e2a626ca4de1f398b9d44a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-device-info-30.2.0-sources.jar",
          "url": "android-test-plugin-host-device-info-30.2.0-sources.jar",
          "size": 4306,
          "sha512": "61749455e1aeb6d6dd65315c0248c2b7cc1e6c5cd990c94d37efbf42c2aed6320ff19d03ebb3b827ccfb93eb8fe50c6819f41a5a31a426927c3953207f08c1bb",
          "sha256": "33322693a0b77b510ed53054ad0120e0d53f78d2c965804b3c2e3c26b4414e14",
          "sha1": "19d356db773526edb4c8f4bef3ec8185bbcc3cbb",
          "md5": "19f63d561d1590b6afd2df869ae009b5"
        }
      ]
    }
  ]
}
