{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.7.0-beta02/animation-core-1.7.0-beta02.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "1.7.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.7.0-beta02.jar",
          "url": "animation-core-desktop-1.7.0-beta02.jar",
          "size": 437680,
          "sha512": "4dc28487b30696a55d63f83158581cd05f68d214b3cf9fb5b9352aaffe9bfd35b1d55583fef88d5777786a9bee3a1abed4b79ec3a7425fa1b00c2789839960c1",
          "sha256": "31c475b8534a8307de86f36aa095c9ea9fae2fbc3a9c2ecf30bc3317ead6d487",
          "sha1": "fb7d891f46fcab64f51609dfdad07b8124e766e3",
          "md5": "30e0852e1113f330edfc9321e7b309bc"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.7.0-beta02.jar",
          "url": "animation-core-desktop-1.7.0-beta02.jar",
          "size": 437680,
          "sha512": "4dc28487b30696a55d63f83158581cd05f68d214b3cf9fb5b9352aaffe9bfd35b1d55583fef88d5777786a9bee3a1abed4b79ec3a7425fa1b00c2789839960c1",
          "sha256": "31c475b8534a8307de86f36aa095c9ea9fae2fbc3a9c2ecf30bc3317ead6d487",
          "sha1": "fb7d891f46fcab64f51609dfdad07b8124e766e3",
          "md5": "30e0852e1113f330edfc9321e7b309bc"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "animation-core-desktop-1.7.0-beta02-sources.jar",
          "url": "animation-core-desktop-1.7.0-beta02-sources.jar",
          "size": 112382,
          "sha512": "ec2446e16764a1a0cc98e52cd99fabe905bad6d909340e9c80ee5c4b129c11a9b9be7be732e1375bc7a41f379927d176d82f01017b1012be7c2aaca159b8277a",
          "sha256": "304de771a3afe8186d3d1701ead7456c9350cc960c5b4cac66b3b592a558035d",
          "sha1": "df824894123f5f3ad88d2abd6fc88af073ee6fea",
          "md5": "72ae9557442951531bf8df8b074411a1"
        }
      ]
    }
  ]
}