{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ui",
    "module": "ui-animation",
    "version": "0.1.0-dev13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6519275"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-animation-core",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-runtime",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-core",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-layout",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "0.1.0-dev13"
          }
        }
      ],
      "files": [
        {
          "name": "ui-animation-0.1.0-dev13.aar",
          "url": "ui-animation-0.1.0-dev13.aar",
          "size": 95400,
          "sha512": "243e1e6610147917fc1972bf044ef2762a774e2b5a3c194770e06fc4f4338d66fa44d54b3664b84f4e93438ed8f1a3456c864bf5c180054cdc74b4cc415240e8",
          "sha256": "6684bd349415eea76714f89582da2eacb12d8380cca1dee5c0495c755266c84f",
          "sha1": "570429d2dce40e67633bfd8f7b45f7d7b0e9194d",
          "md5": "4125cad4b797b65262c6a941fac953d0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-animation-core",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-runtime",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-core",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-layout",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable-jvm",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-util",
          "version": {
            "requires": "0.1.0-dev13"
          }
        }
      ],
      "files": [
        {
          "name": "ui-animation-0.1.0-dev13.aar",
          "url": "ui-animation-0.1.0-dev13.aar",
          "size": 95400,
          "sha512": "243e1e6610147917fc1972bf044ef2762a774e2b5a3c194770e06fc4f4338d66fa44d54b3664b84f4e93438ed8f1a3456c864bf5c180054cdc74b4cc415240e8",
          "sha256": "6684bd349415eea76714f89582da2eacb12d8380cca1dee5c0495c755266c84f",
          "sha1": "570429d2dce40e67633bfd8f7b45f7d7b0e9194d",
          "md5": "4125cad4b797b65262c6a941fac953d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-animation-0.1.0-dev13-sources.jar",
          "url": "ui-animation-0.1.0-dev13-sources.jar",
          "size": 11841,
          "sha512": "0200ce7a9fd1d5ad7d3b0315f89ffbc76a76c984b3054822447cbd976bf1b8226c6567db0617978caec14080e23e64f27ee10f02a8de0f03485c2586953975d1",
          "sha256": "4d89900dc41316b856da3bbd32c26c029ce90300a2044c650e218c0cc2a5fe28",
          "sha1": "df745c52c8711531d7f4532e32256a06519c62e7",
          "md5": "97b1715b4c8110fdcc2be85c8966bb61"
        }
      ]
    }
  ]
}
