java_import(
    name = "gradle-tooling-extension-impl",
    jars = ["gradle-tooling-extension-impl-202.6948.69.jar"],
    visibility = ["//tools/idea/plugins/gradle/tooling-extension-impl:__pkg__"],
)
