java_import(
    name = "gradle-tooling-extension-impl",
    jars = ["gradle-tooling-extension-impl-201.7223.91.jar"],
    visibility = ["//tools/idea/plugins/gradle/tooling-extension-impl:__pkg__"],
)
