java_import(
    name = "gradle-tooling-extension-impl",
    jars = ["gradle-tooling-extension-impl-201.6668.121.jar"],
    visibility = ["//tools/idea/plugins/gradle/tooling-extension-impl:__pkg__"],
)
