{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.10.2/foundation-1.10.2.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14756242"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.10.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation.aar",
          "url": "foundation-android-1.10.2.aar",
          "size": 4948956,
          "sha512": "e449d3f4f9d9f9dc764fa774a54e56bab84a148976c682653464fdc9d43a049122d29dc05b1b25454ffa256f82b35287f333a55f9373e410e5f4ef9a2c713c93",
          "sha256": "068554eb9901a03ac119fe03d153034911c87d8f3886e69bdc840ac21db16cd0",
          "sha1": "b61380798a21b30331d922bffddbcdf978ab78dd",
          "md5": "c1254fee47cbb5a3703fec2662e5aaff"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.10.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation.aar",
          "url": "foundation-android-1.10.2.aar",
          "size": 4948956,
          "sha512": "e449d3f4f9d9f9dc764fa774a54e56bab84a148976c682653464fdc9d43a049122d29dc05b1b25454ffa256f82b35287f333a55f9373e410e5f4ef9a2c713c93",
          "sha256": "068554eb9901a03ac119fe03d153034911c87d8f3886e69bdc840ac21db16cd0",
          "sha1": "b61380798a21b30331d922bffddbcdf978ab78dd",
          "md5": "c1254fee47cbb5a3703fec2662e5aaff"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.10.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-android-1.10.2-sources.jar",
          "url": "foundation-android-1.10.2-sources.jar",
          "size": 1085794,
          "sha512": "99b5ad885aa7a83dfdce7524f88fc203e761667d7ddf55829d65e6ee9836a35503d7e5198724b6ade10f62540fbae5ad0fccd0f01f7a1ee2b350b8aa90e9c06f",
          "sha256": "b918e13fb35df24fcfcdcbbe8cb4115cb41e97c854151d55af0ef92317d642a9",
          "sha1": "7a7ab03b945aae1c96e88bd4379e169b5b90d6bf",
          "md5": "1445fb2e032bdeb2fe754214a2350832"
        },
        {
          "name": "foundation-1.10.2-samples-sources.jar",
          "url": "foundation-android-1.10.2-samples-sources.jar",
          "size": 90310,
          "sha512": "652584274ca95eae7f426d3b9cc93461b7197e17fdfe38560ec58e78b754759004aa496d365f29327b9f106b2f1fdb1d1567cf587d50bce9fcf89e6741cf0498",
          "sha256": "4d4246a8ab50357d37a07ba37960e99c893e1008658ca21489843291168f50a3",
          "sha1": "b041cdde161fe8c9f206646a39e51bf7cfedcbcc",
          "md5": "c452d10a3c2fd1ab66af75e9f4021d7b"
        }
      ]
    }
  ]
}