load("//tools/base/bazel:jvm_import.bzl", "jvm_import")

# managed by go/iml_to_build
jvm_import(
    name = "google-api-java-client",
    jars = ["google-api-java-client-min-repackaged-1.20.0.jar"],
    visibility = ["//visibility:public"],
)
