# managed by go/iml_to_build
java_import(
    name = "google-api-java-client-min-repackaged-1.20.0",
    jars = ["google-api-java-client-min-repackaged-1.20.0.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.google-api-java-client",
    jars = ["google-api-java-client-min-repackaged-1.20.0.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)
