# managed by go/iml_to_build
java_import(
    name = "google-api-java-client-min-repackaged-1.20.0",
    jars = ["google-api-java-client-min-repackaged-1.20.0.jar"],
    visibility = ["//visibility:public"],
)
