{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6841119"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-alpha04.aar",
          "url": "ui-unit-1.0.0-alpha04.aar",
          "size": 85796,
          "sha512": "6131a13a606e721932c6a05e4303ef9d5938db3798f66e00cfa6ea0113f44b2944516fa7a4db58a6b645aa0d555ea167a343ad77ba15d6e3efbd1ec8dd769d31",
          "sha256": "f8b0322b63ac381dcbb237507781ce93a1fd252be5a2d037052153710c98d7ee",
          "sha1": "2d33f30c28229ee4885d300de2bcee91a6bb9fc0",
          "md5": "e2cd553f7ae283825f487922028b4b06"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-alpha04.aar",
          "url": "ui-unit-1.0.0-alpha04.aar",
          "size": 85796,
          "sha512": "6131a13a606e721932c6a05e4303ef9d5938db3798f66e00cfa6ea0113f44b2944516fa7a4db58a6b645aa0d555ea167a343ad77ba15d6e3efbd1ec8dd769d31",
          "sha256": "f8b0322b63ac381dcbb237507781ce93a1fd252be5a2d037052153710c98d7ee",
          "sha1": "2d33f30c28229ee4885d300de2bcee91a6bb9fc0",
          "md5": "e2cd553f7ae283825f487922028b4b06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-1.0.0-alpha04-sources.jar",
          "url": "ui-unit-1.0.0-alpha04-sources.jar",
          "size": 76181,
          "sha512": "32684523078c1d086f641ecbcd54413a1691e01daf0bde45ac806045bd45c85105c5da6aa5d074e95c5fa2a3bf77cb047a7b9dd64a1d196826e6d3c7518bc010",
          "sha256": "22168b984edaf09a328e48822685f6b7ab08c078561f768ae5c1759479804eea",
          "sha1": "c6c8143bf52b825ea0063932102efb543afee591",
          "md5": "f06768641369b335c1ca5b3f2504dc51"
        }
      ]
    }
  ]
}
