{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.profileinstaller",
    "module": "profileinstaller",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.2.0.aar",
          "url": "profileinstaller-1.2.0.aar",
          "size": 36617,
          "sha512": "1fdaade4350817f200d3a805950d9292e6cac16642c23a441c1c3977e8ac767b47e2e132f14854a3be3aeb4986577e926b6259604144c8f84260aaf1d20af3e8",
          "sha256": "0a1b2260af67962f4038d56fa84cda341315704aad56abbcf3a9b3bba6945426",
          "sha1": "16e1de22dae68a8ff46a25ef5083c486e0cf0d6a",
          "md5": "f8df34a60f9e64a7557d32904fdad05c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.2.0.aar",
          "url": "profileinstaller-1.2.0.aar",
          "size": 36617,
          "sha512": "1fdaade4350817f200d3a805950d9292e6cac16642c23a441c1c3977e8ac767b47e2e132f14854a3be3aeb4986577e926b6259604144c8f84260aaf1d20af3e8",
          "sha256": "0a1b2260af67962f4038d56fa84cda341315704aad56abbcf3a9b3bba6945426",
          "sha1": "16e1de22dae68a8ff46a25ef5083c486e0cf0d6a",
          "md5": "f8df34a60f9e64a7557d32904fdad05c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profileinstaller-1.2.0-sources.jar",
          "url": "profileinstaller-1.2.0-sources.jar",
          "size": 29097,
          "sha512": "c62ae263a759422e4202006b91b69a455550d3116cfb5dd56047825d00d11d965f9dfba4b15f06d1852e0908508a8d22365413d5b6595468d7f93a4533c2865d",
          "sha256": "a01a346fb295752f1fa807c1b15525a6be2d5cab70c6a111433b5041b57335f0",
          "sha1": "8de54388ad3a1c5622d693f95c145a9e9f57dc4b",
          "md5": "9453789b22651cfe7f41b7a9a384c16b"
        }
      ]
    }
  ]
}