{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.2.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-util-1.2.0-alpha05.aar",
          "url": "ui-util-1.2.0-alpha05.aar",
          "size": 7894,
          "sha512": "9a2e343e6e0fb06e1d65bcfd825562d424046cb8e1ed0bf7a177411a2d0b827c658e67ec9cce35dabcf418a6be223681f70fc0314c902298e675fa1a6c5ee171",
          "sha256": "dc7ed291f2af4c8c9b84630b7e1c9ac97fd8a7a7d25d732055624cb31dc8f9a1",
          "sha1": "82e89fafa0ff96c6efd9fa61559d0c11e1604937",
          "md5": "454c237e6bc034ce689f8a12fa347e48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-1.2.0-alpha05.aar",
          "url": "ui-util-1.2.0-alpha05.aar",
          "size": 7894,
          "sha512": "9a2e343e6e0fb06e1d65bcfd825562d424046cb8e1ed0bf7a177411a2d0b827c658e67ec9cce35dabcf418a6be223681f70fc0314c902298e675fa1a6c5ee171",
          "sha256": "dc7ed291f2af4c8c9b84630b7e1c9ac97fd8a7a7d25d732055624cb31dc8f9a1",
          "sha1": "82e89fafa0ff96c6efd9fa61559d0c11e1604937",
          "md5": "454c237e6bc034ce689f8a12fa347e48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-util-1.2.0-alpha05-sources.jar",
          "url": "ui-util-1.2.0-alpha05-sources.jar",
          "size": 4738,
          "sha512": "95b730ea51df6152bad807db5a6134e14f16e12dea9483b14a18935269b742d5db32ef934da95b003bea7d1dcafe4f7290e5aca5e65661fd7b96816f8109783b",
          "sha256": "5d041026b4ff3159f2f0c727f621d20fd3833b4a80218c5fe2bd078db7c1f8c4",
          "sha1": "7c2c3f778883b267141811dd639236f3ab27dd85",
          "md5": "ea129d8bc5d6f4400290ae50bbb1624c"
        }
      ]
    }
  ]
}
