{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6841119"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.0.0-alpha04.aar",
          "url": "ui-text-1.0.0-alpha04.aar",
          "size": 291972,
          "sha512": "dddaa7905d75de534bc72d9de60510ad01719d020a49dc0e37bf4e664ea2bd5dde7c3cef4abb68e9aaa8f8030a3145107b590cc0919842f08808ee331ea3be28",
          "sha256": "f342ad4d376b7ae78d1605e633a8c2344e6dcaafea3558bb0c9cc5c7297d7943",
          "sha1": "dc374b76c9f9e7c3405262334d61b6e5b0f7c045",
          "md5": "1bb167476110bb02be5c9462e2dc79de"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saved-instance-state",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-android",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.0.0-alpha04.aar",
          "url": "ui-text-1.0.0-alpha04.aar",
          "size": 291972,
          "sha512": "dddaa7905d75de534bc72d9de60510ad01719d020a49dc0e37bf4e664ea2bd5dde7c3cef4abb68e9aaa8f8030a3145107b590cc0919842f08808ee331ea3be28",
          "sha256": "f342ad4d376b7ae78d1605e633a8c2344e6dcaafea3558bb0c9cc5c7297d7943",
          "sha1": "dc374b76c9f9e7c3405262334d61b6e5b0f7c045",
          "md5": "1bb167476110bb02be5c9462e2dc79de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-1.0.0-alpha04-sources.jar",
          "url": "ui-text-1.0.0-alpha04-sources.jar",
          "size": 293943,
          "sha512": "7969e408adf82c6d4ab23d1aaafd90408ea0d4b3f663ce92e128585e2406440a5172b59554a656b6173b2dcb419b35f2ad25ea0004b6841a802cd1b7fd24daea",
          "sha256": "eb619055193512db14517fc62ce13503865f9a02ec98805954a2fc0c5949f5b2",
          "sha1": "512a6753f6da5895afd6e09d8422fef109874372",
          "md5": "7467585bac98e82099da3f6023bcbc43"
        }
      ]
    }
  ]
}
