{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.8.0-alpha04/foundation-1.8.0-alpha04.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation",
    "version": "1.8.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.8.0-alpha04.jar",
          "url": "foundation-desktop-1.8.0-alpha04.jar",
          "size": 4566531,
          "sha512": "462dc9ba6829bcc80b115ec447e7631b0e5683495479950d2ad88c0b7ea8ab6c182b4c999d4755f9a92ac3b09d471c3836f5d9df0a1762f3bf50d860ea65b257",
          "sha256": "52c64187d615ad38bf3df41068b2a0180d8188d0f875f79a46938f3073fdafbb",
          "sha1": "d4907d195822b3579955aa5d2bb64820c4fa98e1",
          "md5": "54d5425353ab23d0b1d49f4e27302fc5"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.performance",
          "module": "performance-annotation",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.8.0-alpha04.jar",
          "url": "foundation-desktop-1.8.0-alpha04.jar",
          "size": 4566531,
          "sha512": "462dc9ba6829bcc80b115ec447e7631b0e5683495479950d2ad88c0b7ea8ab6c182b4c999d4755f9a92ac3b09d471c3836f5d9df0a1762f3bf50d860ea65b257",
          "sha256": "52c64187d615ad38bf3df41068b2a0180d8188d0f875f79a46938f3073fdafbb",
          "sha1": "d4907d195822b3579955aa5d2bb64820c4fa98e1",
          "md5": "54d5425353ab23d0b1d49f4e27302fc5"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "foundation-desktop-1.8.0-alpha04-sources.jar",
          "url": "foundation-desktop-1.8.0-alpha04-sources.jar",
          "size": 904064,
          "sha512": "ec065988e367a32c6ed324c086b57e4dbd9186e2b850ff801b38728295c7d50547816e264a8e63e6c2f6b4a9869bf30187442b5767bd622466596595f814bdbb",
          "sha256": "c88e0c145f17a1c52361f45dd13483e36e9863d590bcb1f2a2aba4daab15560b",
          "sha1": "12251b17e2e0769e736c0328445821a0624a0392",
          "md5": "65cf110f1b16f136bba272252193b22d"
        }
      ]
    }
  ]
}