{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler-hosted",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compiler-hosted-1.2.0.jar",
          "url": "compiler-hosted-1.2.0.jar",
          "size": 932309,
          "sha512": "64e6c80c8bf7171388532b24454477d7e175838027cb56bad13b19044c4d5f201ef949b1ace3b743168b80b0aa72989723f808f3b2740d3ce3de23f7b593640f",
          "sha256": "9b0b1a1e4396504d2459c7d9efd1d8849753c1f9daa97786124572df237ad0d8",
          "sha1": "dd59bfcfbbe906319901882a14086326aa36a74c",
          "md5": "4b857798bdc682dbba6f8e0a9543ff8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compiler-hosted-1.2.0.jar",
          "url": "compiler-hosted-1.2.0.jar",
          "size": 932309,
          "sha512": "64e6c80c8bf7171388532b24454477d7e175838027cb56bad13b19044c4d5f201ef949b1ace3b743168b80b0aa72989723f808f3b2740d3ce3de23f7b593640f",
          "sha256": "9b0b1a1e4396504d2459c7d9efd1d8849753c1f9daa97786124572df237ad0d8",
          "sha1": "dd59bfcfbbe906319901882a14086326aa36a74c",
          "md5": "4b857798bdc682dbba6f8e0a9543ff8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-hosted-1.2.0-sources.jar",
          "url": "compiler-hosted-1.2.0-sources.jar",
          "size": 189612,
          "sha512": "be3c7e95f3df71fb7486af70423a13aadbbb382d82013bc691f1c2026fefce9a70f6bfb502b920e3140271af5519ce61d79b1f26a34e9aff6e3db08dda9df289",
          "sha256": "d2de2b44a2666d245e4bb426c768047603622f4646430c9719adb49d15f3e003",
          "sha1": "a51bfaf5af687f2eba610515d772e5baef4c317a",
          "md5": "a703960565c4a209f8b8285f014e24d4"
        }
      ]
    }
  ]
}