{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-api",
    "version": "2.0.0-RC2-1.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-2.0.0-RC2-1.0.20.jar",
          "url": "symbol-processing-api-2.0.0-RC2-1.0.20.jar",
          "size": 122978,
          "sha512": "8084067bc89ceb4ae4230dfb31f72e3cde3bd1e006e4d8827e2664d246c64d8c798d8ffe5f001bda399065f5e7db0a46b751c0931777b3e7818cfb91cec82eef",
          "sha256": "299f2d03b750c1ba4ff80066679def79198fcfddeabe5adee26f509542450fa4",
          "sha1": "ad91ffe993bf0e79c81c55b128f37aba604b4343",
          "md5": "ea0416bd1ea216690688afa22ea48595"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-2.0.0-RC2-1.0.20.jar",
          "url": "symbol-processing-api-2.0.0-RC2-1.0.20.jar",
          "size": 122978,
          "sha512": "8084067bc89ceb4ae4230dfb31f72e3cde3bd1e006e4d8827e2664d246c64d8c798d8ffe5f001bda399065f5e7db0a46b751c0931777b3e7818cfb91cec82eef",
          "sha256": "299f2d03b750c1ba4ff80066679def79198fcfddeabe5adee26f509542450fa4",
          "sha1": "ad91ffe993bf0e79c81c55b128f37aba604b4343",
          "md5": "ea0416bd1ea216690688afa22ea48595"
        }
      ]
    }
  ]
}
