{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-ide-laf-bridge-242",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-242",
          "version": {
            "requires": "0.27.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jewel-ide-laf-bridge-242-0.27.0.jar",
          "url": "jewel-ide-laf-bridge-242-0.27.0.jar",
          "size": 236463,
          "sha512": "14d3890ed12cd785699e6ad9f6ad4c43aeb3fa2bd66f5da538f10cd89de82da1da842e9136102b9ed72c936ff65012b18b6a639c2d55d4a8bc2289d65c06187b",
          "sha256": "fb4dda7cb9610f0e0a80765ec6fba97af3c6a228212bb128aeb84e0557db3af8",
          "sha1": "a1d963f9721d231baf8f7b0c44ab5f1f85da03a1",
          "md5": "5b4e5d7363e33a6acd304e13dc7c0119"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-242",
          "version": {
            "requires": "0.27.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jewel-ide-laf-bridge-242-0.27.0.jar",
          "url": "jewel-ide-laf-bridge-242-0.27.0.jar",
          "size": 236463,
          "sha512": "14d3890ed12cd785699e6ad9f6ad4c43aeb3fa2bd66f5da538f10cd89de82da1da842e9136102b9ed72c936ff65012b18b6a639c2d55d4a8bc2289d65c06187b",
          "sha256": "fb4dda7cb9610f0e0a80765ec6fba97af3c6a228212bb128aeb84e0557db3af8",
          "sha1": "a1d963f9721d231baf8f7b0c44ab5f1f85da03a1",
          "md5": "5b4e5d7363e33a6acd304e13dc7c0119"
        }
      ]
    }
  ]
}
