{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-gradle-plugin",
    "version": "2.0.0-RC1-1.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.0.0-RC1-1.0.20.jar",
          "url": "symbol-processing-gradle-plugin-2.0.0-RC1-1.0.20.jar",
          "size": 169519,
          "sha512": "b1c1b9ba460ed097240111ce32f642baaa5589fb0ed1a013ecd6fd9aa0ec48fdac3c086d597e0ec1d4c85a86d51a6f0409484b0f629e7e603d6a6016543d539f",
          "sha256": "8ece33c25731ed654ebcd8191256b18910d86eccc3df23c159c21e75805b86ca",
          "sha1": "5452de7b5d0d5aa93d2e83eea8c615ae285af389",
          "md5": "b135ae4c9357529d3d69f5b45beed2c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.0-RC1-1.0.20"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.0.0-RC1-1.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.0.0-RC1-1.0.20.jar",
          "url": "symbol-processing-gradle-plugin-2.0.0-RC1-1.0.20.jar",
          "size": 169519,
          "sha512": "b1c1b9ba460ed097240111ce32f642baaa5589fb0ed1a013ecd6fd9aa0ec48fdac3c086d597e0ec1d4c85a86d51a6f0409484b0f629e7e603d6a6016543d539f",
          "sha256": "8ece33c25731ed654ebcd8191256b18910d86eccc3df23c159c21e75805b86ca",
          "sha1": "5452de7b5d0d5aa93d2e83eea8c615ae285af389",
          "md5": "b135ae4c9357529d3d69f5b45beed2c9"
        }
      ]
    }
  ]
}
