{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.1.20-RC2/kotlin-test-2.1.20-RC2.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.1.20-RC2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "jvmJUnitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.20-RC2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.1.20-RC2.jar",
          "url": "kotlin-test-junit-2.1.20-RC2.jar",
          "size": 5078,
          "sha512": "1690643e2b941f11154928551793858474d2464732b5b735d9b08c690064fe6b7f69c44bf59574436a261ceb06c6c64393b5bb0210c934c20b698053371ed599",
          "sha256": "9c05213ce83b52e07c286bffce310e72c2f8865eb319c725e2da83155d663e54",
          "sha1": "b100620c5901d1a485acb5d4be5382600f1224b6",
          "md5": "669673bb9d94b4b88e956b3ad98da82e"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.1.20-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.20-RC2"
        }
      ]
    },
    {
      "name": "jvmJUnitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.20-RC2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.1.20-RC2.jar",
          "url": "kotlin-test-junit-2.1.20-RC2.jar",
          "size": 5078,
          "sha512": "1690643e2b941f11154928551793858474d2464732b5b735d9b08c690064fe6b7f69c44bf59574436a261ceb06c6c64393b5bb0210c934c20b698053371ed599",
          "sha256": "9c05213ce83b52e07c286bffce310e72c2f8865eb319c725e2da83155d663e54",
          "sha1": "b100620c5901d1a485acb5d4be5382600f1224b6",
          "md5": "669673bb9d94b4b88e956b3ad98da82e"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.1.20-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.20-RC2"
        }
      ]
    },
    {
      "name": "jvmJUnitSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-junit-2.1.20-RC2-sources.jar",
          "url": "kotlin-test-junit-2.1.20-RC2-sources.jar",
          "size": 2830,
          "sha512": "7e646d9971895dd20e122c2a51b0e062d0b03ef898e5886c17baa324ffdb651bf466b7169f828c3dd2f868145ae386f0520b0faa1b7017294742d07e4ebaa4b7",
          "sha256": "c411a0dad1218f3f652b6619f228fefee498903ee6e11c36c990fbc3fe823f18",
          "sha1": "48ca1b92544803c16b9042ae5b5976f6469e0a8c",
          "md5": "ff35307cfd380882a2b7a0d77f06e1b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.1.20-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.1.20-RC2"
        }
      ]
    }
  ]
}