{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.5.2/runtime-1.5.2.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.5.2.jar",
          "url": "runtime-desktop-1.5.2.jar",
          "size": 1165520,
          "sha512": "f62e96dbce82f7e7d37740298e494cbe7108c0f605ce06fd2b11e31c32fcdfeb53e0287fdcfdbd61994be465882ba60f413cecd46d5350814dd7827bd463ce34",
          "sha256": "d9d1e6d6cf3cd761ceadc43db5bd914b6b603d65bdb45b3a342317cd0dc26235",
          "sha1": "750cae784e9db6ae3e00c52489269febe42f087c",
          "md5": "a643b4b9d512bc062c342ede62cf99ca"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.5.2.jar",
          "url": "runtime-desktop-1.5.2.jar",
          "size": 1165520,
          "sha512": "f62e96dbce82f7e7d37740298e494cbe7108c0f605ce06fd2b11e31c32fcdfeb53e0287fdcfdbd61994be465882ba60f413cecd46d5350814dd7827bd463ce34",
          "sha256": "d9d1e6d6cf3cd761ceadc43db5bd914b6b603d65bdb45b3a342317cd0dc26235",
          "sha1": "750cae784e9db6ae3e00c52489269febe42f087c",
          "md5": "a643b4b9d512bc062c342ede62cf99ca"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "runtime-desktop-1.5.2-sources.jar",
          "url": "runtime-desktop-1.5.2-sources.jar",
          "size": 338632,
          "sha512": "fd17f6f39c5abd2c8068717e6a63237f397b82f30dcb31b0a0cda80638567ddafea1468e3b6ac2f7aea16fd12759228e486269a2401bf20e1aea529a4146340f",
          "sha256": "3acd5c5d65bf478824e9b4b94af693129fb3bb32a5e1d513d5e5e80a8ef875bd",
          "sha1": "8ec7beb9cfc06c4a37d493ef31a765c90f652da8",
          "md5": "5e519250aea7dc859f8810f6860fede8"
        }
      ]
    }
  ]
}