java_import(
    name = "explainer",
    jars = ["explainer.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "generator",
    jars = ["generator.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "shared",
    jars = ["shared.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
