# managed by go/iml_to_build
java_import(
    name = "explainer",
    jars = ["explainer.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "generator",
    jars = ["generator.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "shared",
    jars = ["shared.jar"],
    visibility = ["//visibility:public"],
)
