java_import(
    name = "archive-patcher",
    jars = [
        "explainer.jar",
        "generator.jar",
        "shared.jar",
    ],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
