{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.5.0-alpha03.aar",
          "url": "animation-core-1.5.0-alpha03.aar",
          "size": 1371173,
          "sha512": "c1fa4e126fe2b1b02e0c69a08dea8adead19be99bb905f90ebcebf919640f9d8abfb6ecabd310ea90c7b8f505d551249a990699043c6403129a5687ffd0b3bb8",
          "sha256": "92dad46d99fdeaf9c3a971b9969d41964f4d1e465c7f9918a333ed0ca726fe48",
          "sha1": "363bd3a484dcc093336071608022a61c486507f8",
          "md5": "0ae6ece97e80bb2a4834841d254e8449"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.5.0-alpha03.aar",
          "url": "animation-core-1.5.0-alpha03.aar",
          "size": 1371173,
          "sha512": "c1fa4e126fe2b1b02e0c69a08dea8adead19be99bb905f90ebcebf919640f9d8abfb6ecabd310ea90c7b8f505d551249a990699043c6403129a5687ffd0b3bb8",
          "sha256": "92dad46d99fdeaf9c3a971b9969d41964f4d1e465c7f9918a333ed0ca726fe48",
          "sha1": "363bd3a484dcc093336071608022a61c486507f8",
          "md5": "0ae6ece97e80bb2a4834841d254e8449"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.5.0-alpha03-sources.jar",
          "url": "animation-core-1.5.0-alpha03-sources.jar",
          "size": 76792,
          "sha512": "9cbf2c58cb84aa02fb37cf99d7494684c692b3362eda162ac56d50916e4d03b9393762752482f63418a20c8db0283097121ff2c069778a1088514fa9680228ec",
          "sha256": "60e5157d0283d3eaeeb78ccc60e3a9c37643a65926fc3c572b03652c038c13d5",
          "sha1": "ff43a4825582b6f760b7b727868786484c1ddab0",
          "md5": "7b62c0e84b18d199d6cf73c574e1c444"
        }
      ]
    }
  ]
}