{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-foundation-242",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-desktop",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-foundation-242-0.27.0.jar",
          "url": "jewel-foundation-242-0.27.0.jar",
          "size": 427431,
          "sha512": "a58e673830cbe00530d7c340a3e1b1c4f443aca701dbeb614e6a63b7602334e54f3e43e7324194ebfc2e760506fe294705cbcbfebb056bacba96622448976486",
          "sha256": "fb75b6ef66d3af38630a9a573f53989a7895d8d4850cfa90d47f06d9ead66156",
          "sha1": "1bcc2ccf66ff6a69a6b4a0d47367ae74ccb4ef4c",
          "md5": "8cd664cf39ecad9f2298dde8c9540cf6"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-desktop",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-foundation-242-0.27.0.jar",
          "url": "jewel-foundation-242-0.27.0.jar",
          "size": 427431,
          "sha512": "a58e673830cbe00530d7c340a3e1b1c4f443aca701dbeb614e6a63b7602334e54f3e43e7324194ebfc2e760506fe294705cbcbfebb056bacba96622448976486",
          "sha256": "fb75b6ef66d3af38630a9a573f53989a7895d8d4850cfa90d47f06d9ead66156",
          "sha1": "1bcc2ccf66ff6a69a6b4a0d47367ae74ccb4ef4c",
          "md5": "8cd664cf39ecad9f2298dde8c9540cf6"
        }
      ]
    }
  ]
}
