{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.platform",
    "module": "junit-platform-suite-api",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.12.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-suite-api-1.12.0.jar",
          "url": "junit-platform-suite-api-1.12.0.jar",
          "size": 26143,
          "sha512": "bcab3df86624a0884e0191a6a23dae5d04777de1bd3e17a7c4d554042921ab21ae8f88d0cb5e18d34a975ac3a46a933495c2ea62dc6c78a868c7ed6b39094d29",
          "sha256": "d460ff55f3740addbd780a760d3c7e9af5512b44daaf4b150a2fdc53bdc49be7",
          "sha1": "b9ae718cbd7acab7715fe586bdff747a8b8229f9",
          "md5": "fde24cda591cc210e3e33b33db966457"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.12.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-suite-api-1.12.0.jar",
          "url": "junit-platform-suite-api-1.12.0.jar",
          "size": 26143,
          "sha512": "bcab3df86624a0884e0191a6a23dae5d04777de1bd3e17a7c4d554042921ab21ae8f88d0cb5e18d34a975ac3a46a933495c2ea62dc6c78a868c7ed6b39094d29",
          "sha256": "d460ff55f3740addbd780a760d3c7e9af5512b44daaf4b150a2fdc53bdc49be7",
          "sha1": "b9ae718cbd7acab7715fe586bdff747a8b8229f9",
          "md5": "fde24cda591cc210e3e33b33db966457"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-suite-api-1.12.0-javadoc.jar",
          "url": "junit-platform-suite-api-1.12.0-javadoc.jar",
          "size": 219700,
          "sha512": "63d2d0ece0a2fb7f4c8e17ef29500b5d77cc175da8dee25252cf37efa2c5ed7546e0db0d98b187a705a533a8731fff5564721469e935703cb36a5551f29b126d",
          "sha256": "9ac958dad0da72aab176c0f5c23f12b409f8202016a284d401c7dbf9218dd5f9",
          "sha1": "f5df578547df235525c12a21a199627799503825",
          "md5": "5d1b7e165ba2946a56bd14cabf4b3649"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-suite-api-1.12.0-sources.jar",
          "url": "junit-platform-suite-api-1.12.0-sources.jar",
          "size": 37012,
          "sha512": "0b59823351bd15c8a12d488065047952359644634b8537ab1ddc4b161eaa96ebf753dbf42bc11cac432fe50a92f15a4c9db5d93d20e4da1092b40d725659bb8e",
          "sha256": "9a0be94aa7084a730005221c1c7d0b705bfd397d8ddc97d7f21262c1251a0e3a",
          "sha1": "1347af8d998a9da6dbf6eb830b97676999a7a87f",
          "md5": "d77d397f27f24901fc23ee8081b3fbe8"
        }
      ]
    }
  ]
}
