{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.0.0.aar",
          "url": "animation-1.0.0.aar",
          "size": 1249726,
          "sha512": "486de7caaaa62c2344a52fe03251b6f91cbdd073187340b819c13f1b9b76c7eda96f4bf38f366addc0e2647b84c7743f6021baf421f371f08606b3d26630e925",
          "sha256": "06a01ac38d5d8c1177de64bfe973b1d5b085a0399b216ca3d1d2ae90e9685726",
          "sha1": "3a132ffa3356029cb2544a1d6e4b8efa3312ed74",
          "md5": "89cb39ebff0e1c38802993b622adb2fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.0.0.aar",
          "url": "animation-1.0.0.aar",
          "size": 1249726,
          "sha512": "486de7caaaa62c2344a52fe03251b6f91cbdd073187340b819c13f1b9b76c7eda96f4bf38f366addc0e2647b84c7743f6021baf421f371f08606b3d26630e925",
          "sha256": "06a01ac38d5d8c1177de64bfe973b1d5b085a0399b216ca3d1d2ae90e9685726",
          "sha1": "3a132ffa3356029cb2544a1d6e4b8efa3312ed74",
          "md5": "89cb39ebff0e1c38802993b622adb2fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-1.0.0-sources.jar",
          "url": "animation-1.0.0-sources.jar",
          "size": 37035,
          "sha512": "c8dd5349bb81f8abe41ed31e2d96dae36f8d49a58bdb9b739d4ebbbb1d11d98a2f83b8477da44cc613f08eb453b91c5340cede8537435f9badcb459573799a85",
          "sha256": "3baf8e47e8c7600cf243706a93e20596bcacfbfcd1e4fed0c61ca453a627684c",
          "sha1": "e6e8324157b87ff500fa6e0de4a9272f5bdc37ba",
          "md5": "52baf39ee09ff3f6a5ae44d9495910fc"
        }
      ]
    }
  ]
}
