{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.accompanist",
    "module": "accompanist-appcompat-theme",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "accompanist-appcompat-theme-0.28.0.aar",
          "url": "accompanist-appcompat-theme-0.28.0.aar",
          "size": 30667,
          "sha512": "38407b1266f9b7059df3ad33dd1db7eb20bd7377b4d29c37f17c420ca16a0d8707c660180fb296216a8200ac20ffc1a05e314895b7ab15c3d9ab26ea23782944",
          "sha256": "93b8b1bf48ab3a29b1f578efcff0edcdcd50fdf1b167a14a7c4356ab3d12f2df",
          "sha1": "120d6d64f622096d51d3f290bd6576c71a35bc5e",
          "md5": "eaf47f50d65b0c415d69c730fffb5eac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "accompanist-appcompat-theme-0.28.0.aar",
          "url": "accompanist-appcompat-theme-0.28.0.aar",
          "size": 30667,
          "sha512": "38407b1266f9b7059df3ad33dd1db7eb20bd7377b4d29c37f17c420ca16a0d8707c660180fb296216a8200ac20ffc1a05e314895b7ab15c3d9ab26ea23782944",
          "sha256": "93b8b1bf48ab3a29b1f578efcff0edcdcd50fdf1b167a14a7c4356ab3d12f2df",
          "sha1": "120d6d64f622096d51d3f290bd6576c71a35bc5e",
          "md5": "eaf47f50d65b0c415d69c730fffb5eac"
        }
      ]
    }
  ]
}
