{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.0-alpha02.aar",
          "url": "material3-1.0.0-alpha02.aar",
          "size": 652495,
          "sha512": "5b1bc4701745bf3cc7e6780e725e5b7f980ab4acc14f4485df999ca4ac4577770b4efac89aa71f8639a58323d689540c1a8337ac0213c73ead0dd9088ab2d68c",
          "sha256": "7ac8f635b828286170de48aad14d82b023c79c7f6bd1cc46aec5427bbde3b56c",
          "sha1": "7b9f7737649a832c0436797570d3060f0a9b18d1",
          "md5": "71a66ef130f54ea83f020ca7cab0ee2f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.0-alpha02.aar",
          "url": "material3-1.0.0-alpha02.aar",
          "size": 652495,
          "sha512": "5b1bc4701745bf3cc7e6780e725e5b7f980ab4acc14f4485df999ca4ac4577770b4efac89aa71f8639a58323d689540c1a8337ac0213c73ead0dd9088ab2d68c",
          "sha256": "7ac8f635b828286170de48aad14d82b023c79c7f6bd1cc46aec5427bbde3b56c",
          "sha1": "7b9f7737649a832c0436797570d3060f0a9b18d1",
          "md5": "71a66ef130f54ea83f020ca7cab0ee2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-1.0.0-alpha02-sources.jar",
          "url": "material3-1.0.0-alpha02-sources.jar",
          "size": 117536,
          "sha512": "d0132c2eb25e8f7c64d6a8e84e24015e14ce3f55c19a27473841bffc6a7c36a7f10fa5330f4b0b0977729b52b268b9d7bb94e9380c7f52b0c34f6580eeb252f0",
          "sha256": "3843163c31d559c6d589dc2925e92583bae9fb7ff99d080f31d93ccd175896e2",
          "sha1": "0b60fc004849b48ad5b80f7b51b8ed6a7af5f7b0",
          "md5": "f2c18c8c6ef881f1d3ff9cb4a4a6d30c"
        }
      ]
    }
  ]
}
