{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate-compose/1.3.4/savedstate-compose-1.3.4.module",
    "group": "org.jetbrains.androidx.savedstate",
    "module": "savedstate-compose",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-compose-desktop-1.3.4.jar",
          "url": "savedstate-compose-desktop-1.3.4.jar",
          "size": 11569,
          "sha512": "d3cc185957e57246d41c7281e45d7f6f77239210338fd5740fe89a98568e37a984ec5c9c177b1da60917a44e85d15307df8b71669ef9b94514b39698a74bd664",
          "sha256": "5228d0732128011747c8d56f65156505a0b2d29b000d398c6f1979bc0ef42113",
          "sha1": "9d8414669e7651d086fe84dc0f940cd16abd6412",
          "md5": "f2aeaf05d0bac94d6b4cb7b4101011c7"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-compose-desktop-1.3.4.jar",
          "url": "savedstate-compose-desktop-1.3.4.jar",
          "size": 11569,
          "sha512": "d3cc185957e57246d41c7281e45d7f6f77239210338fd5740fe89a98568e37a984ec5c9c177b1da60917a44e85d15307df8b71669ef9b94514b39698a74bd664",
          "sha256": "5228d0732128011747c8d56f65156505a0b2d29b000d398c6f1979bc0ef42113",
          "sha1": "9d8414669e7651d086fe84dc0f940cd16abd6412",
          "md5": "f2aeaf05d0bac94d6b4cb7b4101011c7"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "savedstate-compose-desktop-1.3.4-sources.jar",
          "url": "savedstate-compose-desktop-1.3.4-sources.jar",
          "size": 7307,
          "sha512": "8699c90eebf7f6b9d004bf7b934d6f5d39695896f1761abf6032b81f62c79c4cb1e333f9a929f860e53e404bfb794af8d9e63e3c1f05921ce20f23db90769f24",
          "sha256": "13b8b09c184d95f0b063964e9b4990a1680dbb8435561c7219578822d7fbb2ee",
          "sha1": "6de83e5a8ac7d8567c5357aa33a035cb8db21912",
          "md5": "f7b7b252f89d71cc49e6ef4e192e82b7"
        }
      ]
    }
  ]
}