{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.databinding",
    "module": "viewbinding",
    "version": "9.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-9.1.0.aar",
          "url": "viewbinding-9.1.0.aar",
          "size": 1868,
          "sha512": "fe095724f28518ef9402450089c71381e478d3ee26ab3bfeae619024f4d43a17b2e85460674301234482dc1a3e0e8e4641653ec635a7914210355b7b1663ae06",
          "sha256": "d1ce9369e2740ece69dbabd2bb63d71a12c1c87f6757cb2b644705944d9f5608",
          "sha1": "6415db11b28e8eeb314ee993fd01598265b598f8",
          "md5": "30e6c3fad042aad30f195c90c56fd258"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-9.1.0.aar",
          "url": "viewbinding-9.1.0.aar",
          "size": 1868,
          "sha512": "fe095724f28518ef9402450089c71381e478d3ee26ab3bfeae619024f4d43a17b2e85460674301234482dc1a3e0e8e4641653ec635a7914210355b7b1663ae06",
          "sha256": "d1ce9369e2740ece69dbabd2bb63d71a12c1c87f6757cb2b644705944d9f5608",
          "sha1": "6415db11b28e8eeb314ee993fd01598265b598f8",
          "md5": "30e6c3fad042aad30f195c90c56fd258"
        }
      ]
    }
  ]
}
