{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.rising3",
    "module": "semver",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b22htbuhnfdojo3rse4zgvz35i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "semver-0.3.1.jar",
          "url": "semver-0.3.1.jar",
          "size": 10433,
          "sha512": "359077de9b29e0d3bb7a81ae826d32991e2e47ed49e5b780ddf6faf9cf2129903b56f2821f84ef2cd22fb738a7cda73805f5c3f42065ec15eb0fb0de96cca103",
          "sha256": "c8b0faba39095bc9f838ecb0c9cd8d5f7a911fb3dc88a11ea694505bbc74e57b",
          "sha1": "804d4dc458b4491e847ae4739d084e27708de7d3",
          "md5": "cc6300b387c9059b3ca913cfef1cda91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "semver-0.3.1.jar",
          "url": "semver-0.3.1.jar",
          "size": 10433,
          "sha512": "359077de9b29e0d3bb7a81ae826d32991e2e47ed49e5b780ddf6faf9cf2129903b56f2821f84ef2cd22fb738a7cda73805f5c3f42065ec15eb0fb0de96cca103",
          "sha256": "c8b0faba39095bc9f838ecb0c9cd8d5f7a911fb3dc88a11ea694505bbc74e57b",
          "sha1": "804d4dc458b4491e847ae4739d084e27708de7d3",
          "md5": "cc6300b387c9059b3ca913cfef1cda91"
        }
      ]
    }
  ]
}
