{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle",
    "module": "gradle-tooling-api",
    "version": "9.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-tooling-api-9.4.1-sources.jar",
          "url": "gradle-tooling-api-9.4.1-sources.jar",
          "size": 6382566,
          "sha512": "40fd4f954b59537ef42975b46b6148f9977a9b2ffadd5f6adfd00a8494df8f0771c6dd7f8407938d35a2b2517cd99ed14ac039ba9f6c9e40f1e90dd692790cfd",
          "sha256": "446e9da092a4b7dd06833c96efd09101d91dafd4b29c6304cba86ce8f933a152",
          "sha1": "9dd5cfdce1cf5a690ad2af3e028d7defcd567bee",
          "md5": "86db07e37226c6f732db3775f12413ed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-tooling-api-9.4.1-javadoc.jar",
          "url": "gradle-tooling-api-9.4.1-javadoc.jar",
          "size": 1976000,
          "sha512": "519d607e746b63f3eccc6d0ccafd28386bf275bd1517984dd2a1ac5ec183d8aec8501a7b84e6bb96f76c4ce8ae28887c96de1733f516a9f1619e464e0990335e",
          "sha256": "5d5d0c9b35570e6e4bc188182dd2e94d5805bc2c0e05d013c67ff791e05b74a6",
          "sha1": "485f759fdebf1aae63948f108c1d690feff7a152",
          "md5": "91c502ff73317e354f26570a23940f36"
        }
      ]
    },
    {
      "name": "shadedRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-tooling-api-9.4.1.jar",
          "url": "gradle-tooling-api-9.4.1.jar",
          "size": 3046309,
          "sha512": "d71709c89b940db6754bf5d9c768ee4931f4cd6cd0ba5ecd54275b758d007a425ee7fe4a92827286bdb5161c1a20aa4f87cbde583b0f9b8da635338595e3ac28",
          "sha256": "705fa5d5263b9ccb756f4721ac45a0ca2efb318f69d4dece1b90e3b59275431c",
          "sha1": "aca2d1955902e2a3df98c7e9d13057855510f232",
          "md5": "75de58dc662bc4a2953d5e12bac75e50"
        }
      ]
    }
  ]
}
