{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.databinding",
    "module": "baseLibrary",
    "version": "7.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "baseLibrary-7.0.0.jar",
          "url": "baseLibrary-7.0.0.jar",
          "size": 16038,
          "sha512": "6f4d0b52e4fa08898fbdffe0babce701a9bcfa81f71b97903aba64ade9a0bbba677ad39cb29f875cb2371722eb65b0317f77ab04202e38c6d39c6d7a748a5d4d",
          "sha256": "582b8fa0eb435d95dc9e31a0ed04c22a1c357c2b92d9baeaeef3fad0c52ccb26",
          "sha1": "9e25ce80899c8c16f5730bdbef4d196416623d3b",
          "md5": "2661d70c523d946d865ce26c56bc9204"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "baseLibrary-7.0.0.jar",
          "url": "baseLibrary-7.0.0.jar",
          "size": 16038,
          "sha512": "6f4d0b52e4fa08898fbdffe0babce701a9bcfa81f71b97903aba64ade9a0bbba677ad39cb29f875cb2371722eb65b0317f77ab04202e38c6d39c6d7a748a5d4d",
          "sha256": "582b8fa0eb435d95dc9e31a0ed04c22a1c357c2b92d9baeaeef3fad0c52ccb26",
          "sha1": "9e25ce80899c8c16f5730bdbef4d196416623d3b",
          "md5": "2661d70c523d946d865ce26c56bc9204"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "baseLibrary-7.0.0-javadoc.jar",
          "url": "baseLibrary-7.0.0-javadoc.jar",
          "size": 451338,
          "sha512": "ac4b2adb08e1eb3ca18cae1ce79b28c417b92bfda7357d801f482ac823f4ee48a2c2b8f99f38f6d9b5b5889959cc91101ffd0ac1d100bd14a6184c162a400886",
          "sha256": "466e304549bb12bbd06cb1b127fae98c6cf9efef1e9a3c30d53d808561d80a44",
          "sha1": "c88494157183d9079176138a8b5e5b4d6fd5b07e",
          "md5": "9d0d0da9142e5b476434fff171d509e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "baseLibrary-7.0.0-sources.jar",
          "url": "baseLibrary-7.0.0-sources.jar",
          "size": 45860,
          "sha512": "6e4daaa720fc5ede17ed70e6137b474e30765d8258fa8164763c8551768e8934cdc6ad2454ed2a26a9f0175742346900aa37f9030b2cb0ab26cc6ee234cff881",
          "sha256": "ad973b90990207348bf9ad5b4d6b07f40eb76f682ae9ed5aa90fc0d106502924",
          "sha1": "ffe39c5319b9aae566e30e09b4fb2a388be3a95e",
          "md5": "bd7165152bce8603e6606e67cf8367b5"
        }
      ]
    }
  ]
}
