{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "sandbox",
    "version": "4.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadowapi",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "sandbox-4.8.2.jar",
          "url": "sandbox-4.8.2.jar",
          "size": 130804,
          "sha512": "84e8ed3995752b86c1a9be0276e9dc8df967746d175f6f1d1fff3c82b65fb06b07148330d9c8ec94744ba746e1287b1e070eb8e1ea337cdb16ef49d6e4a8de5f",
          "sha256": "45b3a1ecc1064ee5ad9834623af4ce32351ca840395ec6a28f773b284df4b528",
          "sha1": "e4ce422833d778aeb4ef4867acad9a2647c38783",
          "md5": "b5919f16d057d96c8dc742d98297a876"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadowapi",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "sandbox-4.8.2.jar",
          "url": "sandbox-4.8.2.jar",
          "size": 130804,
          "sha512": "84e8ed3995752b86c1a9be0276e9dc8df967746d175f6f1d1fff3c82b65fb06b07148330d9c8ec94744ba746e1287b1e070eb8e1ea337cdb16ef49d6e4a8de5f",
          "sha256": "45b3a1ecc1064ee5ad9834623af4ce32351ca840395ec6a28f773b284df4b528",
          "sha1": "e4ce422833d778aeb4ef4867acad9a2647c38783",
          "md5": "b5919f16d057d96c8dc742d98297a876"
        }
      ]
    }
  ]
}
