{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.21.2.jar",
          "url": "checker-qual-3.21.2.jar",
          "size": 222142,
          "sha512": "a8fb8591388ecd5bfda44472c2252671b8bf707b973a4281e89a8eff522044bd20c25a8aa4a5d00b3f4f5f72d45db1bdeb1340e585b3efcd770bd1413810cc0f",
          "sha256": "7e8554c902b9b839e61396cfe3a64c84ecabfb8eb652c410bfd8e4f5c1a8ece8",
          "sha1": "630f15607e9850363c10c81283a65bfbce622146",
          "md5": "a4ceb77f13e6dcc1cb34d55e3f87f4fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.21.2.jar",
          "url": "checker-qual-3.21.2.jar",
          "size": 222142,
          "sha512": "a8fb8591388ecd5bfda44472c2252671b8bf707b973a4281e89a8eff522044bd20c25a8aa4a5d00b3f4f5f72d45db1bdeb1340e585b3efcd770bd1413810cc0f",
          "sha256": "7e8554c902b9b839e61396cfe3a64c84ecabfb8eb652c410bfd8e4f5c1a8ece8",
          "sha1": "630f15607e9850363c10c81283a65bfbce622146",
          "md5": "a4ceb77f13e6dcc1cb34d55e3f87f4fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.21.2-javadoc.jar",
          "url": "checker-qual-3.21.2-javadoc.jar",
          "size": 957968,
          "sha512": "270070013569a1a4ef2a39ff7e78e8403020fd3f94a3b15c0612be091d18cc6160d5ede6c8a4792f357fe2d04ddbe8e4c1287737569b8652f8b4f1587b377270",
          "sha256": "366e9ad70836ca9dc8a5d5e89f721d123f5405df0fd0c4443cb6cdaa68718a9f",
          "sha1": "0e973e76df80c9bf5c3ca0c18eefe3f2ab07053b",
          "md5": "4ea3e9da4754c5acb6adbbaa10fa0f3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.21.2-sources.jar",
          "url": "checker-qual-3.21.2-sources.jar",
          "size": 252646,
          "sha512": "e5116a3ea699c5040db63051914dc58c07f9d612f6545c4a81cedf294f06005cd984454ed4465e90c1c0cfb8b9e206ed20d8670fd2dc57f8745b4bb05cdacce5",
          "sha256": "4f85e422b5da3c73990e894f1ed4cac45358f34fb4b979687848301584eccb57",
          "sha1": "a5b7540037c3cd60ef5c4100e11507f60b331f20",
          "md5": "cde98b80591eb91a7f02bf1e5838d2cc"
        }
      ]
    }
  ]
}
