{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material3",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "14500312"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.5.6-sources.jar",
          "url": "compose-material3-1.5.6-sources.jar",
          "size": 367524,
          "sha512": "26ed10ca5d42f10f73a0b6504f4b871c519bdc90a8149515831bc1e56e819715d6425287e7746a08f95106e1354e6d00ff2e11d6b389127e35cba9cc2d6739ca",
          "sha256": "dd4942fa0488067a244426ba7e1ff26ca82242d037cc130b4f952e6aaf06aa65",
          "sha1": "fbd248218eaa3afb772653b259eb995e9f815a1a",
          "md5": "566c4363771718c229e44a8468ddf7bf"
        },
        {
          "name": "compose-material3-1.5.6-samples-sources.jar",
          "url": "compose-material3-1.5.6-samples-sources.jar",
          "size": 62109,
          "sha512": "c1c8748cecef09576e246f291da332206342917a19a2443a7566457db3a786c699e1bdc64f30c2d8b323f8a4d961aed72654f85aabf99a25af616e115b3de413",
          "sha256": "0abc0a8e9ac884206e6d48deaeaaddb1f46f810fdc4e4013b6ae267b7d70e71d",
          "sha1": "166f0003c33dfb7007061e0f8f5c48d7a09d5f0b",
          "md5": "bd3318fd3d84ca3deb63f8da168c3f9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.5.6.aar",
          "url": "compose-material3-1.5.6.aar",
          "size": 2102898,
          "sha512": "0ba548632b8468e9404dfdc7b1d6c4b13b409902b444833fe1cc460a64962205e2439640c052de3440c6e1b040200f7206f3bc2f52ee540975cbe5aabfe452b7",
          "sha256": "cb6ebf5bc1a27c500451f2decc2e00fb8cdbfb48d08650094aaf94ff38b68543",
          "sha1": "9b4c284b79ec72149a476d5de77d6e7479cc6efd",
          "md5": "35cd05dbe20615cd751c1b52dd939160"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.5.6.aar",
          "url": "compose-material3-1.5.6.aar",
          "size": 2102898,
          "sha512": "0ba548632b8468e9404dfdc7b1d6c4b13b409902b444833fe1cc460a64962205e2439640c052de3440c6e1b040200f7206f3bc2f52ee540975cbe5aabfe452b7",
          "sha256": "cb6ebf5bc1a27c500451f2decc2e00fb8cdbfb48d08650094aaf94ff38b68543",
          "sha1": "9b4c284b79ec72149a476d5de77d6e7479cc6efd",
          "md5": "35cd05dbe20615cd751c1b52dd939160"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.6"
          },
          "reason": "compose-material3 is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.5.6-versionMetadata.json",
          "url": "compose-material3-1.5.6-versionMetadata.json",
          "size": 220824,
          "sha512": "79ebf23e9f3878cbc56b902bd17cb5bfc9d3235a35ef2e703127af142f1ea3dbaa10a2e24f6e1a4151b7f6ad30d3c5bead6d3bab7aeddf0a6bf59b5e928c5ae2",
          "sha256": "c7939418a4951079335d660a9194a5cfb674252ca3003fe43fcb673dc85a0c4d",
          "sha1": "a239aa0de4c8ca27809924423dfd104ae434926e",
          "md5": "7d1a10e681322b646ef8011556c04b0e"
        }
      ]
    }
  ]
}