{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression",
    "version": "1.0.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.0.0-alpha09.aar",
          "url": "protolayout-expression-1.0.0-alpha09.aar",
          "size": 158151,
          "sha512": "4c455ae5d0b7666641be62a27954d2d7ac3b5ecdd8d4c5d3b9cf0de7ffa16ba74242a69c6a255abcc177ff3c7856d4310f42a351a7902c72ec236c9e1d73520b",
          "sha256": "d5248578dcd77694742b3bef8cac8f0e39e1cb9b1d5174e88d341633cf74e162",
          "sha1": "0f751e9d5d93c53f67c1eef981da340c01f11541",
          "md5": "4a22e13232be6828eb5f9246075d5253"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.0.0-alpha09.aar",
          "url": "protolayout-expression-1.0.0-alpha09.aar",
          "size": 158151,
          "sha512": "4c455ae5d0b7666641be62a27954d2d7ac3b5ecdd8d4c5d3b9cf0de7ffa16ba74242a69c6a255abcc177ff3c7856d4310f42a351a7902c72ec236c9e1d73520b",
          "sha256": "d5248578dcd77694742b3bef8cac8f0e39e1cb9b1d5174e88d341633cf74e162",
          "sha1": "0f751e9d5d93c53f67c1eef981da340c01f11541",
          "md5": "4a22e13232be6828eb5f9246075d5253"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.0.0-alpha09-sources.jar",
          "url": "protolayout-expression-1.0.0-alpha09-sources.jar",
          "size": 44050,
          "sha512": "0328fd3ca3d2e4a75bc132ec0239900d1789df8b052ca7065ed6032d88f32833d4fd3eadc47564c9c1d907ab89976f08b08b792ec70bea8895aea235f32e42d2",
          "sha256": "973b502dd8c4757890cf76ad848fe9398e08945365b50de695884f31d610130e",
          "sha1": "a403003a0b86e3f470b2431ef5e136e4f977c779",
          "md5": "34ace655bb1bfc96d44c48d8b923de9d"
        }
      ]
    }
  ]
}