{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.8.0-alpha03/material-ripple-1.8.0-alpha03.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.8.0-alpha03.aar",
          "size": 104442,
          "sha512": "e021d7f6cff99db4a91b3bd612cc45b4e35548e9221c8ca304b3751b6b45d7ef50f4610bc35078ee537075a4c399edd0077f235e5f428d53539358e490b6e2b7",
          "sha256": "dc0b6017141512e8899e6fa31693b715cacad55ed1b8fe0f9aa79291b6ba68dc",
          "sha1": "76c9dfe79a3e7136805fd71b2281b448b8dd2d90",
          "md5": "e5422d00a1186a9e46493e940c96e201"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.8.0-alpha03.aar",
          "size": 104442,
          "sha512": "e021d7f6cff99db4a91b3bd612cc45b4e35548e9221c8ca304b3751b6b45d7ef50f4610bc35078ee537075a4c399edd0077f235e5f428d53539358e490b6e2b7",
          "sha256": "dc0b6017141512e8899e6fa31693b715cacad55ed1b8fe0f9aa79291b6ba68dc",
          "sha1": "76c9dfe79a3e7136805fd71b2281b448b8dd2d90",
          "md5": "e5422d00a1186a9e46493e940c96e201"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-ripple-android-1.8.0-alpha03-sources.jar",
          "url": "material-ripple-android-1.8.0-alpha03-sources.jar",
          "size": 30897,
          "sha512": "00699f9a7091581067a373aea80dffe4bcef79dd886c19621a5952d76fe2938155f281289e570be47ff54360ea8108efa8bce380df1ad43d878858ebe9efcaa1",
          "sha256": "20b0ada16ff9e2ef8935361327df8416d089242fb9a757610ba92e8b15381a22",
          "sha1": "1d3a517b69d5d6218c258179ed3496e4cc3794cb",
          "md5": "cd4da3410ffec392a79403cd4d6e5574"
        }
      ]
    }
  ]
}