filegroup(
    name = "testData",
    srcs = [
        "mobilenet_metadata.tflite",
        "mobilenet_quant_metadata.tflite",
        "mobilenet_quant_no_metadata.tflite",
    ],
    visibility = [
        "//tools/adt/idea/mlkit:__pkg__",
        "//tools/base/build-system/integration-test/application:__pkg__",
        "//tools/base/mlkit-common:__pkg__",
    ],
)
