filegroup(
    name = "testData",
    srcs = glob(["*.tflite"]),
    visibility = [
        "//tools/adt/idea/mlkit:__pkg__",
        "//tools/base/build-system/integration-test/application:__pkg__",
        "//tools/base/mlkit-common:__pkg__",
    ],
)
