filegroup(
    name = "testData",
    srcs = glob(["**/*"]),
    visibility = [
        "//tools/adt/idea/android-uitests:__pkg__",
        "//tools/adt/idea/ide-perf-tests:__pkg__",
        "//tools/adt/idea/mlkit:__pkg__",
        "//tools/base/build-system/integration-test/application:__pkg__",
        "//tools/base/build-system/integration-test/connected:__pkg__",
        "//tools/base/mlkit-common:__pkg__",
    ],
)
