{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-ide-laf-bridge",
    "version": "0.13.2-ij-233",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui",
          "version": {
            "requires": "0.13.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ide-laf-bridge-platform-specific",
          "version": {
            "requires": "0.13.2-ij-233"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-ide-laf-bridge-0.13.2-ij-233.jar",
          "url": "jewel-ide-laf-bridge-0.13.2-ij-233.jar",
          "size": 107203,
          "sha512": "3038d6e9f5a250d8ec53b0f2d9d504ada62bd64dd6a3cdb6f017ce100c3d3307e691eda96711c0e2b2afe839854054f79392492cb3e07d5e1b564f63dcf22df0",
          "sha256": "558d90095c877a5adc0cd7a52d6bd8bb77ae1f32de6c91a3351d9347f6ac3303",
          "sha1": "7de2960658d1bdb303acb5a8a09d530ef9a8a0eb",
          "md5": "d10effe9abb792677fdb884188be0279"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui",
          "version": {
            "requires": "0.13.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ide-laf-bridge-platform-specific",
          "version": {
            "requires": "0.13.2-ij-233"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-ide-laf-bridge-0.13.2-ij-233.jar",
          "url": "jewel-ide-laf-bridge-0.13.2-ij-233.jar",
          "size": 107203,
          "sha512": "3038d6e9f5a250d8ec53b0f2d9d504ada62bd64dd6a3cdb6f017ce100c3d3307e691eda96711c0e2b2afe839854054f79392492cb3e07d5e1b564f63dcf22df0",
          "sha256": "558d90095c877a5adc0cd7a52d6bd8bb77ae1f32de6c91a3351d9347f6ac3303",
          "sha1": "7de2960658d1bdb303acb5a8a09d530ef9a8a0eb",
          "md5": "d10effe9abb792677fdb884188be0279"
        }
      ]
    }
  ]
}
