{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.9.0/animation-core-1.9.0.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.9.0.jar",
          "url": "animation-core-desktop-1.9.0.jar",
          "size": 380643,
          "sha512": "b618551cce4991b563478540b32fb7f0359373b20c95022926959d6b83c35f7abda42c330ce95095c0a1916fe31a79feaea891c4f0cea08bf9684d2373b9aec8",
          "sha256": "76cf4d09b5312f9a9e46e80a270c76a7157a93819493feb7076f9c8c98610605",
          "sha1": "47a335ae4cb43a1e5f950a1a6a44ac86be531ba5",
          "md5": "0d02678252affd90119d35c260a72a42"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.9.0.jar",
          "url": "animation-core-desktop-1.9.0.jar",
          "size": 380643,
          "sha512": "b618551cce4991b563478540b32fb7f0359373b20c95022926959d6b83c35f7abda42c330ce95095c0a1916fe31a79feaea891c4f0cea08bf9684d2373b9aec8",
          "sha256": "76cf4d09b5312f9a9e46e80a270c76a7157a93819493feb7076f9c8c98610605",
          "sha1": "47a335ae4cb43a1e5f950a1a6a44ac86be531ba5",
          "md5": "0d02678252affd90119d35c260a72a42"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "animation-core-desktop-1.9.0-sources.jar",
          "url": "animation-core-desktop-1.9.0-sources.jar",
          "size": 110958,
          "sha512": "8c9f6a3a670b134ef9036d4884d955a5d9c98599aac447a8ec9cc6564185e79f42d24d962882d3eb158cc96aac5601446534353a3552f3c3492ad638923522bc",
          "sha256": "3670839cd23f441c048b44e975f13c058d5869430c48bcf21e9dac2d0d5ccb79",
          "sha1": "6b6b15d88b2762ec6d4dd3332127ce80c5749833",
          "md5": "435f55ed9602f08e979a931ccbddc468"
        }
      ]
    }
  ]
}