{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-utils",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.22.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-metadata-2.3.5.jar",
          "url": "ktor-utils-2.3.5.jar",
          "size": 57190,
          "sha512": "9f01f62d2c17cc2a43b1759568063cf6ffc5b5a501628cac1f70a411af482cef5d3b637f1cbde684bed90f095bf1dc40d8802ee1c934a1dc93a23c1922db8416",
          "sha256": "5476b5e899747b2733ff1b5b8508b06961b6c1b24883e951595e8d84653cebaf",
          "sha1": "923e1405509282818e30d2854b392d37780f9de7",
          "md5": "2e316883849e0b768a849cd23e53bb40"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-utils-kotlin-2.3.5-sources.jar",
          "url": "ktor-utils-2.3.5-sources.jar",
          "size": 75853,
          "sha512": "cc04fc33d2cc5880a4ea6702860baa9acf6e1af2e4bbb6011c3c087735425c880e07bac2f8c6ea7f7a86ab3666b038cc3528149f141c43b62366254a0217cc9b",
          "sha256": "f323b2163e7f81ae2e4002a3ab843ab6f8f302cc692c04d5ef4110b51480ca5a",
          "sha1": "aa29ed3c1930770514ec9b6fc590c83213df3992",
          "md5": "9721b39071e9c621ee9281d61b6921cf"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iosarm64/2.3.5/ktor-utils-iosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iosarm64/2.3.5/ktor-utils-iosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iosarm64/2.3.5/ktor-utils-iosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iossimulatorarm64/2.3.5/ktor-utils-iossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iossimulatorarm64/2.3.5/ktor-utils-iossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iossimulatorarm64/2.3.5/ktor-utils-iossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iosx64/2.3.5/ktor-utils-iosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iosx64/2.3.5/ktor-utils-iosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-iosx64/2.3.5/ktor-utils-iosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-iosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-utils-js/2.3.5/ktor-utils-js-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-js",
        "version": "2.3.5"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-utils-js/2.3.5/ktor-utils-js-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-js",
        "version": "2.3.5"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-utils-js/2.3.5/ktor-utils-js-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-js",
        "version": "2.3.5"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-utils-jvm/2.3.5/ktor-utils-jvm-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-jvm",
        "version": "2.3.5"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-utils-jvm/2.3.5/ktor-utils-jvm-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-jvm",
        "version": "2.3.5"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-utils-jvm/2.3.5/ktor-utils-jvm-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-jvm",
        "version": "2.3.5"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-linuxarm64/2.3.5/ktor-utils-linuxarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-linuxarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-linuxarm64/2.3.5/ktor-utils-linuxarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-linuxarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-linuxx64/2.3.5/ktor-utils-linuxx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-linuxx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-linuxx64/2.3.5/ktor-utils-linuxx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-linuxx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-macosarm64/2.3.5/ktor-utils-macosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-macosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-macosarm64/2.3.5/ktor-utils-macosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-macosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-macosarm64/2.3.5/ktor-utils-macosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-macosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-macosx64/2.3.5/ktor-utils-macosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-macosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-macosx64/2.3.5/ktor-utils-macosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-macosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-macosx64/2.3.5/ktor-utils-macosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-macosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-mingwx64/2.3.5/ktor-utils-mingwx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-mingwx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-mingwx64/2.3.5/ktor-utils-mingwx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-mingwx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvosarm64/2.3.5/ktor-utils-tvosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvosarm64/2.3.5/ktor-utils-tvosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvosarm64/2.3.5/ktor-utils-tvosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvossimulatorarm64/2.3.5/ktor-utils-tvossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvossimulatorarm64/2.3.5/ktor-utils-tvossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvossimulatorarm64/2.3.5/ktor-utils-tvossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvosx64/2.3.5/ktor-utils-tvosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvosx64/2.3.5/ktor-utils-tvosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-tvosx64/2.3.5/ktor-utils-tvosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-tvosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosarm32/2.3.5/ktor-utils-watchosarm32-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosarm32",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosarm32/2.3.5/ktor-utils-watchosarm32-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosarm32",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosarm32/2.3.5/ktor-utils-watchosarm32-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosarm32",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosarm64/2.3.5/ktor-utils-watchosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosarm64/2.3.5/ktor-utils-watchosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosarm64/2.3.5/ktor-utils-watchosarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchossimulatorarm64/2.3.5/ktor-utils-watchossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchossimulatorarm64/2.3.5/ktor-utils-watchossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchossimulatorarm64/2.3.5/ktor-utils-watchossimulatorarm64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchossimulatorarm64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosx64/2.3.5/ktor-utils-watchosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosx64/2.3.5/ktor-utils-watchosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosx64",
        "version": "2.3.5"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-utils-watchosx64/2.3.5/ktor-utils-watchosx64-2.3.5.module",
        "group": "io.ktor",
        "module": "ktor-utils-watchosx64",
        "version": "2.3.5"
      }
    }
  ]
}
