load("//tools/base/bazel:maven.bzl", "maven_java_import", "maven_pom")

maven_java_import(
    name = "uast-145.597.3",
    pom = ":uast-145.597.3.pom",
    jars = ["uast-145.597.3.jar"],
    visibility = ["//visibility:public"],
)

maven_pom(
    name = "uast-145.597.3.pom",
    artifact = "uast",
    group = "com.android.tools.external.com-intellij",
    version = "145.597.3",
)

maven_java_import(
    name = "uast-162.2228.14",
    pom = ":uast-162.2228.14.pom",
    jars = ["uast-162.2228.14.jar"],
    visibility = ["//visibility:public"],
)

maven_pom(
    name = "uast-162.2228.14.pom",
    artifact = "uast",
    group = "com.android.tools.external.intellij",
    version = "162.2228.14",
)
