{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest-lint",
    "version": "1.11.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0",
      "buildId:": "15142220"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-lint-1.11.0-rc01.jar",
          "url": "ui-test-manifest-lint-1.11.0-rc01.jar",
          "size": 12617,
          "sha512": "c0de290c1d0dcf822cef7dc69893f755580611f81997db008d816e1cc4e9f8dd4e2c5b1235985712a2a8eabb24ea35df4ab019866988e7e700c92e2e8c002459",
          "sha256": "3780cd48e804cc31fa2dce0e6211193d744e2f86824fbdc99c021e81a5f1ff0a",
          "sha1": "4e707a4d131404cc8c2e39564ef8f6010d05cd05",
          "md5": "cf0d26cf373cecb02171503decefc1ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-lint-1.11.0-rc01.jar",
          "url": "ui-test-manifest-lint-1.11.0-rc01.jar",
          "size": 12617,
          "sha512": "c0de290c1d0dcf822cef7dc69893f755580611f81997db008d816e1cc4e9f8dd4e2c5b1235985712a2a8eabb24ea35df4ab019866988e7e700c92e2e8c002459",
          "sha256": "3780cd48e804cc31fa2dce0e6211193d744e2f86824fbdc99c021e81a5f1ff0a",
          "sha1": "4e707a4d131404cc8c2e39564ef8f6010d05cd05",
          "md5": "cf0d26cf373cecb02171503decefc1ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.11.0-rc01"
          },
          "reason": "ui-test-manifest-lint is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-lint-1.11.0-rc01-sources.jar",
          "url": "ui-test-manifest-lint-1.11.0-rc01-sources.jar",
          "size": 8491,
          "sha512": "3762cf8b028d63719fc8bbb5f041551e42f3e0f01db7b75c62effbe39a6359030e177bb05d075f59cddbeb23ec5cd9bc0475e9da6c1fd5480885c6bbf4af2235",
          "sha256": "d4583ba06330175e846cf2b3705ab797229c962e8225918fac64733c7044dd9f",
          "sha1": "b0a8f6097f401f699295129c902488d14472becd",
          "md5": "210321dd1f4cbe54c3f1a6a8457db070"
        }
      ]
    }
  ]
}