{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-markdown-extension-autolink-242",
    "version": "0.24.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jewel-markdown-extension-autolink-242-0.24.2.jar",
          "url": "jewel-markdown-extension-autolink-242-0.24.2.jar",
          "size": 2873,
          "sha512": "72e0bfdb35e9dc0ff961e6ffbbdedf9408b0137eeec6f367bcf0b09c4dd8d8569806eb93ec166678459490da5fce8e4b3c1540d33430b375a4f5dca4cfaa9c39",
          "sha256": "e0161f90260231881f12c3a408aa9238cd001058b69ed8ba1a63e9b72ae58426",
          "sha1": "5eacf4ad73f8965262e89c5d76b864091c660fed",
          "md5": "83dcc3bb5139192073ea8dcd0732c874"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-markdown-core-242",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark-ext-autolink",
          "version": {
            "requires": "0.22.0"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-extension-autolink-242-0.24.2.jar",
          "url": "jewel-markdown-extension-autolink-242-0.24.2.jar",
          "size": 2873,
          "sha512": "72e0bfdb35e9dc0ff961e6ffbbdedf9408b0137eeec6f367bcf0b09c4dd8d8569806eb93ec166678459490da5fce8e4b3c1540d33430b375a4f5dca4cfaa9c39",
          "sha256": "e0161f90260231881f12c3a408aa9238cd001058b69ed8ba1a63e9b72ae58426",
          "sha1": "5eacf4ad73f8965262e89c5d76b864091c660fed",
          "md5": "83dcc3bb5139192073ea8dcd0732c874"
        }
      ]
    }
  ]
}
