{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-test-junit4/1.5.10/ui-test-junit4-1.5.10.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-test-junit4",
    "version": "1.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-desktop-1.5.10.jar",
          "url": "ui-test-junit4-desktop-1.5.10.jar",
          "size": 105556,
          "sha512": "9011e41794c43a02ce8810cb442e28a05a8a27321f8c273527920bf0ed51a13384bb16d9f99612d8f6a70d08f42f66ee4b0b944e995e63b04830ff62896b2901",
          "sha256": "ba84b4f17daa341d73bc6efd9c47cc4ceea780a99e3e3440eca974962848512d",
          "sha1": "1601ba64de81e5f84ff244b7ca864592c34a33ec",
          "md5": "65de3314e0e83b78d7c2b996e8a33282"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko-awt",
          "version": {
            "requires": "0.7.85"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-desktop-1.5.10.jar",
          "url": "ui-test-junit4-desktop-1.5.10.jar",
          "size": 105556,
          "sha512": "9011e41794c43a02ce8810cb442e28a05a8a27321f8c273527920bf0ed51a13384bb16d9f99612d8f6a70d08f42f66ee4b0b944e995e63b04830ff62896b2901",
          "sha256": "ba84b4f17daa341d73bc6efd9c47cc4ceea780a99e3e3440eca974962848512d",
          "sha1": "1601ba64de81e5f84ff244b7ca864592c34a33ec",
          "md5": "65de3314e0e83b78d7c2b996e8a33282"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-test-junit4-desktop-1.5.10-sources.jar",
          "url": "ui-test-junit4-desktop-1.5.10-sources.jar",
          "size": 31114,
          "sha512": "19e3036704adb1a6651f99f67e58b7cbccc99557cbbd1aa0778c86629dd51074253ad319baa9d606ae32e592f35c0b2e4abad0bf09b4fed19a12e6e5134f3993",
          "sha256": "2c9623a526fbd578ebd2927eb424333dec8beb450f62d9eceae8493474e01367",
          "sha1": "f9e68c502d1f9cf3fc3bccd02d04add2801fb187",
          "md5": "71f707c931f38b9666d64298b3615833"
        }
      ]
    }
  ]
}