{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt",
    "module": "coil-compose-base",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-base-2.4.0.aar",
          "url": "coil-compose-base-2.4.0.aar",
          "size": 101556,
          "sha512": "5d44c88cbe03ae3f8854ffba4436dc8db1fccefb65cd3ef6ac8847d95c85d6887f15c8ae7e06bfaad2bbd4b8d451d4e31640d9668a881f3af61e0c15bf288373",
          "sha256": "f6119e03ead78d804bad42182e1d0fdf8f9d2c647daf0aba33e89c64fcca2ce2",
          "sha1": "2418952aba4cb915c465d13a902275fd46d95d54",
          "md5": "efbb5dc80176c3689395638c50a8bbc2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-drawablepainter",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-base-2.4.0.aar",
          "url": "coil-compose-base-2.4.0.aar",
          "size": 101556,
          "sha512": "5d44c88cbe03ae3f8854ffba4436dc8db1fccefb65cd3ef6ac8847d95c85d6887f15c8ae7e06bfaad2bbd4b8d451d4e31640d9668a881f3af61e0c15bf288373",
          "sha256": "f6119e03ead78d804bad42182e1d0fdf8f9d2c647daf0aba33e89c64fcca2ce2",
          "sha1": "2418952aba4cb915c465d13a902275fd46d95d54",
          "md5": "efbb5dc80176c3689395638c50a8bbc2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-compose-base-2.4.0-sources.jar",
          "url": "coil-compose-base-2.4.0-sources.jar",
          "size": 14519,
          "sha512": "20df95fd9a26a8904da5d1d4bea96e881d8785b9ec42f2a355f0e3b9d4aa2f160c9fab18920deb193b0cc2da6a0ab8f4f9954cee69ee95b7321282a6a015149f",
          "sha256": "779ca7a2a764986709da6020f7c64c86a181f424cdc5ab77112480016fb9583c",
          "sha1": "e4d05f796877709d9a26cd7f4ec53f96ec4cc868",
          "md5": "95cd16b0aa5bad177eed37907bfea59a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-compose-base-2.4.0-javadoc.jar",
          "url": "coil-compose-base-2.4.0-javadoc.jar",
          "size": 310700,
          "sha512": "7f3cdf2d71ebecdbb6550ea337e71f488e068014ce74e2616de568ac68c1added35d4691c42a5ac09f69479fa7bb9a2c459db5332f12d9ad8beca27931a51af8",
          "sha256": "50f73a51eae735990805aa10441e650b57befb58d50377de30338dc39d0c489f",
          "sha1": "1f984abcfe62f51ec7ad927f26c06af3be51eab5",
          "md5": "ba3d21b072344b2e29531215fdbda98e"
        }
      ]
    }
  ]
}
