{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-core-okio",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "datastore-core-okio-1.1.0-alpha04-multiplatform-sources.jar",
          "url": "datastore-core-okio-1.1.0-alpha04-multiplatform-sources.jar",
          "size": 7976,
          "sha512": "8f451b67d6761a79d3e2d908d43d2c9803f375e028ebb9d438b7ae6d1f678f3ddee02048ac2a6bbd58a7bf83422f9b598fac31d48869723559887293f5b634b3",
          "sha256": "c3c628b26899844178de6af9c945a2f13d18c8d995dcfdccdbe484225e91cb7a",
          "sha1": "ecd4a5fe9be398a64b028c3614fd74314863a48e",
          "md5": "afaf0759560154bf7629bf05c6165e97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datastore-core-okio-1.1.0-alpha04-sources.jar",
          "url": "datastore-core-okio-1.1.0-alpha04-sources.jar",
          "size": 5230,
          "sha512": "2d249cbf113c523d92f4c03862bb30de04d22f46226e84be48fe2bd6d068cbf89e881bd7cad3995285207d08bc1f0305d524f0995177285d8be9af86ccb49bde",
          "sha256": "ac97ce5c0b5c30f23bd59b3aa699a59b084831916c12e978423403f6c59d74f4",
          "sha1": "0ca7f1feb400a84ac38fd048e3bf1a2675694a01",
          "md5": "6ee399a6b3a920719913355f594d6f21"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-metadata-1.1.0-alpha04.jar",
          "url": "datastore-core-okio-1.1.0-alpha04.jar",
          "size": 9469,
          "sha512": "90aa8ea6c133280298f40ed261ff9bd59f9231d911f816cd6bfaa2ec21016a6b5abda94df48f00e62d2bfa52b35748643e280b9166e44a30ade7dfbe2628fe53",
          "sha256": "1e97d2443acee6cde43180cf711353aea55cc2f21366e6846d6e0954d1fc44be",
          "sha1": "4679f40fdd763aa4c5a60d226966b2d370c484dc",
          "md5": "b0ba13ef0fb7ccbd62811bf3f8093c47"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-iosarm64/1.1.0-alpha04/datastore-core-okio-iosarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-iosarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-iosarm64/1.1.0-alpha04/datastore-core-okio-iosarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-iosarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-iossimulatorarm64/1.1.0-alpha04/datastore-core-okio-iossimulatorarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-iossimulatorarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-iossimulatorarm64/1.1.0-alpha04/datastore-core-okio-iossimulatorarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-iossimulatorarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-iosx64/1.1.0-alpha04/datastore-core-okio-iosx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-iosx64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-iosx64/1.1.0-alpha04/datastore-core-okio-iosx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-iosx64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-core-okio-jvm/1.1.0-alpha04/datastore-core-okio-jvm-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-jvm",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-core-okio-jvm/1.1.0-alpha04/datastore-core-okio-jvm-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-jvm",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-linuxx64/1.1.0-alpha04/datastore-core-okio-linuxx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-linuxx64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-macosarm64/1.1.0-alpha04/datastore-core-okio-macosarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-macosarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-macosarm64/1.1.0-alpha04/datastore-core-okio-macosarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-macosarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-macosx64/1.1.0-alpha04/datastore-core-okio-macosx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-macosx64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-core-okio-macosx64/1.1.0-alpha04/datastore-core-okio-macosx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-core-okio-macosx64",
        "version": "1.1.0-alpha04"
      }
    }
  ]
}