{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-text/1.5.2/ui-text-1.5.2.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-text",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.77"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-desktop-1.5.2.jar",
          "url": "ui-text-desktop-1.5.2.jar",
          "size": 681570,
          "sha512": "9dde5b78374433cc251179b5500b273c0ceaa2e7a44f597004934d0be4fa09142c851e48f4ee77f2613412d4946be01b1afe5f136564620aa38da0a58d893092",
          "sha256": "a0a620fccee62caafa53f9ce33054001de8df6be0146466892e862b0c0d6c9c1",
          "sha1": "44519ce6b5b12b70308746ed4351664fdf428322",
          "md5": "73ec8b38e7e7e872486c12759c950d9b"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.77"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-desktop-1.5.2.jar",
          "url": "ui-text-desktop-1.5.2.jar",
          "size": 681570,
          "sha512": "9dde5b78374433cc251179b5500b273c0ceaa2e7a44f597004934d0be4fa09142c851e48f4ee77f2613412d4946be01b1afe5f136564620aa38da0a58d893092",
          "sha256": "a0a620fccee62caafa53f9ce33054001de8df6be0146466892e862b0c0d6c9c1",
          "sha1": "44519ce6b5b12b70308746ed4351664fdf428322",
          "md5": "73ec8b38e7e7e872486c12759c950d9b"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-text-desktop-1.5.2-sources.jar",
          "url": "ui-text-desktop-1.5.2-sources.jar",
          "size": 214569,
          "sha512": "20f38413e214874fae7afe6b003704c0d3ca2db45110a68b92a56740e0b50788e0d848c289e3a5c7a30a5420d2ad59c1a4adb97733529fbe5dad69852e0d9bf2",
          "sha256": "11711a6a4d41e578300796219588b596d5758c428ddd24b40457ec4abc189996",
          "sha1": "e987a6803189b33732ba1fd1c928a240cdf2f8a7",
          "md5": "b1aa3aafabbc8250c85e0bd5e5ac863e"
        }
      ]
    }
  ]
}