{
  "formatVersion": "1.1",
  "component": {
    "group": "com.anthropic",
    "module": "anthropic-java",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.anthropic",
          "module": "anthropic-java-client-okhttp",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "anthropic-java-2.2.0.jar",
          "url": "anthropic-java-2.2.0.jar",
          "size": 345,
          "sha512": "d1bc63eab4a3699f4d22795779193f04cfcb162e2c047021b1de82947691bb2732dde184374c4401f26cd6341de36a8165a02ed17851fba7c8da6e4244d294f2",
          "sha256": "ab00d4c02cb4c4371dbba3321a0e7087068ab6ab16575c1c67711191ea4a4424",
          "sha1": "567dc6f81d66dcd5b408df274af4303b4afe46d2",
          "md5": "363475bb42c24ba15042e493a99b17d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.anthropic",
          "module": "anthropic-java-client-okhttp",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "anthropic-java-2.2.0.jar",
          "url": "anthropic-java-2.2.0.jar",
          "size": 345,
          "sha512": "d1bc63eab4a3699f4d22795779193f04cfcb162e2c047021b1de82947691bb2732dde184374c4401f26cd6341de36a8165a02ed17851fba7c8da6e4244d294f2",
          "sha256": "ab00d4c02cb4c4371dbba3321a0e7087068ab6ab16575c1c67711191ea4a4424",
          "sha1": "567dc6f81d66dcd5b408df274af4303b4afe46d2",
          "md5": "363475bb42c24ba15042e493a99b17d0"
        }
      ]
    }
  ]
}
