# Part of the standalone-jps-builder artifact from IDEA
java_import(
    name = "formc-deps",
    jars = [
        "asm-all-7.0.1.jar",
        "forms-1.1-preview.jar",
        "jdom-2.0.6.jar",
        "jps-builders.jar",
    ],
    visibility = ["//tools/base/bazel:__pkg__"],
)
