{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-ide-laf-bridge",
    "version": "0.9.0-ij-232",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui",
          "version": {
            "requires": "0.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ide-laf-bridge-platform-specific",
          "version": {
            "requires": "0.9.0-ij-232"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-ide-laf-bridge-0.9.0-ij-232.jar",
          "url": "jewel-ide-laf-bridge-0.9.0-ij-232.jar",
          "size": 108582,
          "sha512": "606741a8563d903f467e82de33fec787fea438d4cc12fb631ff39358b91c2f3aa6a6e8f09380ed4e9d276ae2dcf8edf2e3df6837cfe95a4b53d0b6cdae9563df",
          "sha256": "1c94b906057a0410e0ace58b66239388689f60fec5f75409f09c34d726560921",
          "sha1": "538313ffa7d32915c56fb3e575aa21634dc3545c",
          "md5": "eeb43c282dd8a997eeec2fba7def1d59"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui",
          "version": {
            "requires": "0.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ide-laf-bridge-platform-specific",
          "version": {
            "requires": "0.9.0-ij-232"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-ide-laf-bridge-0.9.0-ij-232.jar",
          "url": "jewel-ide-laf-bridge-0.9.0-ij-232.jar",
          "size": 108582,
          "sha512": "606741a8563d903f467e82de33fec787fea438d4cc12fb631ff39358b91c2f3aa6a6e8f09380ed4e9d276ae2dcf8edf2e3df6837cfe95a4b53d0b6cdae9563df",
          "sha256": "1c94b906057a0410e0ace58b66239388689f60fec5f75409f09c34d726560921",
          "sha1": "538313ffa7d32915c56fb3e575aa21634dc3545c",
          "md5": "eeb43c282dd8a997eeec2fba7def1d59"
        }
      ]
    }
  ]
}
