{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.groovy",
    "module": "groovy-swing",
    "version": "4.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "groovydocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "groovydoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-swing-4.0.29-groovydoc.jar",
          "url": "groovy-swing-4.0.29-groovydoc.jar",
          "size": 461245,
          "sha512": "a6d73009429ce6cd8f9e90b9e646eb39a5747c934fcea07b720d8a7a305ad987d532efc8cb80010cc300ca52709d6c34aeeb5b960f27e78f4502ed665bf55c5c",
          "sha256": "f0e6e0dead08c8eb9b402ae49f4695ae54f78106ab5bbc9ef00f2ead949716b0",
          "sha1": "c69d2507c5012597456a5635f05e0297d41025ba",
          "md5": "afc1397aa413a9f9432f7f420c247225"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-swing-4.0.29-javadoc.jar",
          "url": "groovy-swing-4.0.29-javadoc.jar",
          "size": 261324,
          "sha512": "4f55c21f2652d1a128b6656f7775d0fe7691fc175b909feeccb3d92f76764c821e10c35517d5a195cdc733acd9b437b8027c3e6825181519d13dcb1f515a459d",
          "sha256": "57c3daf20b98c37285990b1cc63f95048c94d207504c4798aaf6f0a99a3bdf41",
          "sha1": "9b3159b21d01d31c4ee5e65a2b16979ad484388f",
          "md5": "6d2b1465ba4ad87a0699f181b7ea2aae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-swing-4.0.29-sources.jar",
          "url": "groovy-swing-4.0.29-sources.jar",
          "size": 141652,
          "sha512": "b53d9700fdfcbdb4bbcac926760a3c4ba16d9f12b87a0639eb2b8aaffc1c3472453fe48b803bbe6215488895771039039a7968b8affd6a297b1c48fffdec1707",
          "sha256": "68c3bedc4191cd519dfa8d81bce94f69391e9d660d3a1bc4f71bbd4e8b737f72",
          "sha1": "0990307b68d0bda8b446877a344575444609745f",
          "md5": "bcc3614f2c4a68cea179012da7f426e8"
        }
      ]
    },
    {
      "name": "groovyApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.29"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-swing-4.0.29.jar",
          "url": "groovy-swing-4.0.29.jar",
          "size": 341765,
          "sha512": "e789fda4a5d01fea9713e54c32c5b181de499d4248880067c2d18e1306cd42b94f28aef749677fe818b5a1992f93915fe97b009b4c9259d2cb3879a04840bbfc",
          "sha256": "2570e15ef0eee7582e6820e0862e9beb7b5d4172c44aa87c61453445249b9707",
          "sha1": "8de48e29b5bab28606924bb9943a787b0b54d6bf",
          "md5": "70692287cae97aa97ec75ed383e40bb2"
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-swing",
          "version": "4.0.29"
        },
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-swing",
          "version": "4.0.29"
        }
      ]
    },
    {
      "name": "groovyRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.29"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-swing-4.0.29.jar",
          "url": "groovy-swing-4.0.29.jar",
          "size": 341765,
          "sha512": "e789fda4a5d01fea9713e54c32c5b181de499d4248880067c2d18e1306cd42b94f28aef749677fe818b5a1992f93915fe97b009b4c9259d2cb3879a04840bbfc",
          "sha256": "2570e15ef0eee7582e6820e0862e9beb7b5d4172c44aa87c61453445249b9707",
          "sha1": "8de48e29b5bab28606924bb9943a787b0b54d6bf",
          "md5": "70692287cae97aa97ec75ed383e40bb2"
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-swing",
          "version": "4.0.29"
        },
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-swing",
          "version": "4.0.29"
        }
      ]
    }
  ]
}
