load("//tools/adt/idea/studio:studio.bzl", "studio_data")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "bin",
    srcs = [
        "sokatoa-apk/sokatoa.apk",
        "//tools/profiler/native/android/sherlocklayersapp:sherlock-layers.apk",
    ],
)

studio_data(
    name = "lib",
    files_linux = ["trace-processor-wrapper/linux-x64/main"],
    files_mac = ["trace-processor-wrapper/darwin-arm64/main"],
    files_mac_arm = ["trace-processor-wrapper/darwin-arm64/main"],
    files_win = ["trace-processor-wrapper/windows-x64/main.exe"],
    mappings = {
        "prebuilts/tools/sherlock/trace-processor-wrapper/linux-x64": "",
        "prebuilts/tools/sherlock/trace-processor-wrapper/darwin-arm64": "",
        "prebuilts/tools/sherlock/trace-processor-wrapper/windows-x64": "",
    },
)

# --- GFXReconstruct File Groups ---
filegroup(
    name = "gfxreconstruct",
    srcs = [
        "gfxreconstruct/replay-debug.apk",
    ],
)

studio_data(
    name = "gfxreconstruct_tools",
    files_linux = glob(["gfxreconstruct/linux-x64/tools/**"]),
    files_mac = glob(["gfxreconstruct/darwin-arm64/tools/**"]),
    files_mac_arm = glob(["gfxreconstruct/darwin-arm64/tools/**"]),
    mappings = {
        "prebuilts/tools/sherlock/gfxreconstruct/linux-x64/tools": "",
        "prebuilts/tools/sherlock/gfxreconstruct/darwin-arm64/tools": "",
    },
)

# --- OS-specific SPIRV tools ---
studio_data(
    name = "spirv_tools",
    files_linux = glob(["SPIRV-Tools/linux-x64/**/*"]),
    files_mac = glob(["SPIRV-Tools/darwin-arm64/**/*"]),
    files_mac_arm = glob(["SPIRV-Tools/darwin-arm64/**/*"]),
    mappings = {
        "prebuilts/tools/sherlock/SPIRV-Tools/linux-x64": "",
        "prebuilts/tools/sherlock/SPIRV-Tools/darwin-arm64": "",
    },
)

studio_data(
    name = "spirv_cross",
    files_linux = ["SPIRV-Cross/linux-x64/spirv-cross"],
    files_mac = ["SPIRV-Cross/darwin-arm64/spirv-cross"],
    files_mac_arm = ["SPIRV-Cross/darwin-arm64/spirv-cross"],
    mappings = {
        "prebuilts/tools/sherlock/SPIRV-Cross/linux-x64": "",
        "prebuilts/tools/sherlock/SPIRV-Cross/darwin-arm64": "",
    },
)

filegroup(
    name = "all-prebuilts",
    srcs = glob([
        "*/**",
    ]),
)
