{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.4.0-rc01.aar",
          "url": "animation-1.4.0-rc01.aar",
          "size": 1331356,
          "sha512": "2650fe559c53bf0d134bf3098c889c90c9314e89295c8c23307c1e2ee59018d45395fee26dd4eec61c2c182585fae2f2fd36e7bc0adb6a7cf3381c1be38498ab",
          "sha256": "1bd0dc72cc00b691fa70ffcba2f53b1e60e4f2123b7fe5d4c1158de5d16ffc72",
          "sha1": "d306a3b7ce1650149e6f32ddba60767282e0b58a",
          "md5": "7dc4f210193d90409de2db1bc0d14355"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.4.0-rc01.aar",
          "url": "animation-1.4.0-rc01.aar",
          "size": 1331356,
          "sha512": "2650fe559c53bf0d134bf3098c889c90c9314e89295c8c23307c1e2ee59018d45395fee26dd4eec61c2c182585fae2f2fd36e7bc0adb6a7cf3381c1be38498ab",
          "sha256": "1bd0dc72cc00b691fa70ffcba2f53b1e60e4f2123b7fe5d4c1158de5d16ffc72",
          "sha1": "d306a3b7ce1650149e6f32ddba60767282e0b58a",
          "md5": "7dc4f210193d90409de2db1bc0d14355"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.4.0-rc01-sources.jar",
          "url": "animation-1.4.0-rc01-sources.jar",
          "size": 42087,
          "sha512": "e954584d129dbafe17c255afd91a8c9268336ea3911ff7c9cbef5494465a247041a104dba91b9b36dc55467eebefc160eb8b96c81c44956370cfea58ce5e90b1",
          "sha256": "aa835c43bea46aedc480cb28bacefa6375af74808ee333c6f96e8ab051299f3f",
          "sha1": "b0b8f9ceb8931e481a1c27ab99fe33ba2322d428",
          "md5": "faee4a50cb309c2d7777c672e7b3fc40"
        }
      ]
    }
  ]
}