{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.2.aar",
          "url": "navigation-runtime-ktx-2.5.2.aar",
          "size": 1769,
          "sha512": "a62d0dc5fd200712e6255b5f5788218a892dbde0d958cf8f73886050a6df354126593e3019889e62e1c8f8957ba0aadcc618df7e3dd767b1a8a77eb31ebed6b5",
          "sha256": "af6e0a152cc5dc80b12d69e4bb0ee8aa6dfd3aae50e98a974fa50a8c6b2ba9a2",
          "sha1": "2c1bec1bfd02ba15640c7f10271c64191731dc8d",
          "md5": "db5b85207c8badf2520c7e27daa526fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.2.aar",
          "url": "navigation-runtime-ktx-2.5.2.aar",
          "size": 1769,
          "sha512": "a62d0dc5fd200712e6255b5f5788218a892dbde0d958cf8f73886050a6df354126593e3019889e62e1c8f8957ba0aadcc618df7e3dd767b1a8a77eb31ebed6b5",
          "sha256": "af6e0a152cc5dc80b12d69e4bb0ee8aa6dfd3aae50e98a974fa50a8c6b2ba9a2",
          "sha1": "2c1bec1bfd02ba15640c7f10271c64191731dc8d",
          "md5": "db5b85207c8badf2520c7e27daa526fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.2-sources.jar",
          "url": "navigation-runtime-ktx-2.5.2-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}