{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.3.0.aar",
          "url": "ui-graphics-1.3.0.aar",
          "size": 1408443,
          "sha512": "514c8dab9694715989c132aa4a2d7cc1a583cf7e020cc9c00a1d420b1187434b68edfa4a5be337f105e971459195f14caca1595a5f390d56b269683020b26b80",
          "sha256": "530aaf499361e28acd365ea88c3c543417f6c6051a02a28a56a560e1922ba614",
          "sha1": "241ca562d6d806209f7573aec342b4b5990e8bed",
          "md5": "1b6ea84c768c81c3b07534d1e065563c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.3.0.aar",
          "url": "ui-graphics-1.3.0.aar",
          "size": 1408443,
          "sha512": "514c8dab9694715989c132aa4a2d7cc1a583cf7e020cc9c00a1d420b1187434b68edfa4a5be337f105e971459195f14caca1595a5f390d56b269683020b26b80",
          "sha256": "530aaf499361e28acd365ea88c3c543417f6c6051a02a28a56a560e1922ba614",
          "sha1": "241ca562d6d806209f7573aec342b4b5990e8bed",
          "md5": "1b6ea84c768c81c3b07534d1e065563c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-1.3.0-sources.jar",
          "url": "ui-graphics-1.3.0-sources.jar",
          "size": 160453,
          "sha512": "4382c83264be466f6930ab334910b21d97d6c161aa45d56c83d2cc4e4ef0e6ddd69ce558670e3f0ea3d71bb78dc949e304069530ab90f52eff7e2eb0fc905052",
          "sha256": "f7c003a8a24e8f2c0216446baed5c5279a831f968cb2978500f9cf16b2625ff7",
          "sha1": "01f0725b5ccc7b14a306c879122268e7c236dc2c",
          "md5": "aebb2b7ef4b39a3d9a01b91a947ee22a"
        }
      ]
    }
  ]
}