{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-core",
    "version": "1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.21.8"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha04.jar",
          "url": "tools-core-1.0.0-alpha04.jar",
          "size": 299589,
          "sha512": "7c2cc39715aab2d11f4eca5e5a936f107abb91739d3c903c07ed0b213275c7fefe5569574b3f72a8a8c4d1b8e1a0dd1378161056e978ebe0aed20560ca4cc80e",
          "sha256": "afb43306fff56bd223670470859be202b9011edfcd5311d6edc237a8677be707",
          "sha1": "141cbaf20ee84cb5eee2987198480dea5e20163e",
          "md5": "cf353613f609c0d36b7cf08734954008"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.21.8"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha04.jar",
          "url": "tools-core-1.0.0-alpha04.jar",
          "size": 299589,
          "sha512": "7c2cc39715aab2d11f4eca5e5a936f107abb91739d3c903c07ed0b213275c7fefe5569574b3f72a8a8c4d1b8e1a0dd1378161056e978ebe0aed20560ca4cc80e",
          "sha256": "afb43306fff56bd223670470859be202b9011edfcd5311d6edc237a8677be707",
          "sha1": "141cbaf20ee84cb5eee2987198480dea5e20163e",
          "md5": "cf353613f609c0d36b7cf08734954008"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha04-sources.jar",
          "url": "tools-core-1.0.0-alpha04-sources.jar",
          "size": 50289,
          "sha512": "4b72c0a8c0bbca059dc8a750b26c3ba6c9a3abdba42990fd43c630aba1a867f57c6351dab6aa87d055df816b56701ceac1d8312c1dfdf04a498909e2ae4fcdd6",
          "sha256": "e99aa1685b42be195780d4b35f2c9746508ffcd44fe99860f11530493b263060",
          "sha1": "b60b665db30affcefcb19bdd90bf21667604911f",
          "md5": "69e3afac0b8f1daf2268278fedb77830"
        }
      ]
    }
  ]
}