# managed by go/iml_to_build
java_import(
    name = "android-extensions-compiler-tests",
    jars = ["android-extensions-compiler-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "idea-tests",
    jars = ["idea-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "idea-gradle-tests",
    jars = ["idea-gradle-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "idea-test-framework-tests",
    jars = ["idea-test-framework-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "tests-common-tests",
    jars = ["tests-common-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.android-extensions-compiler-tests",
    jars = ["android-extensions-compiler-tests.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.idea-gradle-tests",
    jars = ["idea-gradle-tests.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.idea-test-framework-tests",
    jars = ["idea-test-framework-tests.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.idea-tests",
    jars = ["idea-tests.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
java_import(
    name = "unb.tests-common-tests",
    jars = ["tests-common-tests.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)
