# managed by go/iml_to_build
java_import(
    name = "android-extensions-compiler-1.2.60-tests",
    jars = ["android-extensions-compiler-1.2.60-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "idea-1.2.60-tests",
    jars = ["idea-1.2.60-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "idea-gradle-1.2.60-tests",
    jars = ["idea-gradle-1.2.60-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "idea-test-framework-1.2.60-tests",
    jars = ["idea-test-framework-1.2.60-tests.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "tests-common-1.2.60-tests",
    jars = ["tests-common-1.2.60-tests.jar"],
    visibility = ["//visibility:public"],
)
