{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.3.0.aar",
          "url": "material-icons-extended-1.3.0.aar",
          "size": 32356763,
          "sha512": "83ef48859a665da270bc794a79a20636a08309bfaf05f6d736db1b90d7b3f07048509f920deb2a781835738b1979d5ce94d232ab56b4cc0978d720f82391d6ae",
          "sha256": "2f1113070a219d92fe67a57eb236499d19cfe4d27232d05a5f7a983a11d930e2",
          "sha1": "63e5bc7314972a7d04a982edebec587e58bbf632",
          "md5": "fb75f68bcbfc784398fe98f8c061810a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.3.0.aar",
          "url": "material-icons-extended-1.3.0.aar",
          "size": 32356763,
          "sha512": "83ef48859a665da270bc794a79a20636a08309bfaf05f6d736db1b90d7b3f07048509f920deb2a781835738b1979d5ce94d232ab56b4cc0978d720f82391d6ae",
          "sha256": "2f1113070a219d92fe67a57eb236499d19cfe4d27232d05a5f7a983a11d930e2",
          "sha1": "63e5bc7314972a7d04a982edebec587e58bbf632",
          "md5": "fb75f68bcbfc784398fe98f8c061810a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-extended-1.3.0-sources.jar",
          "url": "material-icons-extended-1.3.0-sources.jar",
          "size": 11067229,
          "sha512": "96bf38e9e36d6e4711353256fbd476dd1cf31e788fc7682254ae975ec131f42e9126e2caed038bb4fb3262a6d02075303eaa9579d4d45e9c104f4d30204e6b19",
          "sha256": "01967bebfd54970d5d3eb678852400b652f90a30da8e439c668c7fdcf6b58991",
          "sha1": "f7f634aaf9e00d11c1f8ec3c7e3a364ee67d6f69",
          "md5": "c316a614924d452c10251659a10ad264"
        }
      ]
    }
  ]
}