{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.androidx.lifecycle",
    "module": "lifecycle-runtime-compose",
    "version": "2.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.8.4.jar",
          "url": "lifecycle-runtime-compose-2.8.4.jar",
          "size": 8245,
          "sha512": "1608a3b8d35c50a558fc44e7c94f1c4cd5965e583b001602f46ed43b2fc841dd723cdea2187db15d2acb38970db9320b27db62d1407cfb3ea442618311fd08d1",
          "sha256": "bca0a12c8dfcaf7f7340f6ae78478755ba0aacb5fd026cdaaaed044d1ea2d1d3",
          "sha1": "37bc2016a71a8729c5fd2c1f7947999e841d5fef",
          "md5": "2258fbfe0b15e035364817fbcc1a0d52"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lifecycle-runtime-compose-2.8.4-sources.jar",
          "url": "lifecycle-runtime-compose-2.8.4-sources.jar",
          "size": 10298,
          "sha512": "32dc7eca45c5321099feb865e4829c71e85fed03c197cc440d8df76be9859c73252cdfebf7b1cfe6f510967900f7e6784f0dd1700785b99a168a32f3824f2109",
          "sha256": "ffe4b5f1a7bdd9655a0ee64dfcc3474afd24e97d9dc02896e8db106616b50fe8",
          "sha1": "4c787c325568658022d901efb8a435325e484dbf",
          "md5": "64d1b78ae756c6d7e529722b26bc9167"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-desktop/2.8.4/lifecycle-runtime-compose-desktop-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-desktop",
        "version": "2.8.4"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-desktop/2.8.4/lifecycle-runtime-compose-desktop-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-desktop",
        "version": "2.8.4"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-desktop/2.8.4/lifecycle-runtime-compose-desktop-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-desktop",
        "version": "2.8.4"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-js/2.8.4/lifecycle-runtime-compose-js-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-js",
        "version": "2.8.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-js/2.8.4/lifecycle-runtime-compose-js-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-js",
        "version": "2.8.4"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-js/2.8.4/lifecycle-runtime-compose-js-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-js",
        "version": "2.8.4"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-linuxarm64/2.8.4/lifecycle-runtime-compose-linuxarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-linuxarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-linuxarm64/2.8.4/lifecycle-runtime-compose-linuxarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-linuxarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-linuxx64/2.8.4/lifecycle-runtime-compose-linuxx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-linuxx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-linuxx64/2.8.4/lifecycle-runtime-compose-linuxx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-linuxx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-macosarm64/2.8.4/lifecycle-runtime-compose-macosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-macosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-macosarm64/2.8.4/lifecycle-runtime-compose-macosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-macosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-macosarm64/2.8.4/lifecycle-runtime-compose-macosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-macosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-macosx64/2.8.4/lifecycle-runtime-compose-macosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-macosx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-macosx64/2.8.4/lifecycle-runtime-compose-macosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-macosx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-macosx64/2.8.4/lifecycle-runtime-compose-macosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-macosx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-mingwx64/2.8.4/lifecycle-runtime-compose-mingwx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-mingwx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-mingwx64/2.8.4/lifecycle-runtime-compose-mingwx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-mingwx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvosarm64/2.8.4/lifecycle-runtime-compose-tvosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvosarm64/2.8.4/lifecycle-runtime-compose-tvosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvosarm64/2.8.4/lifecycle-runtime-compose-tvosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvossimulatorarm64/2.8.4/lifecycle-runtime-compose-tvossimulatorarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvossimulatorarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvossimulatorarm64/2.8.4/lifecycle-runtime-compose-tvossimulatorarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvossimulatorarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvossimulatorarm64/2.8.4/lifecycle-runtime-compose-tvossimulatorarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvossimulatorarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvosx64/2.8.4/lifecycle-runtime-compose-tvosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvosx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvosx64/2.8.4/lifecycle-runtime-compose-tvosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvosx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-tvosx64/2.8.4/lifecycle-runtime-compose-tvosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-tvosx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitarm64/2.8.4/lifecycle-runtime-compose-uikitarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitarm64/2.8.4/lifecycle-runtime-compose-uikitarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitarm64/2.8.4/lifecycle-runtime-compose-uikitarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitsimarm64/2.8.4/lifecycle-runtime-compose-uikitsimarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitsimarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitSimArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitsimarm64/2.8.4/lifecycle-runtime-compose-uikitsimarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitsimarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitsimarm64/2.8.4/lifecycle-runtime-compose-uikitsimarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitsimarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitx64/2.8.4/lifecycle-runtime-compose-uikitx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitx64/2.8.4/lifecycle-runtime-compose-uikitx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-uikitx64/2.8.4/lifecycle-runtime-compose-uikitx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-uikitx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-wasm-js/2.8.4/lifecycle-runtime-compose-wasm-js-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-wasm-js",
        "version": "2.8.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-wasm-js/2.8.4/lifecycle-runtime-compose-wasm-js-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-wasm-js",
        "version": "2.8.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-wasm-js/2.8.4/lifecycle-runtime-compose-wasm-js-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-wasm-js",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosarm32/2.8.4/lifecycle-runtime-compose-watchosarm32-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosarm32",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosarm32/2.8.4/lifecycle-runtime-compose-watchosarm32-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosarm32",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosarm32/2.8.4/lifecycle-runtime-compose-watchosarm32-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosarm32",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosarm64/2.8.4/lifecycle-runtime-compose-watchosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosarm64/2.8.4/lifecycle-runtime-compose-watchosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosarm64/2.8.4/lifecycle-runtime-compose-watchosarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchossimulatorarm64/2.8.4/lifecycle-runtime-compose-watchossimulatorarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchossimulatorarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchossimulatorarm64/2.8.4/lifecycle-runtime-compose-watchossimulatorarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchossimulatorarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchossimulatorarm64/2.8.4/lifecycle-runtime-compose-watchossimulatorarm64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchossimulatorarm64",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosx64/2.8.4/lifecycle-runtime-compose-watchosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosx64/2.8.4/lifecycle-runtime-compose-watchosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosx64",
        "version": "2.8.4"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-runtime-compose-watchosx64/2.8.4/lifecycle-runtime-compose-watchosx64-2.8.4.module",
        "group": "org.jetbrains.androidx.lifecycle",
        "module": "lifecycle-runtime-compose-watchosx64",
        "version": "2.8.4"
      }
    }
  ]
}