{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-markdown-ide-laf-bridge-styling-241",
    "version": "0.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-markdown-core-241",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ide-laf-bridge-241",
          "version": {
            "requires": "0.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-ide-laf-bridge-styling-241-0.18.1.jar",
          "url": "jewel-markdown-ide-laf-bridge-styling-241-0.18.1.jar",
          "size": 28387,
          "sha512": "c066bfaab58591d0ff31251bfbed1e77c25e792295a09c0c491e44384fc32d04591972a3f123e9b73a8c93e8b56c5820c82e2c8f70fb0340a9587cd146addb3e",
          "sha256": "40b1d1bcd7bbd44e0ba08d461a430e94b450690f411fdf8768e75fc307df5a42",
          "sha1": "488878faa769e7255e2413bd6b3ee0acd8e2d60d",
          "md5": "91b9a2741948fe708f2a5ca7c7ab2612"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-markdown-core-241",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ide-laf-bridge-241",
          "version": {
            "requires": "0.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-ide-laf-bridge-styling-241-0.18.1.jar",
          "url": "jewel-markdown-ide-laf-bridge-styling-241-0.18.1.jar",
          "size": 28387,
          "sha512": "c066bfaab58591d0ff31251bfbed1e77c25e792295a09c0c491e44384fc32d04591972a3f123e9b73a8c93e8b56c5820c82e2c8f70fb0340a9587cd146addb3e",
          "sha256": "40b1d1bcd7bbd44e0ba08d461a430e94b450690f411fdf8768e75fc307df5a42",
          "sha1": "488878faa769e7255e2413bd6b3ee0acd8e2d60d",
          "md5": "91b9a2741948fe708f2a5ca7c7ab2612"
        }
      ]
    }
  ]
}
