{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-text/1.1.1/ui-text-1.1.1.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-text",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.16"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-desktop-1.1.1.jar",
          "url": "ui-text-desktop-1.1.1.jar",
          "size": 418273,
          "sha512": "4ee765c6dd9ddd84afc61a341ba686a52c7ee445262714f18846dfbaa75c7252fe95f02c8b7624fadb7ae0f574889e03846f06eacd70e0198e9ee467984db513",
          "sha256": "c264f0d3d0d68d424c98e03959d02d6b4bc63dd1923b42299b357343edba85ab",
          "sha1": "c28b6d30561069ca05c638e9a4c2229e3677b303",
          "md5": "3b7ccb7c7ca9611f9e092ed2848cf223"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-desktop-1.1.1.jar",
          "url": "ui-text-desktop-1.1.1.jar",
          "size": 418273,
          "sha512": "4ee765c6dd9ddd84afc61a341ba686a52c7ee445262714f18846dfbaa75c7252fe95f02c8b7624fadb7ae0f574889e03846f06eacd70e0198e9ee467984db513",
          "sha256": "c264f0d3d0d68d424c98e03959d02d6b4bc63dd1923b42299b357343edba85ab",
          "sha1": "c28b6d30561069ca05c638e9a4c2229e3677b303",
          "md5": "3b7ccb7c7ca9611f9e092ed2848cf223"
        }
      ]
    }
  ]
}
