{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.10.4/animation-core-1.10.4.module",
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.10.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14886741"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core.aar",
          "url": "animation-core-android-1.10.4.aar",
          "size": 1369853,
          "sha512": "8adccfa137bd42e2a7a734eff70fd6edd30aa468a672094f61413ec05ba24bdd903547827c62ddd70f4ee8e65f34634c20a09aeae471c050c57110d1ddb15b18",
          "sha256": "05ee8844cca8c8e77fe6a3809472326270a1247b48a4ced590635c928cf80a83",
          "sha1": "1dcb9cc3abdc675f328527e1528f5e914b24221e",
          "md5": "20712246b8bad5dab81075f625b527ff"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core.aar",
          "url": "animation-core-android-1.10.4.aar",
          "size": 1369853,
          "sha512": "8adccfa137bd42e2a7a734eff70fd6edd30aa468a672094f61413ec05ba24bdd903547827c62ddd70f4ee8e65f34634c20a09aeae471c050c57110d1ddb15b18",
          "sha256": "05ee8844cca8c8e77fe6a3809472326270a1247b48a4ced590635c928cf80a83",
          "sha1": "1dcb9cc3abdc675f328527e1528f5e914b24221e",
          "md5": "20712246b8bad5dab81075f625b527ff"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.10.4"
          },
          "reason": "animation-core is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-android-1.10.4-sources.jar",
          "url": "animation-core-android-1.10.4-sources.jar",
          "size": 115164,
          "sha512": "fd5079bcddbf9c9a6849b89d94e85427b98e249b17ba34695ec3bccb4e71faeb33e22607736c2f2c9258766f80fd5ba8bfe7b6e4a9147c2541edff25a4b385f7",
          "sha256": "12c1db9f74f744f4c33d04ab7272226dc1e67a1e5cfafbe808036718ac954fe1",
          "sha1": "6907095ab7a9280d24cbf098d05ec8cec09fa993",
          "md5": "fccd5b3b715241bd367ad09edd735de4"
        },
        {
          "name": "animation-core-1.10.4-samples-sources.jar",
          "url": "animation-core-android-1.10.4-samples-sources.jar",
          "size": 25951,
          "sha512": "c47d7caa2fa6ea92a57a886adecc37494bae8712706a45067ac3c1eed8dc599c9cfc258959cb4e73c3c00309f49a6867347f7f39f9a71fde8028324df6353ddf",
          "sha256": "cbd4b9814d7e2af91b3a22f554e75281beaf23c3f47016f98a79b1ac0f3cb6b2",
          "sha1": "ae139cc0ab318b5bb8cf986e43f25356bfc126c8",
          "md5": "a46005f614a432aa11f427df6ba5e618"
        }
      ]
    }
  ]
}