{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ui",
    "module": "ui-geometry",
    "version": "0.1.0-dev13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6519275"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-0.1.0-dev13.aar",
          "url": "ui-geometry-0.1.0-dev13.aar",
          "size": 34138,
          "sha512": "7f594f667293b3baad716ed22a4f6434f2a2f701dbf2dd79ba85c1d1d44427814aba8d8cf215862a9e220439ca1802750949cdbfc41e08ef5b2a4397e2dca8fa",
          "sha256": "c69080802b01ccfac129bc7ee10f7bb0111df33998eecb4dcfec81724d8dcd72",
          "sha1": "c81f8b7df59f08b6aa99b8b2f179b882fadf33e1",
          "md5": "8cb2c9421478c0bf4319a342c1f9f380"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-util",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-runtime",
          "version": {
            "requires": "0.1.0-dev13"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-0.1.0-dev13.aar",
          "url": "ui-geometry-0.1.0-dev13.aar",
          "size": 34138,
          "sha512": "7f594f667293b3baad716ed22a4f6434f2a2f701dbf2dd79ba85c1d1d44427814aba8d8cf215862a9e220439ca1802750949cdbfc41e08ef5b2a4397e2dca8fa",
          "sha256": "c69080802b01ccfac129bc7ee10f7bb0111df33998eecb4dcfec81724d8dcd72",
          "sha1": "c81f8b7df59f08b6aa99b8b2f179b882fadf33e1",
          "md5": "8cb2c9421478c0bf4319a342c1f9f380"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-geometry-0.1.0-dev13-sources.jar",
          "url": "ui-geometry-0.1.0-dev13-sources.jar",
          "size": 56418,
          "sha512": "62a43fe2c47cbf7fd981928dc22223e02fa5e7802fc8e88f5b5926cd71ec6162e9f1c92092b537478088cffcade0d26524c3ca0deb934c47ec57fd893d26e3d0",
          "sha256": "15c2092f1b2330e6bd68f2433e052a103e320114a176722caa449b357649f665",
          "sha1": "1a6aafc106bf19be9ee766b8322275eaa46c21e0",
          "md5": "abd8240addc8b6ad3c32da9750d7dce2"
        }
      ]
    }
  ]
}
