{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest",
    "version": "1.8.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.8.0-alpha06-sources.jar",
          "url": "ui-test-manifest-1.8.0-alpha06-sources.jar",
          "size": 4564,
          "sha512": "1b75ee69e0a5fff86d80d1cce7f47510ecd05cf5a92536dc0a21d426aca1aec45403915208012575b8187070cd8763198e79b0f8ee9dde0f683f37589a618b22",
          "sha256": "384785272b2eb412c8b9137eb8c597408238dd78a5e605b23368152f7a19485e",
          "sha1": "8ba18871ed812f819e8b0f4df06ea11ab8d3cc39",
          "md5": "ac4f52a8f3c9f0148b6ddc0e9049599c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.8.0-alpha06.aar",
          "url": "ui-test-manifest-1.8.0-alpha06.aar",
          "size": 16708,
          "sha512": "50e75c7cd4d8949b014e2aacc3a1d025fde311a502b273d6f4589549dd99c2a062f8ff1e6504846c2b9fd423ef991d8755287203a63132a0417b008c276327d2",
          "sha256": "3c44a77f5527c97dfa79cf17eefa36d15c082d1d03cf76ce5e15e93d35d04b08",
          "sha1": "dbee4dedcd23f62ba0c5b5afe4cb5840171e469d",
          "md5": "cba49d082e3089757ed8ff83de43bede"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.8.0-alpha06.aar",
          "url": "ui-test-manifest-1.8.0-alpha06.aar",
          "size": 16708,
          "sha512": "50e75c7cd4d8949b014e2aacc3a1d025fde311a502b273d6f4589549dd99c2a062f8ff1e6504846c2b9fd423ef991d8755287203a63132a0417b008c276327d2",
          "sha256": "3c44a77f5527c97dfa79cf17eefa36d15c082d1d03cf76ce5e15e93d35d04b08",
          "sha1": "dbee4dedcd23f62ba0c5b5afe4cb5840171e469d",
          "md5": "cba49d082e3089757ed8ff83de43bede"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-test-manifest is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.8.0-alpha06-versionMetadata.json",
          "url": "ui-test-manifest-1.8.0-alpha06-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}