{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-test",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4irbk5x6kragle63hngfxoqfii"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-metadata-1.6.1-all.jar",
          "url": "kotlinx-coroutines-test-1.6.1-all.jar",
          "size": 13118,
          "sha512": "7970082c6cd63d3e91cbad408ca746ce8c8527ef63a09afa4672db22473adddd56abb0128b3160b211a401792cbf3daea3fd544b5d7dba108ddc3c333a14d3c9",
          "sha256": "ca04c7ce03f7894de34d70ac173c4b0ecd32220db824ed1821727d207edc6c02",
          "sha1": "f5ee50b48ad00c336273eeac9732b67262e044ff",
          "md5": "132a8f414cae9ced576cd0a1f812fea4"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-test-1.6.1.jar",
          "url": "kotlinx-coroutines-test-1.6.1.jar",
          "size": 11747,
          "sha512": "af330f1125e5df7ed954d9b8c86c3cdd962e546355969881f4829b316f334951e28a4da1bb9a1d2c260950aee7d5e08709a4e3ac2269290c9904106aeeb1bee9",
          "sha256": "a32d64d969143df45d59fbf221e097cc2e05a9da6b0d8a612c2556cfed89b8ca",
          "sha1": "9922ea530d30030eb148e67db5546bb239df667f",
          "md5": "b43a1c4568d5b0122d83a4a7ee8dc893"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm32/1.6.1/kotlinx-coroutines-test-iosarm32-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm32",
        "version": "1.6.1"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm32/1.6.1/kotlinx-coroutines-test-iosarm32-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm32",
        "version": "1.6.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm64/1.6.1/kotlinx-coroutines-test-iosarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosarm64/1.6.1/kotlinx-coroutines-test-iosarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iossimulatorarm64/1.6.1/kotlinx-coroutines-test-iossimulatorarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iossimulatorarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iossimulatorarm64/1.6.1/kotlinx-coroutines-test-iossimulatorarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iossimulatorarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosx64/1.6.1/kotlinx-coroutines-test-iosx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-iosx64/1.6.1/kotlinx-coroutines-test-iosx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-iosx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.6.1/kotlinx-coroutines-test-js-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.6.1"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.6.1/kotlinx-coroutines-test-js-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.6.1"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.6.1/kotlinx-coroutines-test-js-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.6.1"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-js/1.6.1/kotlinx-coroutines-test-js-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-js",
        "version": "1.6.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-jvm/1.6.1/kotlinx-coroutines-test-jvm-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-jvm",
        "version": "1.6.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-jvm/1.6.1/kotlinx-coroutines-test-jvm-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-jvm",
        "version": "1.6.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-linuxx64/1.6.1/kotlinx-coroutines-test-linuxx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-linuxx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosarm64/1.6.1/kotlinx-coroutines-test-macosarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosarm64/1.6.1/kotlinx-coroutines-test-macosarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosx64/1.6.1/kotlinx-coroutines-test-macosx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-macosx64/1.6.1/kotlinx-coroutines-test-macosx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-macosx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-mingwx64/1.6.1/kotlinx-coroutines-test-mingwx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-mingwx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosarm64/1.6.1/kotlinx-coroutines-test-tvosarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosarm64/1.6.1/kotlinx-coroutines-test-tvosarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvossimulatorarm64/1.6.1/kotlinx-coroutines-test-tvossimulatorarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvossimulatorarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvossimulatorarm64/1.6.1/kotlinx-coroutines-test-tvossimulatorarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvossimulatorarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosx64/1.6.1/kotlinx-coroutines-test-tvosx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-tvosx64/1.6.1/kotlinx-coroutines-test-tvosx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-tvosx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm32/1.6.1/kotlinx-coroutines-test-watchosarm32-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm32",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm32/1.6.1/kotlinx-coroutines-test-watchosarm32-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm32",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm64/1.6.1/kotlinx-coroutines-test-watchosarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosarm64/1.6.1/kotlinx-coroutines-test-watchosarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchossimulatorarm64/1.6.1/kotlinx-coroutines-test-watchossimulatorarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchossimulatorarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchossimulatorarm64/1.6.1/kotlinx-coroutines-test-watchossimulatorarm64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchossimulatorarm64",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx64/1.6.1/kotlinx-coroutines-test-watchosx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx64/1.6.1/kotlinx-coroutines-test-watchosx64-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx64",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx86/1.6.1/kotlinx-coroutines-test-watchosx86-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx86",
        "version": "1.6.1"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-test-watchosx86/1.6.1/kotlinx-coroutines-test-watchosx86-1.6.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-test-watchosx86",
        "version": "1.6.1"
      }
    }
  ]
}
