{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite/2.5.0-beta01/sqlite-2.5.0-beta01.module",
    "group": "androidx.sqlite",
    "module": "sqlite",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13020744"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite.aar",
          "url": "sqlite-android-2.5.0-beta01.aar",
          "size": 35941,
          "sha512": "e3f96bdd655d79ed843d48dfc9d32bb0157941c88bba842c67e36a4bb9936105f25f5165a6eb9b1f6de5d7d3c4ec1e70f2cbbd63e55ce8931ab40d43bd1c740f",
          "sha256": "12600a67ebf36fcbe46aa69d2576d347408b6107303252f78fad6ba70b0d6fa5",
          "sha1": "4be7284c8ee4dc5a204a89017098b1b0eb2ede37",
          "md5": "c9a1070a407df5642d9d70ab2f8998fe"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite.aar",
          "url": "sqlite-android-2.5.0-beta01.aar",
          "size": 35941,
          "sha512": "e3f96bdd655d79ed843d48dfc9d32bb0157941c88bba842c67e36a4bb9936105f25f5165a6eb9b1f6de5d7d3c4ec1e70f2cbbd63e55ce8931ab40d43bd1c740f",
          "sha256": "12600a67ebf36fcbe46aa69d2576d347408b6107303252f78fad6ba70b0d6fa5",
          "sha1": "4be7284c8ee4dc5a204a89017098b1b0eb2ede37",
          "md5": "c9a1070a407df5642d9d70ab2f8998fe"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          },
          "reason": "sqlite is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-android-2.5.0-beta01-sources.jar",
          "url": "sqlite-android-2.5.0-beta01-sources.jar",
          "size": 30375,
          "sha512": "6d2c220c387c298b9350e738956e57b984899332c9130d7a8d04b31f7115c82908e54adc2cf59c45dbce77ad097bd93fdf6014572f2d2300b7106a186766583f",
          "sha256": "14dd310ff0d3c6d701dd599f352997524f40bd574f96ee45ab49a0fe490cce38",
          "sha1": "aeec7b5e699943bcc3f6d04dd460473a056c0c0f",
          "md5": "db7be473bba1bf233734c2dc26e5a4f1"
        }
      ]
    }
  ]
}