{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-gradle-plugin",
    "version": "2.1.0-Beta1-1.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.1.0-Beta1-1.0.25.jar",
          "url": "symbol-processing-gradle-plugin-2.1.0-Beta1-1.0.25.jar",
          "size": 188537,
          "sha512": "69968564bc5b875fed623ff8644951f75606c76d9332b0613a90b1648d908cc34f5599477f2248b5d93192b7db485a2d057e85f7235d979d53c5602d5beaff1a",
          "sha256": "3a74333e6b406c907e5aad4dbebfabd07352881f4d00183faa55c24224a813d2",
          "sha1": "ced728c8f89f2d7ce1f64fb99d6f87041d068fe1",
          "md5": "062f087bdcbdde52824827415fb9b217"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-Beta1-1.0.25"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.1.0-Beta1-1.0.25"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.1.0-Beta1-1.0.25.jar",
          "url": "symbol-processing-gradle-plugin-2.1.0-Beta1-1.0.25.jar",
          "size": 188537,
          "sha512": "69968564bc5b875fed623ff8644951f75606c76d9332b0613a90b1648d908cc34f5599477f2248b5d93192b7db485a2d057e85f7235d979d53c5602d5beaff1a",
          "sha256": "3a74333e6b406c907e5aad4dbebfabd07352881f4d00183faa55c24224a813d2",
          "sha1": "ced728c8f89f2d7ce1f64fb99d6f87041d068fe1",
          "md5": "062f087bdcbdde52824827415fb9b217"
        }
      ]
    }
  ]
}
