{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-gradle-plugin",
    "version": "2.1.21-2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.1.21-2.0.2.jar",
          "url": "symbol-processing-gradle-plugin-2.1.21-2.0.2.jar",
          "size": 232238,
          "sha512": "4b40c645946ae975ce9756794972cab35e4876965cdad7b222b61589188fbec549219d9dd4670dad3122eae12e2c96d33ea34f0e68a2938c57117eaf9daa6ae6",
          "sha256": "61b64ddc6e5bd35647b58c10fa442b093fc0d82d1102b9e90730e733ff06e735",
          "sha1": "cbe5d1df438c7674e184a564ebc4b66f41682439",
          "md5": "3c856279bc41c58669e6cedd65cff97c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.1.21-2.0.2.jar",
          "url": "symbol-processing-gradle-plugin-2.1.21-2.0.2.jar",
          "size": 232238,
          "sha512": "4b40c645946ae975ce9756794972cab35e4876965cdad7b222b61589188fbec549219d9dd4670dad3122eae12e2c96d33ea34f0e68a2938c57117eaf9daa6ae6",
          "sha256": "61b64ddc6e5bd35647b58c10fa442b093fc0d82d1102b9e90730e733ff06e735",
          "sha1": "cbe5d1df438c7674e184a564ebc4b66f41682439",
          "md5": "3c856279bc41c58669e6cedd65cff97c"
        }
      ]
    }
  ]
}
