{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-api",
    "version": "1.8.10-1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.8.10-1.0.9.jar",
          "url": "symbol-processing-api-1.8.10-1.0.9.jar",
          "size": 117978,
          "sha512": "fd2eaf97b069ba53caae34eb7684cbe78905760fa3b25631fc0c54082ccdf7bd2e618482f2131fc1523f0bf1fb297149411a777565526af7dcb6fb5eed3c078b",
          "sha256": "10e2b0b483bb58b658a4d5b3d967308ed2c9c88ae1276f4c2202d38defac9907",
          "sha1": "cb23eb105730f05919bd182fe91d709650d328a6",
          "md5": "285bb69fb7a8db6388599731c99c1df7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.8.10-1.0.9.jar",
          "url": "symbol-processing-api-1.8.10-1.0.9.jar",
          "size": 117978,
          "sha512": "fd2eaf97b069ba53caae34eb7684cbe78905760fa3b25631fc0c54082ccdf7bd2e618482f2131fc1523f0bf1fb297149411a777565526af7dcb6fb5eed3c078b",
          "sha256": "10e2b0b483bb58b658a4d5b3d967308ed2c9c88ae1276f4c2202d38defac9907",
          "sha1": "cb23eb105730f05919bd182fe91d709650d328a6",
          "md5": "285bb69fb7a8db6388599731c99c1df7"
        }
      ]
    }
  ]
}
