{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.5.0-alpha06/collection-1.5.0-alpha06.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-alpha06.jar",
          "url": "collection-jvm-1.5.0-alpha06.jar",
          "size": 877303,
          "sha512": "f4fa071477bc56ad2ae9a09dc720e3a78f8a7145b5d9a2332313dd71d51cc2c7eb6dfb979d47edfd779cf44e17e5948a65093d43df4cd5c861599e4b3140c68c",
          "sha256": "9f635f87c0f30cc9ee3ffd64ebbac39999fffdc85b7b487f76b79447009c51ea",
          "sha1": "ff3ea49f27328835bfea008a6d468222e92ff2bd",
          "md5": "b4c22f3e95014264c585cd666366c124"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-alpha06.jar",
          "url": "collection-jvm-1.5.0-alpha06.jar",
          "size": 877303,
          "sha512": "f4fa071477bc56ad2ae9a09dc720e3a78f8a7145b5d9a2332313dd71d51cc2c7eb6dfb979d47edfd779cf44e17e5948a65093d43df4cd5c861599e4b3140c68c",
          "sha256": "9f635f87c0f30cc9ee3ffd64ebbac39999fffdc85b7b487f76b79447009c51ea",
          "sha1": "ff3ea49f27328835bfea008a6d468222e92ff2bd",
          "md5": "b4c22f3e95014264c585cd666366c124"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-alpha06-sources.jar",
          "url": "collection-jvm-1.5.0-alpha06-sources.jar",
          "size": 288142,
          "sha512": "a8262322370ef6fac5239b3a92b2f51ebb6092f6bae532c5de2cc20da4767fbb5475acbe897274795a4b4e53ace5c12f9b335d8d46e6cc5ae903dd577aadaafb",
          "sha256": "51e207d50fe6e9663574975171231456c94b441154fa330444d3065fc0a5a2dd",
          "sha1": "29937a6dc283c31d3e30472d9770b6bd7d71710e",
          "md5": "2fe5cee5997a9f0438dd5f2a8d9e6d9d"
        }
      ]
    }
  ]
}