{
  "formatVersion": "1.1",
  "component": {
    "url": "../../urlencoder-lib/1.5.0/urlencoder-lib-1.5.0.module",
    "group": "net.thauvin.erik.urlencoder",
    "module": "urlencoder-lib",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "urlencoder-lib-jvm-1.5.0.jar",
          "url": "urlencoder-lib-jvm-1.5.0.jar",
          "size": 6614,
          "sha512": "5551e78fecb614a9d4f3b6c20fd7a97d38cbd39ac331841e2d49db27160d53bc635ef2e8bf403d14655a169cbdf0beb7035c122cf221950aeb19cd44cd359523",
          "sha256": "b2caad7c083e001e21d405aaa6e6bef49445e012f730269b2c18894ec705f86c",
          "sha1": "93179364d9e915b17baa4160877fa770154e9aa5",
          "md5": "4ec5318160a3410b6613b3d7ee3f59aa"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "urlencoder-lib-jvm-1.5.0.jar",
          "url": "urlencoder-lib-jvm-1.5.0.jar",
          "size": 6614,
          "sha512": "5551e78fecb614a9d4f3b6c20fd7a97d38cbd39ac331841e2d49db27160d53bc635ef2e8bf403d14655a169cbdf0beb7035c122cf221950aeb19cd44cd359523",
          "sha256": "b2caad7c083e001e21d405aaa6e6bef49445e012f730269b2c18894ec705f86c",
          "sha1": "93179364d9e915b17baa4160877fa770154e9aa5",
          "md5": "4ec5318160a3410b6613b3d7ee3f59aa"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "urlencoder-lib-jvm-1.5.0-sources.jar",
          "url": "urlencoder-lib-jvm-1.5.0-sources.jar",
          "size": 5423,
          "sha512": "6d272d3a17228486342b6e7c322db1f568837220a122f719a5164cc919d02fe1a88890f71faeee2e90e49b433544684464da0f7726032b81c578b7b38a5e200a",
          "sha256": "ec107ce47aa4db7ffb9b892cee846dc88ee1cac745b6ecabd7d89de12253edd0",
          "sha1": "02a5c531e4b4afef02d124c081c41024852eefc4",
          "md5": "8856ec122a055312165178cefe23d51d"
        }
      ]
    }
  ]
}
