{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.5.0-alpha03/collection-1.5.0-alpha03.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-alpha03"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-alpha03.jar",
          "url": "collection-jvm-1.5.0-alpha03.jar",
          "size": 875184,
          "sha512": "b1bd9e900a5107bff754fe7d9ccde5f13fccbeec37eb745da954e8730c8d5ec59925f8b4a98b0da0a658f9d86e6619b2bd79f4c9a46dc84db4dd6366ca07bebe",
          "sha256": "a3f962c2cd60b8593293646434a11953da3609e65fb5272716c0a2f4abd54fb9",
          "sha1": "f66d5f375378264bf0b8b10b9bdeb3af29940458",
          "md5": "e72651184ec0a191f300aa745e4dd463"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-alpha03"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-alpha03.jar",
          "url": "collection-jvm-1.5.0-alpha03.jar",
          "size": 875184,
          "sha512": "b1bd9e900a5107bff754fe7d9ccde5f13fccbeec37eb745da954e8730c8d5ec59925f8b4a98b0da0a658f9d86e6619b2bd79f4c9a46dc84db4dd6366ca07bebe",
          "sha256": "a3f962c2cd60b8593293646434a11953da3609e65fb5272716c0a2f4abd54fb9",
          "sha1": "f66d5f375378264bf0b8b10b9bdeb3af29940458",
          "md5": "e72651184ec0a191f300aa745e4dd463"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-alpha03"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-alpha03-sources.jar",
          "url": "collection-jvm-1.5.0-alpha03-sources.jar",
          "size": 286919,
          "sha512": "343203b70fbf66c0da7e4a95c9dc4113fafc46cd0f70d138e2013ceca38ad9771d91279a78b0bd501b6781e7e5d2209e25552a6eb97bfb23e253f845879de36d",
          "sha256": "a0decb84a97bacf1e0f0bf10fc55ede19d72da120e99f3833e777f930a3d7386",
          "sha1": "a7a9abe9dbad7433b2c59a6d3c333d5be6123eca",
          "md5": "46f0682c41072e325f03e58c2e78019d"
        }
      ]
    }
  ]
}