{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.6.0-dev1369/animation-core-1.6.0-dev1369.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "1.6.0-dev1369",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.6.0-dev1369.jar",
          "url": "animation-core-desktop-1.6.0-dev1369.jar",
          "size": 323727,
          "sha512": "1cb1075ea2234ed0c149c1a1c5d9155cca80474bceb20951d5d9c640f61f138bca3a646bcbc7b85408db562a16a2e196466c347577800699e443fa528a01ed41",
          "sha256": "433015723928b41f12d2889982bdd5f3f1edd77898b01de0daa37232e2e89a5a",
          "sha1": "c7f710124defa585807e2f2fd6316fdb8a81033d",
          "md5": "dfc17491025bd63bb4e8ee3db9407aa9"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-dev1369"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-dev1369"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-dev1369"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-dev1369"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.6.0-dev1369.jar",
          "url": "animation-core-desktop-1.6.0-dev1369.jar",
          "size": 323727,
          "sha512": "1cb1075ea2234ed0c149c1a1c5d9155cca80474bceb20951d5d9c640f61f138bca3a646bcbc7b85408db562a16a2e196466c347577800699e443fa528a01ed41",
          "sha256": "433015723928b41f12d2889982bdd5f3f1edd77898b01de0daa37232e2e89a5a",
          "sha1": "c7f710124defa585807e2f2fd6316fdb8a81033d",
          "md5": "dfc17491025bd63bb4e8ee3db9407aa9"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "animation-core-desktop-1.6.0-dev1369-sources.jar",
          "url": "animation-core-desktop-1.6.0-dev1369-sources.jar",
          "size": 81881,
          "sha512": "f38c3c163e21eaf6431442c5c7226d2ab14e62b1e2fd7c1def1b551b84f4a3c4f7bdf6a41bba512c0ec4f5f5ca4c5c7a161a233bb8625bdce8c76ffdf7f3f7ab",
          "sha256": "1213a39e612c3ec5ad81932c4579ca6cc2a9a45148dfea631aef01a6a9232002",
          "sha1": "af173ce05ec4dcf4a3119e91290d57704d105072",
          "md5": "8dfe7a7d3e61f904faa1c7948b0b0dd1"
        }
      ]
    }
  ]
}