{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-lint",
    "version": "1.8.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-lint-1.8.0-alpha06.jar",
          "url": "material-lint-1.8.0-alpha06.jar",
          "size": 1053184,
          "sha512": "5cfdf034f3ba71194e95674a24733fb85b37fb2d32235d9ac5c1c9d8e943c1e63474c2c2ea162d59e8653e477644ddb1639adc0c2ef8ab9e04d4d52817d7d4ed",
          "sha256": "c24e24e067510b88988b436425f70b7a8c0bc13f3e97a5336b45feb225606eda",
          "sha1": "0ad1cf9202f2d01ad227545090a9b1487c2c7ae3",
          "md5": "3c2c41879bf686986f578b1f7e68a2bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-lint-1.8.0-alpha06.jar",
          "url": "material-lint-1.8.0-alpha06.jar",
          "size": 1053184,
          "sha512": "5cfdf034f3ba71194e95674a24733fb85b37fb2d32235d9ac5c1c9d8e943c1e63474c2c2ea162d59e8653e477644ddb1639adc0c2ef8ab9e04d4d52817d7d4ed",
          "sha256": "c24e24e067510b88988b436425f70b7a8c0bc13f3e97a5336b45feb225606eda",
          "sha1": "0ad1cf9202f2d01ad227545090a9b1487c2c7ae3",
          "md5": "3c2c41879bf686986f578b1f7e68a2bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-lint-1.8.0-alpha06-sources.jar",
          "url": "material-lint-1.8.0-alpha06-sources.jar",
          "size": 12195,
          "sha512": "8b265e0a67c99eb528bbe06ce6e32a6eb2205b9784589fef99c5199809b928711771302c124f1b9d4b89dd0f3c2e81c0ed57587114dff99c9bdb19cdd72c5ef4",
          "sha256": "c73cdb083ac866d10a060778a1b837c14f5fb920fea67ef16f8f3b3c268d3d0b",
          "sha1": "46a59230df893c769404c308ec3a48802a09f5d1",
          "md5": "5a484969cef14eb19dd284cd62b56a1d"
        }
      ]
    }
  ]
}