{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.8.0-alpha03-multiplatform-sources.jar",
          "url": "runtime-saveable-1.8.0-alpha03-multiplatform-sources.jar",
          "size": 16560,
          "sha512": "1744f891e6563a19ed705125b4f49a2b65c0492198599fd9e6f2b6604c4dc4505d86fa7f826e0906fcac2f8778266030997faf7af9da8e9ba6e6bf0cb3e18824",
          "sha256": "f676b5d0c200821ed248c53f5e4069309c24a2a69835188271667a9807df09e9",
          "sha1": "b08e04502d892d7137d77ad0c91c3e1a4201d0da",
          "md5": "f5abdef7df712c5bf9e72fbcc1463627"
        },
        {
          "name": "runtime-saveable-1.8.0-alpha03-samples-sources.jar",
          "url": "runtime-saveable-1.8.0-alpha03-samples-sources.jar",
          "size": 8597,
          "sha512": "509151aab0db321992be131dcaddd9bb3cc61b4060b6d9efad2f12c2e1c07fe96dd8b0e624dc0accdb6e1edf7f7773c1449a507302b9917c4970b753f9b45300",
          "sha256": "1540c1f764bfabc5ce175097db8fcbfc1519d9ceb42a7989ba3147f3e7b286c9",
          "sha1": "bad09107d9683f4d66fa2d27773cf5240a5c906a",
          "md5": "e92332855418830ce92356fe406e72fd"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "runtime-saveable-1.8.0-alpha03-versionMetadata.json",
          "size": 3405,
          "sha512": "44994ff2de449c13516ea4c1ce34b41a9ce342c1450f80e6b29f35c743f18d697fe8beb96f2274bb43aa28aab41da942067c8ada96f42cc441c7eedd9b69795a",
          "sha256": "0a8d078a85cf98ea13d1496ff413d8ea8997a0221141bfdf48b9d3312122d942",
          "sha1": "c52e7ceaaeea18cc935ef5c4b66b32872cfb86b1",
          "md5": "08869e3c20c7b1f5825058e90bfe0e12"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-metadata-1.8.0-alpha03.jar",
          "url": "runtime-saveable-1.8.0-alpha03.jar",
          "size": 10683,
          "sha512": "b818a9c6b904613988049e29b94a0a5b06fd6c86adcc4c993432aec3bc360d2d545a4640baeff58daa7a0137a7b1d122d93cccb576505c5c73139687511df868",
          "sha256": "86d8814d32bbe85d3bb4476f4e438be73d77994148d8c547d0b9b1850aa5309a",
          "sha1": "56203e6d80de326ca5fa2a447545fff97ffe1c71",
          "md5": "6454e41186fcad7f7e816fc38d8884fd"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-kotlin-1.8.0-alpha03-sources.jar",
          "url": "runtime-saveable-1.8.0-alpha03-sources.jar",
          "size": 16244,
          "sha512": "2b09b948b548c02b7cbfd21ddb4f44acbc0a50da30d411f5987e99727f316a1ab0abbcd015d2fdc786565a59daa167c986dec5c2593ed6c1514d34875f17fa46",
          "sha256": "ae70add17dd2954c10d21545f3f7e4ec6018e4f8b94ddabca0754fabe4f8d583",
          "sha1": "21a62ad898d445c6d84dc78d172336032ebfe0cc",
          "md5": "19abfecd1e4af393c36242ccaf7d634a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-android/1.8.0-alpha03/runtime-saveable-android-1.8.0-alpha03.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-android",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-android/1.8.0-alpha03/runtime-saveable-android-1.8.0-alpha03.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-android",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-android/1.8.0-alpha03/runtime-saveable-android-1.8.0-alpha03.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-android",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-jvmstubs/1.8.0-alpha03/runtime-saveable-jvmstubs-1.8.0-alpha03.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-jvmstubs",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-jvmstubs/1.8.0-alpha03/runtime-saveable-jvmstubs-1.8.0-alpha03.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-jvmstubs",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-jvmstubs/1.8.0-alpha03/runtime-saveable-jvmstubs-1.8.0-alpha03.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-jvmstubs",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-linuxx64stubs/1.8.0-alpha03/runtime-saveable-linuxx64stubs-1.8.0-alpha03.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-linuxx64stubs",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-linuxx64stubs/1.8.0-alpha03/runtime-saveable-linuxx64stubs-1.8.0-alpha03.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-linuxx64stubs",
        "version": "1.8.0-alpha03"
      }
    }
  ]
}