# managed by go/iml_to_build
java_import(
    name = "tightvnc",
    jars = ["tightvnc.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build [unb]
filegroup(
    name = "unb.tightvnc_files",
    srcs = ["tightvnc.jar"],
    tags = [
        "manual",
        "unb",
    ],
    visibility = ["//visibility:public"],
)
