{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6875358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saved-instance-state",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.0.0-alpha04.aar",
          "url": "foundation-1.0.0-alpha04.aar",
          "size": 374622,
          "sha512": "d4a69c8a4345b9b5935142982fc412e0072f80cee54d2c4c6b176c5c05819bdc49c50b3ac9c3783cbc132f41846173ef69372e944a7766a9c88f4553c38083cc",
          "sha256": "5dfb83fac9f619c91177a91c834cc88d23312073fbf2b761f44633cbd850c7c7",
          "sha1": "a68a5d315e50219153a5c5a86e7231bf1728618d",
          "md5": "48aa1d5f3b22c98a9354caa4bd038189"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saved-instance-state",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-text",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.0.0-alpha04.aar",
          "url": "foundation-1.0.0-alpha04.aar",
          "size": 374622,
          "sha512": "d4a69c8a4345b9b5935142982fc412e0072f80cee54d2c4c6b176c5c05819bdc49c50b3ac9c3783cbc132f41846173ef69372e944a7766a9c88f4553c38083cc",
          "sha256": "5dfb83fac9f619c91177a91c834cc88d23312073fbf2b761f44633cbd850c7c7",
          "sha1": "a68a5d315e50219153a5c5a86e7231bf1728618d",
          "md5": "48aa1d5f3b22c98a9354caa4bd038189"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-1.0.0-alpha04-sources.jar",
          "url": "foundation-1.0.0-alpha04-sources.jar",
          "size": 223055,
          "sha512": "5ab6fe28b3ceae3c40dc7b4e36c6acaff637b0c09c87faebdd7845b529228027387c8e3a8da849b61f68d491b726e87d1d27199d432ca7414cd65036a93064fa",
          "sha256": "7af4729dfebedad099695f92cfeb9fe2c040996b6f9a5c60dba0cfcea988511e",
          "sha1": "bed2f9cce666abd990479b1c312d95fbcb7896a9",
          "md5": "190373230d04cbf6a9ca79faded5c476"
        }
      ]
    }
  ]
}
