{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "material-ripple-1.7.8-multiplatform-sources.jar",
          "url": "material-ripple-1.7.8-multiplatform-sources.jar",
          "size": 26807,
          "sha512": "56ab05baa1312e8f789d9d3d0359b752bffad47426afa385d6a719986abb8611a30a623aaa0c0d63844ab1dc0437ccd48a090e82c3bcc499443b86bea292e3f4",
          "sha256": "fc11d3f2d796fade2df5d9a0e73e792f4c34d96a45df2c1bb67cd7fa65afbef7",
          "sha1": "af6200ef2f75e75fde984a42af369d4121d34469",
          "md5": "9c911ab729c3c7a48cfc978b78c3d407"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material-ripple-1.7.8-versionMetadata.json",
          "size": 1708,
          "sha512": "87c096380f24cca80eb7ca5e9d0229e7a5e8c33a1c95af613a6fc2d7cac3027e45d63502f8c737f87d8939590e32d5d58290f289640a7a455856e11424a9230d",
          "sha256": "d4985ccfc992415d99b93b8fe186bace896ee89dec6c5a2da534a069d615ad57",
          "sha1": "53a05c720630ac9b44256b75f4437e14e0723e58",
          "md5": "3dc420123b0d2c822ae68c039647c0a3"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.8"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-metadata-1.7.8.jar",
          "url": "material-ripple-1.7.8.jar",
          "size": 12254,
          "sha512": "dc86b71e58d2566e5891f984b2086ea1dfd0d6b447284136707db7379a699a60ff7f299cf90f9f39cb8914ab318bc73af0fe2c327da76f9f85fbf67faad29007",
          "sha256": "e14c5df7b718f952faf6bd07fa8cf5529d4a5b4728deef8651b332a7d36ca668",
          "sha1": "9ec2d609b5c7a77b21b495211f1680bc31dc4779",
          "md5": "f2d12469161931e5cc44dc62f1bc536c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-ripple-kotlin-1.7.8-sources.jar",
          "url": "material-ripple-1.7.8-sources.jar",
          "size": 16070,
          "sha512": "e5406dd59187da17d53d0ca499ca78c592673780562d8cba7b9c089ea0befa9d12de26a75b9c0dbd9f355d9cc7c7c10c67e36c8c1e0608622c3b614781de386b",
          "sha256": "c62d1862af6dd2d0d4c13cd27ad0a437ea53140b0f5ec6e389597a77232d3528",
          "sha1": "b120634edc09273ab432ce2a0cc17ec81cb9fd0a",
          "md5": "d508643ed0fe5df8bbeca929fc90cd7a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.7.8/material-ripple-android-1.7.8.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.7.8"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.7.8/material-ripple-android-1.7.8.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.7.8"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.7.8/material-ripple-android-1.7.8.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.7.8"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-jvmstubs/1.7.8/material-ripple-jvmstubs-1.7.8.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-jvmstubs",
        "version": "1.7.8"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-jvmstubs/1.7.8/material-ripple-jvmstubs-1.7.8.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-jvmstubs",
        "version": "1.7.8"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-jvmstubs/1.7.8/material-ripple-jvmstubs-1.7.8.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-jvmstubs",
        "version": "1.7.8"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-ripple-linuxx64stubs/1.7.8/material-ripple-linuxx64stubs-1.7.8.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-linuxx64stubs",
        "version": "1.7.8"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-ripple-linuxx64stubs/1.7.8/material-ripple-linuxx64stubs-1.7.8.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-linuxx64stubs",
        "version": "1.7.8"
      }
    }
  ]
}