{
  "formatVersion": "1.1",
  "component": {
    "group": "io.outfoxx",
    "module": "swiftpoet",
    "version": "1.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "swiftpoet-1.6.5.jar",
          "url": "swiftpoet-1.6.5.jar",
          "size": 217460,
          "sha512": "584120214eef09c2ebfa5e9fe3cab18f38c0d19201e3f74a071a927cc331996eb94a43bb648b48704759934382f277fbccfce62fcebd821698f80e253b11294b",
          "sha256": "8f825d9eb0ffda5561a55d6764b52195cfe254289fce6a80d211571a338e894f",
          "sha1": "5482c62c622b9d07b1b8bb208cd6666e784b2ba9",
          "md5": "836750c40a1d417837a7fc614d8672b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "swiftpoet-1.6.5.jar",
          "url": "swiftpoet-1.6.5.jar",
          "size": 217460,
          "sha512": "584120214eef09c2ebfa5e9fe3cab18f38c0d19201e3f74a071a927cc331996eb94a43bb648b48704759934382f277fbccfce62fcebd821698f80e253b11294b",
          "sha256": "8f825d9eb0ffda5561a55d6764b52195cfe254289fce6a80d211571a338e894f",
          "sha1": "5482c62c622b9d07b1b8bb208cd6666e784b2ba9",
          "md5": "836750c40a1d417837a7fc614d8672b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "swiftpoet-1.6.5-sources.jar",
          "url": "swiftpoet-1.6.5-sources.jar",
          "size": 53845,
          "sha512": "9e24f99985f6d4fa0f7c94519659dd3d3d9ed2da43451895808a3b2bcc04d366fd7c59ff05575ad29d3a1b6eadfbc48fadca6f76813eed4a9257528ad13cfdc8",
          "sha256": "43bf8cdb9c85e64558e639a1b81661852de37601f26a8973f54110d4a66da4fb",
          "sha1": "a3b81b44e29a52aeb79adbc9c4a919edd72a83e3",
          "md5": "dfec93c872e65992b2dd1bfcf9f9a421"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "swiftpoet-1.6.5-javadoc.jar",
          "url": "swiftpoet-1.6.5-javadoc.jar",
          "size": 261,
          "sha512": "c714046385391ddcf9f6093b303547e29e2d2e90be75a84bf3f1a58d5ab5d98cc00d5c9249249575b55f6b65091b8d0a98f15c09225507248b565e82cf72b46f",
          "sha256": "2707b8839084b43f1a734908578dd54662c013537e301a0524a63324be69b6b5",
          "sha1": "6bfb159dab0bd7a066d7c8027f88bf26d71862f0",
          "md5": "8da63de88aa82a18be8dc83f294d786e"
        }
      ]
    }
  ]
}
