{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.horologist",
    "module": "horologist-annotations",
    "version": "0.6.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "horologist-annotations-0.6.17.jar",
          "url": "horologist-annotations-0.6.17.jar",
          "size": 1914,
          "sha512": "51121c5b54743f7cad1eebffb510e025c22e0ec18be80aea6774f98cb9fd7db639fe76fd4dc4f4bdd7ef82b66796c9c127e74199b1e7d5aa4aaab23cc05306d1",
          "sha256": "f8f414c5336b79ffd9ba16e237e3498a87d50ab22220d2c0786b8d3e7249f09c",
          "sha1": "b9648bf9682ee70253c20f8868a46f39589547ad",
          "md5": "50d8f8753291bf1020a1a8ce3caa9a68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "horologist-annotations-0.6.17.jar",
          "url": "horologist-annotations-0.6.17.jar",
          "size": 1914,
          "sha512": "51121c5b54743f7cad1eebffb510e025c22e0ec18be80aea6774f98cb9fd7db639fe76fd4dc4f4bdd7ef82b66796c9c127e74199b1e7d5aa4aaab23cc05306d1",
          "sha256": "f8f414c5336b79ffd9ba16e237e3498a87d50ab22220d2c0786b8d3e7249f09c",
          "sha1": "b9648bf9682ee70253c20f8868a46f39589547ad",
          "md5": "50d8f8753291bf1020a1a8ce3caa9a68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "horologist-annotations-0.6.17-sources.jar",
          "url": "horologist-annotations-0.6.17-sources.jar",
          "size": 1789,
          "sha512": "0ccce96dd3e5bde38e83c4015b9b88abc8d4b0ed1c203b4603034e6dfd837072684350fe70eefab9cccffe9513b9513774adf5a38ef16b7cb477f38090a47a5b",
          "sha256": "89e3f56d324db082e51ca584e172b5e10446e0e0c28bf176a5af1cc11ab4b67a",
          "sha1": "2d38833549fb883be3e531a875fe1a6a0be69a99",
          "md5": "a1f5ff28f1cb98dc1d92b9e8214b77e6"
        }
      ]
    }
  ]
}
