{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-core",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha10-sources.jar",
          "url": "ui-core-1.0.0-alpha10-sources.jar",
          "size": 16152,
          "sha512": "8ce3a12f7ee72958dbd9612c138d579eb0e973c83d2462901c6fe43635195653fc3c35b4eb95ab584e4a61e883d30418368ac1f682324c7447a031752998632c",
          "sha256": "68d2ba6eb0edbc1569b9e42cbfbe66bce799cbe1b6f3c7b65760c6a929201f58",
          "sha1": "4056ecee9af4f45ad424e4aab248143103af55a9",
          "md5": "84671aaee1188afa8bfbb6850770dd87"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha10.aar",
          "url": "ui-core-1.0.0-alpha10.aar",
          "size": 38132,
          "sha512": "4499314e398420627b0c33c26098621cd2ffd1f44b853c564940e61362ac540f4b829a0073216ec77e39bd2690a06650ef967b4c58306f8cd27374e117ba4e3b",
          "sha256": "2de4a6db2004835e3c7c8985ecf86f879f960c9e4a7d4b3becfcd014da92f7ea",
          "sha1": "577b55bfb64a9fae5f3f0ebe485243b441cfc3fb",
          "md5": "d718552572f29cc2fb5b8ba2b778093b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha10.aar",
          "url": "ui-core-1.0.0-alpha10.aar",
          "size": 38132,
          "sha512": "4499314e398420627b0c33c26098621cd2ffd1f44b853c564940e61362ac540f4b829a0073216ec77e39bd2690a06650ef967b4c58306f8cd27374e117ba4e3b",
          "sha256": "2de4a6db2004835e3c7c8985ecf86f879f960c9e4a7d4b3becfcd014da92f7ea",
          "sha1": "577b55bfb64a9fae5f3f0ebe485243b441cfc3fb",
          "md5": "d718552572f29cc2fb5b8ba2b778093b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha10-versionMetadata.json",
          "url": "ui-core-1.0.0-alpha10-versionMetadata.json",
          "size": 3852,
          "sha512": "71d36242b21339d682a93aec1195a8c71ba919c9713239b49be8b09e92e75854d7342d4c632c63bdd0b76726006282e4ae3310dcaf74676bd9c09270e4033967",
          "sha256": "ddf0cd827f4103697ff2d049e3db2eddca893821f53d56c25e52444824da7baa",
          "sha1": "1ac7f069fe97ea1058d66c27d159ad3a76a0bd3b",
          "md5": "11085c75d4ad008fb41182a12dfab328"
        }
      ]
    }
  ]
}