#!/bin/bash

# Set JAVA_HOME to the one in prebuilts
JDK_DIR=$(dirname "$0")/../../../studio/jdk/jdk17
OS_NAME=$(uname)
ARCH=$(uname -m)

if [[ $OS_NAME == "Linux" ]]; then
    JAVA_HOME="$JDK_DIR/linux"
elif [[ $OS_NAME == "Darwin" && $ARCH == "arm64" ]]; then
    JAVA_HOME="$JDK_DIR/mac-arm64/Contents/Home"
elif [[ $OS_NAME == "Darwin" && $ARCH == "x86_64" ]]; then
    JAVA_HOME="$JDK_DIR/mac/Contents/Home"
else
    die "Unsupported OS: $OS_NAME or architecture: $ARCH"
fi

# TODO(476037624): add --enable-editorconfig once all projects have it enabled
$JAVA_HOME/bin/java -jar `dirname "$0"`/ktfmt-0.61-with-dependencies.jar "$@"
