{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.8.0-alpha06/foundation-layout-1.8.0-alpha06.module",
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.8.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout.aar",
          "url": "foundation-layout-android-1.8.0-alpha06.aar",
          "size": 664498,
          "sha512": "94821b3dfdeb84e209f1a9204c80f0533c4a26fbe0ea49b8a01ac38454b75d751f794e2b2491966da09d33a839120bed997ab4eb70ce0ed987e242f11f4cb918",
          "sha256": "7a78fbd7d7ef92d8433d3457acf9e99f6c8bf3d876834591c6b9aef38e5c5211",
          "sha1": "9126a92d0966cd896a6dfdaef090c5fad66ee523",
          "md5": "502c3cbb56e4610f82b64e31d3fe4ecf"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha06"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout.aar",
          "url": "foundation-layout-android-1.8.0-alpha06.aar",
          "size": 664498,
          "sha512": "94821b3dfdeb84e209f1a9204c80f0533c4a26fbe0ea49b8a01ac38454b75d751f794e2b2491966da09d33a839120bed997ab4eb70ce0ed987e242f11f4cb918",
          "sha256": "7a78fbd7d7ef92d8433d3457acf9e99f6c8bf3d876834591c6b9aef38e5c5211",
          "sha1": "9126a92d0966cd896a6dfdaef090c5fad66ee523",
          "md5": "502c3cbb56e4610f82b64e31d3fe4ecf"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-android-1.8.0-alpha06-sources.jar",
          "url": "foundation-layout-android-1.8.0-alpha06-sources.jar",
          "size": 104106,
          "sha512": "2deaf19656d8fa000f4550ea05e0551fad303f98d4c61921018c2d727fc8e5a0f094c70193a832b82f49bcb19531896252341ef7483bc23bf738cc56b6771f4d",
          "sha256": "90b201ace1dc971829461ab23ae021bd6a2b2647e0d96a884cce7aae0bcb6878",
          "sha1": "82c96cbe55750e3c948c7a9bce8caeda47003f4a",
          "md5": "4e91f9e4dd47c0a4fb9bd3db347bf0dc"
        },
        {
          "name": "foundation-layout-1.8.0-alpha06-samples-sources.jar",
          "url": "foundation-layout-android-1.8.0-alpha06-samples-sources.jar",
          "size": 31506,
          "sha512": "1fe889d4561d3a9d29e092e9b44e3bb198d0b462c6b742224859bae5a3e00bbcac63facddde72d1e7fb833384cd52086b37affde9c29fdf85b149c0c851ea029",
          "sha256": "724dda94d1512b2bcf4a452e65a156ccbb5edafc6164fd41d49860b1063edb43",
          "sha1": "efe7fc7e0cbdf44c0e4279e2fc5e3e53a5c61948",
          "md5": "ad0967b4cf2e7fe10adf691136f71748"
        }
      ]
    }
  ]
}