{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.analytics-library",
    "module": "crash",
    "version": "30.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crash-30.0.0.jar",
          "url": "crash-30.0.0.jar",
          "size": 13628,
          "sha512": "191c30f6a3b66cf24be471378ec29a723f87e5a0016054e8d9c28559a65c2e2443e20468bc122d1704c5e7dd53d4318411bd338a133ed809406d70321a33f6f8",
          "sha256": "6a8f15734a795686200ac2966def25a999223ca5e5a44354d562779c21650170",
          "sha1": "7df3f0c2e80e2a1b936077abc0b1d17d704d491d",
          "md5": "ab2272c67778af05ed87575a7318f60c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.4.10"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "crash-30.0.0.jar",
          "url": "crash-30.0.0.jar",
          "size": 13628,
          "sha512": "191c30f6a3b66cf24be471378ec29a723f87e5a0016054e8d9c28559a65c2e2443e20468bc122d1704c5e7dd53d4318411bd338a133ed809406d70321a33f6f8",
          "sha256": "6a8f15734a795686200ac2966def25a999223ca5e5a44354d562779c21650170",
          "sha1": "7df3f0c2e80e2a1b936077abc0b1d17d704d491d",
          "md5": "ab2272c67778af05ed87575a7318f60c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crash-30.0.0-javadoc.jar",
          "url": "crash-30.0.0-javadoc.jar",
          "size": 408768,
          "sha512": "d450c43b941f87dfee34378390997595e57355624cacf341290b91792d4d526f8d2a802e18bb23399c7f6d3574aa32855eb4accf7a949cecc917ef049a9f861e",
          "sha256": "8fee151359e72618cee208d3b14d02431547545ea38f8bb7660f7f03e3893c06",
          "sha1": "0851ec508252f3a06bc9060d410fd3805aff1ffd",
          "md5": "2e91839087b80aaefb3f1cfaf2ec1056"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "crash-30.0.0-sources.jar",
          "url": "crash-30.0.0-sources.jar",
          "size": 10684,
          "sha512": "c14bc168974c86c78ed8b4f383c15efbccc08b7ef123b0be6d8a6c67271b8c41e685094e3573ce459201183e6d74527dadf47b6fd563f5304b0b8b14da70e47c",
          "sha256": "74b78b9e8279de805f16c40d18d3da3214e47c064dc7f7c1f62d78f9ff6d6335",
          "sha1": "b1938328b6a37450d4d8ce3f1e4032c1ad07450b",
          "md5": "72129a42a0f08ea4cb94e09410b39020"
        }
      ]
    }
  ]
}
