{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.6.0-dev1369/ui-util-1.6.0-dev1369.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-util",
    "version": "1.6.0-dev1369",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-util-desktop-1.6.0-dev1369.jar",
          "url": "ui-util-desktop-1.6.0-dev1369.jar",
          "size": 6322,
          "sha512": "6e90150ddf2d8eb5235af898b85dd56b3cc15e77d47be6dc2c43de453b2958aa831e605430a5696f4ec16aa582f9e25d2e8a86c2bcdb78ef59ed002e86cf3a64",
          "sha256": "56ec071c78b4824bda2a96781304283756b088e241a41ac7db1435adc0915b61",
          "sha1": "82fadb7456a2328ac783c2a3b93641fbfe416dde",
          "md5": "42b103b9f4b925ede16847b8221017c2"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-desktop-1.6.0-dev1369.jar",
          "url": "ui-util-desktop-1.6.0-dev1369.jar",
          "size": 6322,
          "sha512": "6e90150ddf2d8eb5235af898b85dd56b3cc15e77d47be6dc2c43de453b2958aa831e605430a5696f4ec16aa582f9e25d2e8a86c2bcdb78ef59ed002e86cf3a64",
          "sha256": "56ec071c78b4824bda2a96781304283756b088e241a41ac7db1435adc0915b61",
          "sha1": "82fadb7456a2328ac783c2a3b93641fbfe416dde",
          "md5": "42b103b9f4b925ede16847b8221017c2"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-util-desktop-1.6.0-dev1369-sources.jar",
          "url": "ui-util-desktop-1.6.0-dev1369-sources.jar",
          "size": 4370,
          "sha512": "a345635bf2543c4e8d3917cf7f5bdc31bc6c952f2affb0109e2f3b37f7dbc8ae8fb7045d5ef91146b4eb98417a855ef00ec0a27651d0c49fc271094edfd5c501",
          "sha256": "cea877d7e3d74b36050a2c8ed1d265ecfdb5e1dc0a036f7c29437755b38465c8",
          "sha1": "5d7cde69db891fc0b6f9f5f0582fdefdcb990fbb",
          "md5": "6501e66a4ce899006f8f8a4a79531abb"
        }
      ]
    }
  ]
}