{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.7.7/material-ripple-1.7.7.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.7"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-jvmstubs-1.7.7.jar",
          "url": "material-ripple-jvmstubs-1.7.7.jar",
          "size": 74390,
          "sha512": "9f5b3d4f074a525c018489ae39f8565475018abf2cbc6a747931efde31249f1dc0708481dd720e29373a601d6a857c34ec2c5a85222348d3b81604340bede6c5",
          "sha256": "84050d45b203e42ccb9998e6d9e6d7952212dd425242d2ab9cfc1a50fad900c5",
          "sha1": "f85b2211b8ea1a1f934451480154edc39a39bb6b",
          "md5": "f0e60228714754055c636759afeef25d"
        }
      ]
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-jvmstubs-1.7.7.jar",
          "url": "material-ripple-jvmstubs-1.7.7.jar",
          "size": 74390,
          "sha512": "9f5b3d4f074a525c018489ae39f8565475018abf2cbc6a747931efde31249f1dc0708481dd720e29373a601d6a857c34ec2c5a85222348d3b81604340bede6c5",
          "sha256": "84050d45b203e42ccb9998e6d9e6d7952212dd425242d2ab9cfc1a50fad900c5",
          "sha1": "f85b2211b8ea1a1f934451480154edc39a39bb6b",
          "md5": "f0e60228714754055c636759afeef25d"
        }
      ]
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-ripple-jvmstubs-1.7.7-sources.jar",
          "url": "material-ripple-jvmstubs-1.7.7-sources.jar",
          "size": 16070,
          "sha512": "269bc27b0e3cc34c51a9ac500acd4306a8aa59f559315e6f1e3277ee4deaf48703ca5c27cfd4a2c946cb3daa83d977eda1b5458e86e013e45d98bba3e48980eb",
          "sha256": "887c8fe7933d4c5672383478b6d4f8b690bf75729cf06bade687512f11f3909a",
          "sha1": "922052b449441b6507e4326eb16f6759aa9ccd21",
          "md5": "06205cb64ea2385a7f39429f4eb6128a"
        }
      ]
    }
  ]
}