{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-gradle-plugin",
    "version": "2.1.20-1.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.1.20-1.0.31.jar",
          "url": "symbol-processing-gradle-plugin-2.1.20-1.0.31.jar",
          "size": 201125,
          "sha512": "7d948473006795714561c9350cdf218bc700dac07145949eefb47b0c6405f142a29231ad0e0bfd7a8918fc4c0bcc6e6e43f2843237df039d0fec9a45f9f2e562",
          "sha256": "d9ec244fa33e157424f1e0368cd016c4a23869dc2c51fb6b93af9a52ec482152",
          "sha1": "d4ca395419adb08099efa001ab7f0ce452b03ea0",
          "md5": "a1fa70455e4a5058d6aa29a918ff51bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.20-1.0.31"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.1.20-1.0.31"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.1.20-1.0.31.jar",
          "url": "symbol-processing-gradle-plugin-2.1.20-1.0.31.jar",
          "size": 201125,
          "sha512": "7d948473006795714561c9350cdf218bc700dac07145949eefb47b0c6405f142a29231ad0e0bfd7a8918fc4c0bcc6e6e43f2843237df039d0fec9a45f9f2e562",
          "sha256": "d9ec244fa33e157424f1e0368cd016c4a23869dc2c51fb6b93af9a52ec482152",
          "sha1": "d4ca395419adb08099efa001ab7f0ce452b03ea0",
          "md5": "a1fa70455e4a5058d6aa29a918ff51bd"
        }
      ]
    }
  ]
}
