{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.9.0/material-ripple-1.9.0.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13900193"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple.aar",
          "url": "material-ripple-android-1.9.0.aar",
          "size": 96342,
          "sha512": "74658c4e96a33a36be911fe4e25e605bddf25366562357f202f23a28e07c712b13d01cce6eab3fa82a4c9b736864f4c4ccdc4da53efaf706130b2c4eb772add5",
          "sha256": "e09fd2c7e7d11005b07699502f778884b8cb9bf1409b10b0d2ee03cd903ce11a",
          "sha1": "7d461d74ad58d5055264ce5e84418b5276fa9f7b",
          "md5": "5eff9ced44c02a6c7e1f614ed8134f3b"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple.aar",
          "url": "material-ripple-android-1.9.0.aar",
          "size": 96342,
          "sha512": "74658c4e96a33a36be911fe4e25e605bddf25366562357f202f23a28e07c712b13d01cce6eab3fa82a4c9b736864f4c4ccdc4da53efaf706130b2c4eb772add5",
          "sha256": "e09fd2c7e7d11005b07699502f778884b8cb9bf1409b10b0d2ee03cd903ce11a",
          "sha1": "7d461d74ad58d5055264ce5e84418b5276fa9f7b",
          "md5": "5eff9ced44c02a6c7e1f614ed8134f3b"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-ripple-android-1.9.0-sources.jar",
          "url": "material-ripple-android-1.9.0-sources.jar",
          "size": 30931,
          "sha512": "309bf956dd1f33491f1c9bcc3b4425d65b3ac7097653790ec8289c27aacedb65b14e2ac945bc14b48eaa4d55c9690b5019fd9a7832065b585b29bd2e33f86a0a",
          "sha256": "7ec7d1d2136078edeadd3b01ab10af49b79f3d8b9b498a0ecf49416ebda7d252",
          "sha1": "d37b944000427856b3a7213886c940ed285356e3",
          "md5": "3b59f57a315b71974d18033437599da0"
        }
      ]
    }
  ]
}