{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-gradle-plugin-model",
    "version": "2.0.0-Beta4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ]
    },
    {
      "name": "gradle70JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle70-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle70-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle70SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle70-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle70-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle70ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle70.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle70RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle70.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle71JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle71-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle71-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle71SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle71-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle71-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle71ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle71.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle71.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle71RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle71.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle71.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle74JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle74-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle74-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle74",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle74SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle74-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle74-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle74",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle74ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle74"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle74.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle74.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle74",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle74RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle74"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle74.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle74.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle74",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle75JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle75-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle75-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle75",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle75SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle75-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle75-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle75",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle75ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle75"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle75.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle75.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle75",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle75RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle75"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle75.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle75.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle75",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle76JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle76-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle76-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle76",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle76SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle76-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle76-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle76",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle76ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle76"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle76.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle76.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle76",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle76RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle76"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle76.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle76.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle76",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle80JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle80-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle80-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle80",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle80-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle80-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle80",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle80.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle80.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle80",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle80.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle80.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle80",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle81JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle81-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle81-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle81",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle81-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle81-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle81",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle81.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle81.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle81",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle81.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle81.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle81",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle82JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle82-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle82-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle82",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle82-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle82-sources.jar",
          "size": 7932,
          "sha512": "1deadf401ba462f2a2d89510fabe179c290c23be96758a09c8c8d9e178fe5674517fb5a194a1e635306f368c09ac110460cd8d25a0d53c600e710e531b552851",
          "sha256": "4b20d6d68a12d1657672c14390c029b38a67ed10e4198fc23a215a489448be1c",
          "sha1": "401ac50e34aa3644a6dc0e4e6959c159c20341d7",
          "md5": "a236c047f810a5339e21bbce5744c86f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle82",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle82.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle82.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle82",
          "version": "2.0.0-Beta4"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.0.0-Beta4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle82.jar",
          "url": "kotlin-gradle-plugin-model-2.0.0-Beta4-gradle82.jar",
          "size": 12588,
          "sha512": "63bc689786385ebd3fbfb96947f8e5cbb63916eb95e2250ce681230fdc9c21fcf34aeedaff5aae310e371e6a5bdf1e4d89373331b36dd357712f36f62a1df076",
          "sha256": "9885a89dac7cf8e81942bdcb1b6ca318c91863c72c1156c7597bf72378cd04eb",
          "sha1": "d8003925e7c208e72a5d5a33bbedc8cf471c21d4",
          "md5": "68e94d0b05e6f11fdc367075b728c75b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle82",
          "version": "2.0.0-Beta4"
        }
      ]
    }
  ]
}
