{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.0.0-RC2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0-RC2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.0.0-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.0.0-RC2-all.jar",
          "url": "kotlin-test-2.0.0-RC2-all.jar",
          "size": 8720,
          "sha512": "7e2be9a7d9002226f2f46e471e8bfe4d7e6defea1359177de40038ec43462e6b540de1a913903efda75c875670a3eada9669691e085618119fdc64a879b4007a",
          "sha256": "3288873963471c51e2ea54a690f605b291b03022675cf0c040080adefbb37010",
          "sha1": "54d065313f746ea93e82b89c79ddbedac927180a",
          "md5": "795927d0b5c2c325a8442a2931a5fe48"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0-RC2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.0.0-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.0.0-RC2.jar",
          "url": "kotlin-test-2.0.0-RC2.jar",
          "size": 101636,
          "sha512": "0b8db68b7fae5f29c7c80556452b7b91149f1288034f7553c98ed492d58f199f36a2d894e5cab1a2e07959c8f63a0fda22c588941b5d7772cc26c2537152eb02",
          "sha256": "9ab7a439b00602672fb5fc8413c1974ca44b6f44cc9a90e18abf331e88a75239",
          "sha1": "49bb684fbcbc80f4ba8f610261e048073ebba109",
          "md5": "178e5b6049afb17532030a1ab1df9b2b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0-RC2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.0.0-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-2.0.0-RC2.jar",
          "url": "kotlin-test-2.0.0-RC2.jar",
          "size": 101636,
          "sha512": "0b8db68b7fae5f29c7c80556452b7b91149f1288034f7553c98ed492d58f199f36a2d894e5cab1a2e07959c8f63a0fda22c588941b5d7772cc26c2537152eb02",
          "sha256": "9ab7a439b00602672fb5fc8413c1974ca44b6f44cc9a90e18abf331e88a75239",
          "sha1": "49bb684fbcbc80f4ba8f610261e048073ebba109",
          "md5": "178e5b6049afb17532030a1ab1df9b2b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-2.0.0-RC2-sources.jar",
          "url": "kotlin-test-2.0.0-RC2-sources.jar",
          "size": 11554,
          "sha512": "c4decd6a8d0b2643f6d9839d40d69f97927435cf350322bd6dd7ebabfbce0fbcd238391f8229cf6809f32d2324104a591f4497be8caf0fee8bbba9acc02e88eb",
          "sha256": "a1a9a16fc5f4e8b2d23a57b9fd39cb04f5e775f2fbb217bb326539e9c8956e1d",
          "sha1": "b2793875afcd0cf0b070db5e1d06ae9fc98bfdd7",
          "md5": "b9ed61dea0ec0d0dfec0574396aa6326"
        }
      ]
    },
    {
      "name": "nativeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "2.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "2.0.0-RC2"
          }
        }
      ]
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.0.0-RC2/kotlin-test-js-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.0.0-RC2"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.0.0-RC2/kotlin-test-js-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.0.0-RC2"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-js/2.0.0-RC2/kotlin-test-js-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-js",
        "version": "2.0.0-RC2"
      }
    },
    {
      "name": "jvmJUnitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.0.0-RC2/kotlin-test-junit-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmJUnitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.0.0-RC2/kotlin-test-junit-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmJUnitSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit/2.0.0-RC2/kotlin-test-junit-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmJUnit5ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.0.0-RC2/kotlin-test-junit5-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmJUnit5RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.0.0-RC2/kotlin-test-junit5-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmJUnit5SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-junit5/2.0.0-RC2/kotlin-test-junit5-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-junit5",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-junit5",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmTestNGApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.0.0-RC2/kotlin-test-testng-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmTestNGRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.0.0-RC2/kotlin-test-testng-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "jvmTestNGSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-test-testng/2.0.0-RC2/kotlin-test-testng-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-testng",
        "version": "2.0.0-RC2"
      },
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework",
          "version": "2.0.0-RC2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-testng",
          "version": "2.0.0-RC2"
        }
      ]
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.0.0-RC2/kotlin-test-wasm-js-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.0.0-RC2"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.0.0-RC2/kotlin-test-wasm-js-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.0.0-RC2"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-js/2.0.0-RC2/kotlin-test-wasm-js-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-js",
        "version": "2.0.0-RC2"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.0.0-RC2/kotlin-test-wasm-wasi-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.0.0-RC2"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.0.0-RC2/kotlin-test-wasm-wasi-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.0.0-RC2"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-test-wasm-wasi/2.0.0-RC2/kotlin-test-wasm-wasi-2.0.0-RC2.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-test-wasm-wasi",
        "version": "2.0.0-RC2"
      }
    }
  ]
}
