{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-common-deps",
    "version": "2.1.0-1.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.1.0-1.0.29.jar",
          "url": "symbol-processing-common-deps-2.1.0-1.0.29.jar",
          "size": 109757,
          "sha512": "547cb144b4edcb8cc3001cd997ac682b1b1e038888c2bb1a5d5e366b1eb9a73566fc19d48bfdfdf87544339078e8764198a7f1478e88d0304ea73132347a50dc",
          "sha256": "a74ff0e922fba5b27cd7ce49025c9ea4d73f824d2a3ac0c2697b39bc12da9b92",
          "sha1": "981907d8ef3d6d20c54bef09b51b5ae4b33e2f3b",
          "md5": "c8a5cbea7b57fe55939a00f344d19909"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.1.0-1.0.29.jar",
          "url": "symbol-processing-common-deps-2.1.0-1.0.29.jar",
          "size": 109757,
          "sha512": "547cb144b4edcb8cc3001cd997ac682b1b1e038888c2bb1a5d5e366b1eb9a73566fc19d48bfdfdf87544339078e8764198a7f1478e88d0304ea73132347a50dc",
          "sha256": "a74ff0e922fba5b27cd7ce49025c9ea4d73f824d2a3ac0c2697b39bc12da9b92",
          "sha1": "981907d8ef3d6d20c54bef09b51b5ae4b33e2f3b",
          "md5": "c8a5cbea7b57fe55939a00f344d19909"
        }
      ]
    }
  ]
}
