{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-core",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "datastore-preferences-core-1.1.0-alpha04-multiplatform-sources.jar",
          "url": "datastore-preferences-core-1.1.0-alpha04-multiplatform-sources.jar",
          "size": 21219,
          "sha512": "117616a28e033458bfc506360018e6d1271bd30470f5714a362661fc050baa11bc4d872f435046ae2615a12a58aa8d6681fbbed259f3f050c144a976d4597290",
          "sha256": "5c2cc14bdc25677a41e6d296da6fc4ba6ea70a0200296c6db09cc792ee05e979",
          "sha1": "0db95df3dbc6431cfa13b339a616f20e01530731",
          "md5": "b0670697b541f5896c6930b35362f7fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datastore-preferences-core-1.1.0-alpha04-sources.jar",
          "url": "datastore-preferences-core-1.1.0-alpha04-sources.jar",
          "size": 14392,
          "sha512": "02a0626116eb0563353987b773883443749a9ca5dd202a9fc8003f47171bc7e84477cb953f8873ee1f454ac8fbc1fbd4f8025e6eaef9959fdabc772475f3a825",
          "sha256": "cf189a68f6612bc76e92abfedda20c0eb73b13d5cc2fe8866c49230efd2ecebb",
          "sha1": "c6a2be3a30b81e290e9104a2fe225692ae1b2ef9",
          "md5": "edb39a9ed581315db7490378edbf1e8d"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-metadata-1.1.0-alpha04.jar",
          "url": "datastore-preferences-core-1.1.0-alpha04.jar",
          "size": 13094,
          "sha512": "df008e40bc39be01607b86f751d8bfbb75c823eb926c10f5bfa268c60360841698b478a8ea9d0b043d3ec5f72e3d9ba4dc77fcb22296c2542f27a27fc25a47d9",
          "sha256": "68008f690867528ae3bdacf845da49ed22bd27ef7f4ce6821ade4b65295fddf4",
          "sha1": "4e6b003f847973e51395e4c921cb29cc8ada6759",
          "md5": "c9357c38354da367c09a81d98e74d91c"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.1.0-alpha04/datastore-preferences-core-iosarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.1.0-alpha04/datastore-preferences-core-iosarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.1.0-alpha04/datastore-preferences-core-iossimulatorarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.1.0-alpha04/datastore-preferences-core-iossimulatorarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.1.0-alpha04/datastore-preferences-core-iosx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.1.0-alpha04/datastore-preferences-core-iosx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.1.0-alpha04/datastore-preferences-core-jvm-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.1.0-alpha04/datastore-preferences-core-jvm-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-linuxx64/1.1.0-alpha04/datastore-preferences-core-linuxx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-linuxx64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.1.0-alpha04/datastore-preferences-core-macosarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.1.0-alpha04/datastore-preferences-core-macosarm64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.1.0-alpha04/datastore-preferences-core-macosx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.1.0-alpha04"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.1.0-alpha04/datastore-preferences-core-macosx64-1.1.0-alpha04.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.1.0-alpha04"
      }
    }
  ]
}