{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-core",
    "version": "1.4.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-beta03-sources.jar",
          "url": "compose-material-core-1.4.0-beta03-sources.jar",
          "size": 31675,
          "sha512": "6acdf0201ead780bdd9b806d794ffdcddb602e30c181665c4fc3916ef393ac584f5ad7e1612c1026e62f7541aac8ffd7693c362463aa546bfcc16773532a9c8d",
          "sha256": "f6faf6ca7b8afc81cf9c335d9af1e9b29d68b7902fb46b5f48642ddbc962029c",
          "sha1": "6d37ecd388e7d48f80f88bb2f8a7181dda537bb6",
          "md5": "b73fa38094b95411832d632127f2c934"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-beta03.aar",
          "url": "compose-material-core-1.4.0-beta03.aar",
          "size": 168859,
          "sha512": "858113b74f3ba4c1b9b816e51a5b40a1cd24b18eb487d4e2c39562ad543062b214b81db2eba0d860e5181ba9077aaa5ba38a13d8f04ed26f621f554d9d334f9b",
          "sha256": "7109692707890c729864e27da7bd18bd296d4bdf54e6e7f9620fde35d3a09296",
          "sha1": "17a4c961d0fbfea7dd38c3e649055b52990e6494",
          "md5": "4a9c7ed959a541fb09da4fcfb19e7e10"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-beta03.aar",
          "url": "compose-material-core-1.4.0-beta03.aar",
          "size": 168859,
          "sha512": "858113b74f3ba4c1b9b816e51a5b40a1cd24b18eb487d4e2c39562ad543062b214b81db2eba0d860e5181ba9077aaa5ba38a13d8f04ed26f621f554d9d334f9b",
          "sha256": "7109692707890c729864e27da7bd18bd296d4bdf54e6e7f9620fde35d3a09296",
          "sha1": "17a4c961d0fbfea7dd38c3e649055b52990e6494",
          "md5": "4a9c7ed959a541fb09da4fcfb19e7e10"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-beta03-versionMetadata.json",
          "url": "compose-material-core-1.4.0-beta03-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}