{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.lint",
    "module": "lint",
    "version": "30.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.lint",
          "module": "lint-api",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-checks",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lint-30.1.0-alpha01.jar",
          "url": "lint-30.1.0-alpha01.jar",
          "size": 402441,
          "sha512": "25f72852ec994dbefaf36b54a49b788236d43832c8655bc113364b79a61daa786457f84a105993ad716159989484b07e50d3bb187fb845c5f8abe4ba64fd7b76",
          "sha256": "a610073ad913a1ede4533577b7752aa865146ef81c90cf5c95e1c9f825366585",
          "sha1": "fa8a7a26f41341d882357978bc32b9a3d2b7a05e",
          "md5": "047a09a38e2511f7b3b58ed06a757510"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.external.org-jetbrains",
          "module": "uast",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "kotlin-compiler",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.external.com-intellij",
          "module": "intellij-core",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-api",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-checks",
          "version": {
            "requires": "30.1.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lint-30.1.0-alpha01.jar",
          "url": "lint-30.1.0-alpha01.jar",
          "size": 402441,
          "sha512": "25f72852ec994dbefaf36b54a49b788236d43832c8655bc113364b79a61daa786457f84a105993ad716159989484b07e50d3bb187fb845c5f8abe4ba64fd7b76",
          "sha256": "a610073ad913a1ede4533577b7752aa865146ef81c90cf5c95e1c9f825366585",
          "sha1": "fa8a7a26f41341d882357978bc32b9a3d2b7a05e",
          "md5": "047a09a38e2511f7b3b58ed06a757510"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-30.1.0-alpha01-javadoc.jar",
          "url": "lint-30.1.0-alpha01-javadoc.jar",
          "size": 427530,
          "sha512": "efc0017b17bb4829e9ebc67e01919791be011ed1823845cd71e864ff6d5cd05ad3d86494b3abfbaee0df1acdfa6b8feef08498edc38e6995075cd6b2d652c6cf",
          "sha256": "a160c9f206491c48eb58c8fe44166205d271369a29b062265f49d9160ff31a81",
          "sha1": "b6247ab2d5b2625c2ab6079867bc10cef89da4c3",
          "md5": "2aaa64a0d79f9dc2b75022f9cb513c85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lint-30.1.0-alpha01-sources.jar",
          "url": "lint-30.1.0-alpha01-sources.jar",
          "size": 190970,
          "sha512": "4728d7ec1c368f27fb98f5b8f29500a410cf04b15363291751bc511405562199427dc6b7f3418b867ac9f98418b964886c9c3c595e6a25b93129e2d4273c4e0a",
          "sha256": "fd78fc0a6d81f838badc0ca835b9c8d2294d12c1e198c74cd9118be98abaedb3",
          "sha1": "453b8e904394a571b7c8a5aa99d6fcfd7b8bf7fd",
          "md5": "be76c45036971db0e814f25c8d2436a5"
        }
      ]
    }
  ]
}
