{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.2.0-Beta2/kotlin-test-2.2.0-Beta2.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.2.0-Beta2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "jvmJUnitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.2.0-Beta2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.2.0-Beta2.jar",
          "url": "kotlin-test-junit-2.2.0-Beta2.jar",
          "size": 5011,
          "sha512": "11ba7fb39be7d40431dd483ec6e4ff44c954e29a490cde698d46f0e8654e6c2f65185e19bc2364a18e5717f0a2bd2915bd6a6803d2df2901541fa2e0f571d138",
          "sha256": "df39ec4f6b531bbe93eb99448a6227a804bcd6abd04a89ace0c53c7a93dc55e0",
          "sha1": "72e7f2261a9e972d30a827b4693e63b9e98d6eb2",
          "md5": "4968bb44fd74f52b3bf49f46d3c6aeaa"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.2.0-Beta2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.0-Beta2"
        }
      ]
    },
    {
      "name": "jvmJUnitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.2.0-Beta2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.2.0-Beta2.jar",
          "url": "kotlin-test-junit-2.2.0-Beta2.jar",
          "size": 5011,
          "sha512": "11ba7fb39be7d40431dd483ec6e4ff44c954e29a490cde698d46f0e8654e6c2f65185e19bc2364a18e5717f0a2bd2915bd6a6803d2df2901541fa2e0f571d138",
          "sha256": "df39ec4f6b531bbe93eb99448a6227a804bcd6abd04a89ace0c53c7a93dc55e0",
          "sha1": "72e7f2261a9e972d30a827b4693e63b9e98d6eb2",
          "md5": "4968bb44fd74f52b3bf49f46d3c6aeaa"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.2.0-Beta2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.0-Beta2"
        }
      ]
    },
    {
      "name": "jvmJUnitSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-junit-2.2.0-Beta2-sources.jar",
          "url": "kotlin-test-junit-2.2.0-Beta2-sources.jar",
          "size": 2830,
          "sha512": "7e646d9971895dd20e122c2a51b0e062d0b03ef898e5886c17baa324ffdb651bf466b7169f828c3dd2f868145ae386f0520b0faa1b7017294742d07e4ebaa4b7",
          "sha256": "c411a0dad1218f3f652b6619f228fefee498903ee6e11c36c990fbc3fe823f18",
          "sha1": "48ca1b92544803c16b9042ae5b5976f6469e0a8c",
          "md5": "ff35307cfd380882a2b7a0d77f06e1b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.2.0-Beta2"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.0-Beta2"
        }
      ]
    }
  ]
}