load("//tools/adt/idea/studio:studio.bzl", "studio_data")

studio_data(
    name = "gemini_coder_prebuilts",
    files_linux = glob(["linux_amd64/*"]),
    files_mac = glob(["darwin_x86_64/*"]),
    files_mac_arm = glob(["darwin_arm64/*"]),
    files_win = glob(["windows/*"]),
    mappings = {
        "prebuilts/tools/common/gemini-coder/linux_amd64/": "bin/",
        "prebuilts/tools/common/gemini-coder/darwin_x86_64/": "bin/",
        "prebuilts/tools/common/gemini-coder/darwin_arm64/": "bin/",
        "prebuilts/tools/common/gemini-coder/windows/": "bin/",
    },
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gemini_coder_prebuilts_files",
    srcs = glob([
        "linux_amd64/*",
        "darwin_x86_64/*",
        "darwin_arm64/*",
        "windows/*",
    ]),
    visibility = ["//visibility:public"],
)
