load("//tools/adt/idea/studio:studio.bzl", "studio_data")

studio_data(
    name = "gemini_coder_prebuilts",
    files_linux = glob(["linux_x86_64/*"]),
    files_mac = glob(["darwin_x86_64/*"]),
    files_mac_arm = glob(["darwin_arm_64/*"]),
    files_win = glob(["windows_x86_64/*"]),
    mappings = {
        "prebuilts/tools/common/gemini-coder/linux_x86_64/": "bin/",
        "prebuilts/tools/common/gemini-coder/darwin_x86_64/": "bin/",
        "prebuilts/tools/common/gemini-coder/darwin_arm_64/": "bin/",
        "prebuilts/tools/common/gemini-coder/windows_x86_64/": "bin/",
    },
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gemini_coder_prebuilts_files",
    srcs = glob([
        "linux_x86_64/*",
        "darwin_x86_64/*",
        "darwin_arm_64/*",
        "windows_x86_64/*",
    ]),
    visibility = ["//visibility:public"],
)
