{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.1.1/animation-core-1.1.1.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.1.1.jar",
          "url": "animation-core-desktop-1.1.1.jar",
          "size": 299614,
          "sha512": "d2cd599a02ebe31b697c195302a26868c94abec206acf38fa7d178672cc321161aef6ea16f9d3e39fd3f710805852c34c6f601144d68d705fbe46a166a331060",
          "sha256": "138a6a3226ec444465b8a1c1907e07e02cfd6dec561c1f3119e841315df78252",
          "sha1": "35cb8857d549cceabc442af169cd3205cbe14555",
          "md5": "1ec13229368db6b6b4917b4e80d2fc5c"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.1.1.jar",
          "url": "animation-core-desktop-1.1.1.jar",
          "size": 299614,
          "sha512": "d2cd599a02ebe31b697c195302a26868c94abec206acf38fa7d178672cc321161aef6ea16f9d3e39fd3f710805852c34c6f601144d68d705fbe46a166a331060",
          "sha256": "138a6a3226ec444465b8a1c1907e07e02cfd6dec561c1f3119e841315df78252",
          "sha1": "35cb8857d549cceabc442af169cd3205cbe14555",
          "md5": "1ec13229368db6b6b4917b4e80d2fc5c"
        }
      ]
    }
  ]
}
