{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.5.11/ui-util-1.5.11.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-util",
    "version": "1.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-util-desktop-1.5.11.jar",
          "url": "ui-util-desktop-1.5.11.jar",
          "size": 6321,
          "sha512": "0ec7282a134fc746edddf0f204b26dcdd3100234c6faebba01a960e8b3561d7d8de2e248bf27f3af2d167708df1b23aa66964138ef2df8d436c43787d6ac69ee",
          "sha256": "d8dff32de582ed38a161453f9ae69eb07f0712ce093c478b209aef06023f4009",
          "sha1": "0b6cef817ffe7a8b7bba1ef34ded701f287cebf9",
          "md5": "9d7fac27cedddc1ab578bbf48372e777"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-desktop-1.5.11.jar",
          "url": "ui-util-desktop-1.5.11.jar",
          "size": 6321,
          "sha512": "0ec7282a134fc746edddf0f204b26dcdd3100234c6faebba01a960e8b3561d7d8de2e248bf27f3af2d167708df1b23aa66964138ef2df8d436c43787d6ac69ee",
          "sha256": "d8dff32de582ed38a161453f9ae69eb07f0712ce093c478b209aef06023f4009",
          "sha1": "0b6cef817ffe7a8b7bba1ef34ded701f287cebf9",
          "md5": "9d7fac27cedddc1ab578bbf48372e777"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-util-desktop-1.5.11-sources.jar",
          "url": "ui-util-desktop-1.5.11-sources.jar",
          "size": 4370,
          "sha512": "a345635bf2543c4e8d3917cf7f5bdc31bc6c952f2affb0109e2f3b37f7dbc8ae8fb7045d5ef91146b4eb98417a855ef00ec0a27651d0c49fc271094edfd5c501",
          "sha256": "cea877d7e3d74b36050a2c8ed1d265ecfdb5e1dc0a036f7c29437755b38465c8",
          "sha1": "5d7cde69db891fc0b6f9f5f0582fdefdcb990fbb",
          "md5": "6501e66a4ce899006f8f8a4a79531abb"
        }
      ]
    }
  ]
}