{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "fus-statistics-gradle-plugin",
    "version": "2.1.20-dev-8262",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-sources.jar",
          "size": 12788,
          "sha512": "6ae24c447d5b99c99b16f047e5d97abcd9bd542f4a8370767895e471f961afb8d1d6eee8c3c47ee586f7d0bcccb76305be5391d0dad6bab0fa156b7b8c00297f",
          "sha256": "5c2c585419be8e2978e220e842604af3d5ca6519db104213ac430427e02c61a8",
          "sha1": "63d49fc91838cd411c84c7e168d90e5211cfeb51",
          "md5": "04e9b417dc7201f3a6023c9e15cb2b04"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ]
    },
    {
      "name": "gradle80JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle80-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle80-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle80-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle80-sources.jar",
          "size": 12788,
          "sha512": "6ae24c447d5b99c99b16f047e5d97abcd9bd542f4a8370767895e471f961afb8d1d6eee8c3c47ee586f7d0bcccb76305be5391d0dad6bab0fa156b7b8c00297f",
          "sha256": "5c2c585419be8e2978e220e842604af3d5ca6519db104213ac430427e02c61a8",
          "sha1": "63d49fc91838cd411c84c7e168d90e5211cfeb51",
          "md5": "04e9b417dc7201f3a6023c9e15cb2b04"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle80.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle80.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle80.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle80.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle81JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle81-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle81-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle81-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle81-sources.jar",
          "size": 12788,
          "sha512": "6ae24c447d5b99c99b16f047e5d97abcd9bd542f4a8370767895e471f961afb8d1d6eee8c3c47ee586f7d0bcccb76305be5391d0dad6bab0fa156b7b8c00297f",
          "sha256": "5c2c585419be8e2978e220e842604af3d5ca6519db104213ac430427e02c61a8",
          "sha1": "63d49fc91838cd411c84c7e168d90e5211cfeb51",
          "md5": "04e9b417dc7201f3a6023c9e15cb2b04"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle81.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle81.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle81.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle81.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle82JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle82-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle82-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle82-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle82-sources.jar",
          "size": 12788,
          "sha512": "6ae24c447d5b99c99b16f047e5d97abcd9bd542f4a8370767895e471f961afb8d1d6eee8c3c47ee586f7d0bcccb76305be5391d0dad6bab0fa156b7b8c00297f",
          "sha256": "5c2c585419be8e2978e220e842604af3d5ca6519db104213ac430427e02c61a8",
          "sha1": "63d49fc91838cd411c84c7e168d90e5211cfeb51",
          "md5": "04e9b417dc7201f3a6023c9e15cb2b04"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle82.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle82.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle82.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle82.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle85JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle85-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle85-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle85-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle85-sources.jar",
          "size": 12788,
          "sha512": "6ae24c447d5b99c99b16f047e5d97abcd9bd542f4a8370767895e471f961afb8d1d6eee8c3c47ee586f7d0bcccb76305be5391d0dad6bab0fa156b7b8c00297f",
          "sha256": "5c2c585419be8e2978e220e842604af3d5ca6519db104213ac430427e02c61a8",
          "sha1": "63d49fc91838cd411c84c7e168d90e5211cfeb51",
          "md5": "04e9b417dc7201f3a6023c9e15cb2b04"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle85.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle85.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.20-dev-8262"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle85.jar",
          "url": "fus-statistics-gradle-plugin-2.1.20-dev-8262-gradle85.jar",
          "size": 60473,
          "sha512": "579cf705f101baa78e516104b00a6cb7100b03c2e5db263843fc1835409d30cb4754f5fdcdc0f8a5be11f39c3e42c96f2202372a7a4ac2f26607b06086e6568c",
          "sha256": "38bd1e26a2505b92f84aa0f329fdecc2287d7717d4d8c69a562e3b5143a5d2c0",
          "sha1": "9824e7b5f7c18b3d4ab18ebc7acf5959507847e3",
          "md5": "6bfabd6102abd867398cd0b69b920174"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.1.20-dev-8262"
        }
      ]
    }
  ]
}
