{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.6.1.aar",
          "url": "activity-ktx-1.6.1.aar",
          "size": 31962,
          "sha512": "189f9a36e52166ee07c70f98d18f030a81ac33c4c6719f3d6fe58116b9ca17b20e4fd16296680fbbe79824646463e4e10150ccaa46e401a99c4f96ae2ceabe50",
          "sha256": "0561745b3ddce53db491221b2b0cd3a44cadfb091b85e7831fd8be344f117d6e",
          "sha1": "bf390ee805b2d5e2eddd50aff0918e9d24c47e3e",
          "md5": "8c318fc2e959f79dda9fb40c304fd835"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.6.1.aar",
          "url": "activity-ktx-1.6.1.aar",
          "size": 31962,
          "sha512": "189f9a36e52166ee07c70f98d18f030a81ac33c4c6719f3d6fe58116b9ca17b20e4fd16296680fbbe79824646463e4e10150ccaa46e401a99c4f96ae2ceabe50",
          "sha256": "0561745b3ddce53db491221b2b0cd3a44cadfb091b85e7831fd8be344f117d6e",
          "sha1": "bf390ee805b2d5e2eddd50aff0918e9d24c47e3e",
          "md5": "8c318fc2e959f79dda9fb40c304fd835"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.6.1-sources.jar",
          "url": "activity-ktx-1.6.1-sources.jar",
          "size": 7896,
          "sha512": "410bbd1a10f608fdc92ce2597cac6d8e8bc24c7c2a3de296016e04106298d0df3108cc767b661b869d7160403664b806051b2023a4359afa72f5de366d6660ae",
          "sha256": "89dd07b2ecd1e7678fcee8a3cde667ae51f251c88b3bce5ea8298662c118c909",
          "sha1": "919ce22f7ced37bb707da496c1852fa8a30b6571",
          "md5": "2086f53f293836c195e19cf368e671f1"
        }
      ]
    }
  ]
}