{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-metadata-0.7.7-all.jar",
          "url": "skiko-0.7.7-all.jar",
          "size": 106865,
          "sha512": "46bf12f42d13efdd59c36e0313169a99aa98ea2373d21ab598a26d2e1a9584a67fb74143e19442d69be5d893f6f8aad6fbc40928963854ee425bac5df84cc904",
          "sha256": "c0c39f941138dd193676a3b1c28b8a36b7433ec760b979c69699241bdecee4cb",
          "sha1": "082d0c2d279976bbc8b2acee4f53c646fe7c98be",
          "md5": "9a63cb1bc9b28814308102fcfcd4a0f3"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "skiko-0.7.7.jar",
          "url": "skiko-0.7.7.jar",
          "size": 182093,
          "sha512": "65e9349dd5877ff98d2750aaa6448460f23e9d0e71bfb223317e1f6f822c2385a3131ed05be80170df35e878d89048614036026b938d763e0a1ecf03a59eae8f",
          "sha256": "82a83c38a61d1212eab92605bb5c4714f683d57ffc2ca27e4b8430fe8f4f1aed",
          "sha1": "d552fd69570f8e1a1503d1992305283e792131b4",
          "md5": "d6c7f62a5ff7b1a4c97c7abf43aa3344"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "ui": "android"
      },
      "available-at": {
        "url": "../../skiko-android/0.7.7/skiko-android-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-android",
        "version": "0.7.7"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm",
        "ui": "android"
      },
      "available-at": {
        "url": "../../skiko-android/0.7.7/skiko-android-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-android",
        "version": "0.7.7"
      }
    },
    {
      "name": "awtApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.7/skiko-awt-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.7"
      }
    },
    {
      "name": "awtRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.7/skiko-awt-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.7"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-iosarm64/0.7.7/skiko-iosarm64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-iosarm64",
        "version": "0.7.7"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-iosarm64/0.7.7/skiko-iosarm64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-iosarm64",
        "version": "0.7.7"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-iosx64/0.7.7/skiko-iosx64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-iosx64",
        "version": "0.7.7"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-iosx64/0.7.7/skiko-iosx64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-iosx64",
        "version": "0.7.7"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../skiko-js/0.7.7/skiko-js-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-js",
        "version": "0.7.7"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../skiko-js/0.7.7/skiko-js-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-js",
        "version": "0.7.7"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-linuxx64/0.7.7/skiko-linuxx64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-linuxx64",
        "version": "0.7.7"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-macosarm64/0.7.7/skiko-macosarm64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-macosarm64",
        "version": "0.7.7"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-macosarm64/0.7.7/skiko-macosarm64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-macosarm64",
        "version": "0.7.7"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-macosx64/0.7.7/skiko-macosx64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-macosx64",
        "version": "0.7.7"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../skiko-macosx64/0.7.7/skiko-macosx64-0.7.7.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-macosx64",
        "version": "0.7.7"
      }
    }
  ]
}
