{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles-renderer",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-renderer-1.4.0-beta01-sources.jar",
          "url": "tiles-renderer-1.4.0-beta01-sources.jar",
          "size": 33217,
          "sha512": "f6090a145934a15f46f23734c22388af0c1c51469700caa50ae42664ff5958974722e36c5730a42609c633c2bf6fdc540f9613a006cbb7f84c1ad8179b8c14dc",
          "sha256": "4650eb37308ceb8e7ae96ab8e4d654a119067866b50d4d64ff60cb97f4b76cc8",
          "sha1": "e32ffbb30a32abf5cb9e3eb7d7626f35198ee127",
          "md5": "af6f522660623e37d7356383e296ad69"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-renderer-1.4.0-beta01.aar",
          "url": "tiles-renderer-1.4.0-beta01.aar",
          "size": 104186,
          "sha512": "13ccca144ee191842464a730d99ef9f77b414726abc3a009c12cba2d08bbf8f2d004b8fe49e2029c7ffcce65a511d12fadbbc1c0e59ebd936a57e73687b7e858",
          "sha256": "f6182f1088558898d8c80ff566f34e1ebf87102435c597a571e06b41690a8dbe",
          "sha1": "65f539f19b81aa4e321323df92d85cc7e93c1800",
          "md5": "e9f6f91209b4f3cbf92638344c979c07"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-renderer-1.4.0-beta01.aar",
          "url": "tiles-renderer-1.4.0-beta01.aar",
          "size": 104186,
          "sha512": "13ccca144ee191842464a730d99ef9f77b414726abc3a009c12cba2d08bbf8f2d004b8fe49e2029c7ffcce65a511d12fadbbc1c0e59ebd936a57e73687b7e858",
          "sha256": "f6182f1088558898d8c80ff566f34e1ebf87102435c597a571e06b41690a8dbe",
          "sha1": "65f539f19b81aa4e321323df92d85cc7e93c1800",
          "md5": "e9f6f91209b4f3cbf92638344c979c07"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "tiles-renderer is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-renderer-1.4.0-beta01-versionMetadata.json",
          "url": "tiles-renderer-1.4.0-beta01-versionMetadata.json",
          "size": 6653,
          "sha512": "8ae136a1d715001dc664921a56fa4ad22f4185f19a4d1d7ab1aa20c38a545a529da710e69fd3611caa06c041867eed37204c1ce155c3d7651eb66eec82b4183c",
          "sha256": "44da28fd4872d5097468c73a9726b3172395c0bbfb16f7745de1e97e1081379d",
          "sha1": "4301e5f640ca53d7144335cace6609a3aca584c2",
          "md5": "1d65c9eefab189aab55ca9b2e2fb3689"
        }
      ]
    }
  ]
}