{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.metalava",
    "module": "metalava-model-text",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "buildId:": "14553263",
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "metalava-model-text-1.0.0-alpha14.jar",
          "url": "metalava-model-text-1.0.0-alpha14.jar",
          "size": 167406,
          "sha512": "fcc932bae3d8d6b6a4b108ed5385cb00e3358a4a13e3834f0d1d17252a722401430cd1b2de04eed73636ac64c7ebb91f43ac0d6b3fa491449e71c0379bfea2a4",
          "sha256": "732fa0cb0aa85987e2e39e27c09efff45325b2117fd62151f0fe466fcce2242c",
          "sha1": "459237956103331d413a8710f16ccd993ce27499",
          "md5": "f11faf5f975aac822d92413a5440060a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.metalava",
          "module": "metalava-model",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.android.tools.metalava",
          "module": "metalava-reporter",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "metalava-model-text-1.0.0-alpha14.jar",
          "url": "metalava-model-text-1.0.0-alpha14.jar",
          "size": 167406,
          "sha512": "fcc932bae3d8d6b6a4b108ed5385cb00e3358a4a13e3834f0d1d17252a722401430cd1b2de04eed73636ac64c7ebb91f43ac0d6b3fa491449e71c0379bfea2a4",
          "sha256": "732fa0cb0aa85987e2e39e27c09efff45325b2117fd62151f0fe466fcce2242c",
          "sha1": "459237956103331d413a8710f16ccd993ce27499",
          "md5": "f11faf5f975aac822d92413a5440060a"
        }
      ]
    }
  ]
}
