{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-ide-laf-bridge-243",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-243",
          "version": {
            "requires": "0.27.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jewel-ide-laf-bridge-243-0.27.0.jar",
          "url": "jewel-ide-laf-bridge-243-0.27.0.jar",
          "size": 207195,
          "sha512": "d243af2c656f7188cf4d59900ba79e5bbc305d79cc84dcf156cd438e24e76d2afe48654473f58a85a33d45e474df7b8c6273ba881e35a673cc5e2252244ba492",
          "sha256": "b2b988104d5cfb8d3c185e588d73bdb75bb1beea0f74994a7f01e1bbb427d085",
          "sha1": "e98ee0898bb083d8b787162f82af62887602e8a4",
          "md5": "2ee75a6dcbf7b85ad0906fe5ffda9037"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-243",
          "version": {
            "requires": "0.27.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jewel-ide-laf-bridge-243-0.27.0.jar",
          "url": "jewel-ide-laf-bridge-243-0.27.0.jar",
          "size": 207195,
          "sha512": "d243af2c656f7188cf4d59900ba79e5bbc305d79cc84dcf156cd438e24e76d2afe48654473f58a85a33d45e474df7b8c6273ba881e35a673cc5e2252244ba492",
          "sha256": "b2b988104d5cfb8d3c185e588d73bdb75bb1beea0f74994a7f01e1bbb427d085",
          "sha1": "e98ee0898bb083d8b787162f82af62887602e8a4",
          "md5": "2ee75a6dcbf7b85ad0906fe5ffda9037"
        }
      ]
    }
  ]
}
