{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle",
    "module": "gradle-tooling-api",
    "version": "9.5.0-milestone-5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-milestone-4"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-tooling-api-9.5.0-milestone-5-sources.jar",
          "url": "gradle-tooling-api-9.5.0-milestone-5-sources.jar",
          "size": 6461797,
          "sha512": "703588b83119be719da7e30c1e42448f002a2841b48d907cca8f805bfa5c4adf3daa74ad73963441ea06b68400f79144ed9542ca6843cf7c36802984d5a8514b",
          "sha256": "c5c1c236a2085861e0743bbd632803db61b1eeb28b6df3bae90b4d987fb4cbdb",
          "sha1": "34766d86d34780bb6e08e2c0501c1c7f06e67702",
          "md5": "2d7ea6b117fc9370d9b329d9d940a043"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-tooling-api-9.5.0-milestone-5-javadoc.jar",
          "url": "gradle-tooling-api-9.5.0-milestone-5-javadoc.jar",
          "size": 1994015,
          "sha512": "b29387e3a921cdd2c61a20d00ce7fd6e3b469300242c0fb84c603feaf553dae802f4ffffa7adef05445dbd6dfc7d518026f237f25233e193c1dfffdbbe4c2644",
          "sha256": "d6e6bdd481b8c4114ae4e56fc280862303392818f24f8185da518d130d3712b4",
          "sha1": "8006dd4d5773d1e74f9f8b9da2bbdef6299b12f3",
          "md5": "b76e37b7831c321e24592a994318e924"
        }
      ]
    },
    {
      "name": "shadedRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "strictly": "2.0.17",
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "gradle-tooling-api-9.5.0-milestone-5.jar",
          "url": "gradle-tooling-api-9.5.0-milestone-5.jar",
          "size": 3054994,
          "sha512": "ee55ac3f6951f5d76a4725e97d19d850269512943f456a71e4e6bbc41b0df4e7d7d2561f3ab11937244445c7837d482c483d4dbc6b143e73c8b63ea49e8a7e70",
          "sha256": "0567ffa484e00b46add0b02a4fb97f9903644e94d5ab339998d10dd6afa490bf",
          "sha1": "e196a9a7fcea4a31a2d0629e8cddc156e28eb545",
          "md5": "63a63b5cf91cd8a3cab6f725b6a61aed"
        }
      ]
    }
  ]
}
