{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.3.3.aar",
          "url": "ui-text-1.3.3.aar",
          "size": 725521,
          "sha512": "cf1484d059979742d3f1c993a1b19107dcc4dd4c436e529da35db5ffbd916bfd88dc1e2bf4d2b05b545cbea06745b8218156bef2b39f1592824762c524f56254",
          "sha256": "89f186445ba99f74964b1fd13c1673e288b5e4b74e6392c43297d4e406332c38",
          "sha1": "5ef21fd21ff9691bd431eabe26c92654ad6d2a9e",
          "md5": "64cfff744b88b963463d1ffaab4bae60"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.3.3.aar",
          "url": "ui-text-1.3.3.aar",
          "size": 725521,
          "sha512": "cf1484d059979742d3f1c993a1b19107dcc4dd4c436e529da35db5ffbd916bfd88dc1e2bf4d2b05b545cbea06745b8218156bef2b39f1592824762c524f56254",
          "sha256": "89f186445ba99f74964b1fd13c1673e288b5e4b74e6392c43297d4e406332c38",
          "sha1": "5ef21fd21ff9691bd431eabe26c92654ad6d2a9e",
          "md5": "64cfff744b88b963463d1ffaab4bae60"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-1.3.3-sources.jar",
          "url": "ui-text-1.3.3-sources.jar",
          "size": 279049,
          "sha512": "446d2ef086c7deb0cb2bce76197618dd68e8743ea7861ddc294d0a2b369193af85a0f539cfc0938ddd32e2c33fbbf30d1200badf8c3f5ee9e23e8ce68da5e62e",
          "sha256": "7a7cbf95f3111765ff0931e6dbd273e7b3e53b1f89261d227fdcf6f337d13409",
          "sha1": "4bd8e4a4623e32f65300ad6a46145a38ced1a125",
          "md5": "99c372bc00dbad27c1471521c99b2c37"
        }
      ]
    }
  ]
}