{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent/1.0.2/navigationevent-1.0.2.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14757970"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-desktop-1.0.2.jar",
          "url": "navigationevent-desktop-1.0.2.jar",
          "size": 41775,
          "sha512": "1747d03e468e083547aa45cb1d5ef0a8685ad651a005fd169d63ab919d403525bc7eb737bf426e6c4c6d464ce95ce925016b29e1677b30dace6bc030dad3971a",
          "sha256": "43deeb5774fd737fa945e09a47f93b6f1a508d17fac8f3b65f1c863e7f7d0660",
          "sha1": "0ddb1e7fe97ed51c3d35bba493f97fcf12398719",
          "md5": "e0291c4f5d6a6b9038dae1d32950806e"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-desktop-1.0.2.jar",
          "url": "navigationevent-desktop-1.0.2.jar",
          "size": 41775,
          "sha512": "1747d03e468e083547aa45cb1d5ef0a8685ad651a005fd169d63ab919d403525bc7eb737bf426e6c4c6d464ce95ce925016b29e1677b30dace6bc030dad3971a",
          "sha256": "43deeb5774fd737fa945e09a47f93b6f1a508d17fac8f3b65f1c863e7f7d0660",
          "sha1": "0ddb1e7fe97ed51c3d35bba493f97fcf12398719",
          "md5": "e0291c4f5d6a6b9038dae1d32950806e"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-desktop-1.0.2-sources.jar",
          "url": "navigationevent-desktop-1.0.2-sources.jar",
          "size": 36861,
          "sha512": "14f2a9f7ddccfaedf8df2105151f3c233314e8982ba73e5aac081b8b87d2628da9a44559b853cfa42604fc3b017e1ea929b7fe32c15432ce00c1b5404973b6d6",
          "sha256": "8ac6df68a24c80bbf5cbd7550ce30581a1d1f7cb35b54a7c707bd2583c6e70ec",
          "sha1": "4a1dd6c564d43a5a81d3ab218726fba309aff76e",
          "md5": "0672ca9c82fb1482a0c210d88d773226"
        }
      ]
    }
  ]
}