{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.6.20-dev1663/foundation-1.6.20-dev1663.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation",
    "version": "1.6.20-dev1663",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.6.20-dev1663.jar",
          "url": "foundation-desktop-1.6.20-dev1663.jar",
          "size": 4003512,
          "sha512": "c25b6868d2f857a46c89e7575cb8079ed66f89c337a643a0e6ddf2adc107dc6e208be0c51f9745355e76c3b9cc68ad8b3b108a84ee42367e5939e12f7e5cdda3",
          "sha256": "f919ac56da271429dcaf2f201c8c9bf67bcc48231967cdc6b6b0f49d6da3a580",
          "sha1": "f21857cd9abc9bd7522b0683f023604efa525508",
          "md5": "86a449fc04dfc8964f9b0f6fb0e2b270"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.6.20-dev1663.jar",
          "url": "foundation-desktop-1.6.20-dev1663.jar",
          "size": 4003512,
          "sha512": "c25b6868d2f857a46c89e7575cb8079ed66f89c337a643a0e6ddf2adc107dc6e208be0c51f9745355e76c3b9cc68ad8b3b108a84ee42367e5939e12f7e5cdda3",
          "sha256": "f919ac56da271429dcaf2f201c8c9bf67bcc48231967cdc6b6b0f49d6da3a580",
          "sha1": "f21857cd9abc9bd7522b0683f023604efa525508",
          "md5": "86a449fc04dfc8964f9b0f6fb0e2b270"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "foundation-desktop-1.6.20-dev1663-sources.jar",
          "url": "foundation-desktop-1.6.20-dev1663-sources.jar",
          "size": 774465,
          "sha512": "241eb8464e759ea37d1e9d9f56f4a880f0e3bb80b71d247439903d238231916a149a07f1eb1ba2510ab39cc45de9a685900214c3a2e743f224d1862efd39d32d",
          "sha256": "8240305639db02651c6084dbc158c5939b0ace422282d42fe1ebcbbfc15836f2",
          "sha1": "dcfce79deb11bacd74a781de4e045656c4a762cb",
          "md5": "331170fa5bab56c0df81f232eba2ced8"
        }
      ]
    }
  ]
}