{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-preview/1.8.0-alpha06/ui-tooling-preview-1.8.0-alpha06.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.8.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview.aar",
          "url": "ui-tooling-preview-android-1.8.0-alpha06.aar",
          "size": 21494,
          "sha512": "18988ef3d554e34e9465826d9f50d894c4f9e31b96566337b8d3b286ea0fe84a7eb4eb759d4b56bfbdbe1341a1142e38e57d7602282087150b8c14a8205dcd9c",
          "sha256": "991f0564fabdf39520ce13ebe5430ef9acc41cbd11bb9bf13c1d07ac5716a16d",
          "sha1": "0eb1421093c77531b208b97a6342396a1f199e3b",
          "md5": "6870c2389cd5dffa481adcda1f234ad9"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview.aar",
          "url": "ui-tooling-preview-android-1.8.0-alpha06.aar",
          "size": 21494,
          "sha512": "18988ef3d554e34e9465826d9f50d894c4f9e31b96566337b8d3b286ea0fe84a7eb4eb759d4b56bfbdbe1341a1142e38e57d7602282087150b8c14a8205dcd9c",
          "sha256": "991f0564fabdf39520ce13ebe5430ef9acc41cbd11bb9bf13c1d07ac5716a16d",
          "sha1": "0eb1421093c77531b208b97a6342396a1f199e3b",
          "md5": "6870c2389cd5dffa481adcda1f234ad9"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-android-1.8.0-alpha06-sources.jar",
          "url": "ui-tooling-preview-android-1.8.0-alpha06-sources.jar",
          "size": 15735,
          "sha512": "6acd9bb0bf2f09fe3c6e088226d31540ca0b6169499e3c3b8ae8ca61838453845b86d852dcb7e268055c2f44698a14236f38720c01a677bd717a76b47ee54f33",
          "sha256": "d1d4163e64f71894b25bc65bc293e16face6da7092a22e3e0e232f532caad6b5",
          "sha1": "91a217bec6e6cf647f981ddf0d949d8272b0119c",
          "md5": "10d5d242d312674e702ceebf1be90cf0"
        }
      ]
    }
  ]
}