{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13556420"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.5.0-sources.jar",
          "url": "tiles-1.5.0-sources.jar",
          "size": 79183,
          "sha512": "ad95655a77f39bab3d1dcbb34259c79feafbb3162a634385653f14e38a0474857410f3d1477a15d1d160ccac49628cd365e6b2279f4f6c1b6b7dc2174b585ce8",
          "sha256": "b05b1e677cbff3aa819ec2199d4ad500af5b085218ba372af6e7ed9a508314ec",
          "sha1": "c703fbc3dd9c7c5239ed647d9ca59bb6c86f8ac0",
          "md5": "535e2002f3c4d75edb2b886935548971"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.5.0.aar",
          "url": "tiles-1.5.0.aar",
          "size": 285535,
          "sha512": "05d5123e6ab6cfbc2691e78ddf7f18210d28943c0341b45adc03e0c3266cd5ec90eb7acce69061ed14c472f783fd9230cda0eb22691fe4c82ffb89232c9477f5",
          "sha256": "eac5238833d6cea0a2ce27c236b34f921536687179febc30766eb3cd9329569f",
          "sha1": "9d35878fe5ed3bce54d91e177beebd4bd7ad2df5",
          "md5": "45d2ff12592c1f1cdb43420d47a6ed4a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.5.0.aar",
          "url": "tiles-1.5.0.aar",
          "size": 285535,
          "sha512": "05d5123e6ab6cfbc2691e78ddf7f18210d28943c0341b45adc03e0c3266cd5ec90eb7acce69061ed14c472f783fd9230cda0eb22691fe4c82ffb89232c9477f5",
          "sha256": "eac5238833d6cea0a2ce27c236b34f921536687179febc30766eb3cd9329569f",
          "sha1": "9d35878fe5ed3bce54d91e177beebd4bd7ad2df5",
          "md5": "45d2ff12592c1f1cdb43420d47a6ed4a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.5.0"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.5.0-versionMetadata.json",
          "url": "tiles-1.5.0-versionMetadata.json",
          "size": 68694,
          "sha512": "2be4da1d697f5d8c6e9de9498943b40d6d8b7c865446d1c2cd9f369e700c23e6117d412314174cb26eff525d89bd62c0300a4931db834d9e600cadbe5eb1e9d1",
          "sha256": "0c755237bbfafd0c2d59686dfb10029e70886d07f1c66b6d7ab00b37ea59faa4",
          "sha1": "5a31010f5190edfb504237a289e70039fdd87934",
          "md5": "6a29243ef835dc833cf661b4d5b78416"
        }
      ]
    }
  ]
}