#!/usr/bin/env bash
set -eu

export WORKSPACE="$(cd "$(dirname "$0")"/../../../.. && pwd)"

# Check that the WORKSPACE file is actually there.
test -f "${WORKSPACE}/WORKSPACE"

echo "Found WORKSPACE root: ${WORKSPACE}"

# This file builds and assembles Lint's dependencies (IntelliJ/Kotlin/UAST).
# Consult the README for details.

# These versions should generally be updated to match what we use in Android Studio.
# The git SHAs must also be updated to match the versions specified.

# IntelliJ: See [tools/idea/build.txt](file://./../../../../tools/idea/build.txt)
# IntelliJ 2026.1
# https://github.com/JetBrains/intellij-community/tree/idea/261.22158.277
# https://github.com/JetBrains/intellij-community/commit/088fc74da710f5a4dc177b4ca539e11b669959f7
export INTELLIJ_VERSION="261.22158.277"
export INTELLIJ_SHA="088fc74da710f5a4dc177b4ca539e11b669959f7"

# Kotlin: see [tools/idea/.idea/libraries/kotlinc_*.xml](file://./../../../../tools/idea/.idea/libraries/kotlinc_analysis_api.xml).
# https://github.com/JetBrains/kotlin/tree/build-2.4.0-dev-2631
# https://github.com/JetBrains/kotlin/commit/a43a9ee67b63df8d52989824d119b6fe9bad42dd
export KOTLIN_VERSION="2.4.0-dev-2631"
export KOTLIN_SHA="a43a9ee67b63df8d52989824d119b6fe9bad42dd"

export CLEAN_BUILD="${CLEAN_BUILD:-false}"

export LINT_PSI_DIR="${WORKSPACE}/prebuilts/tools/common/lint-psi"
export KOTLIN_DIR="${CUSTOM_KOTLIN_DIR:-$LINT_PSI_DIR/dependency-source-checkouts/kotlin}"
export INTELLIJ_DIR="${CUSTOM_INTELLIJ_DIR:-$LINT_PSI_DIR/dependency-source-checkouts/intellij}"

JAR_REWRITER_DIR="${LINT_PSI_DIR}/jarrewriter"

INTELLIJ_REMOTE="git@github.com:JetBrains/intellij-community.git"
KOTLIN_REMOTE="git@github.com:JetBrains/kotlin.git"

phase() {
    echo -e "\n=== $1 ===\n"
}

fetch_git_repo() {
    local DIR="$1"; local REMOTE="$2"; local REF="$3"
    git init "$DIR"
    git -C "$DIR" fetch --filter=blob:none "$REMOTE" "$REF"
    git -C "$DIR" checkout -f FETCH_HEAD
    git -C "$DIR" clean -fd
}

cd "${WORKSPACE}"

# Forbid clean builds with custom repos, to avoid clobbering user files.
if [[ "$CLEAN_BUILD" = "true" && ( "${CUSTOM_KOTLIN_DIR:-}" || "${CUSTOM_INTELLIJ_DIR:-}" ) ]]; then
    echo "ERROR: clean builds are not supported when using custom dependency repositories"
    exit 1
fi

phase "Fetching dependency sources if needed"
if [[ ! "${CUSTOM_KOTLIN_DIR:-}" ]]; then fetch_git_repo "$KOTLIN_DIR" "$KOTLIN_REMOTE" "$KOTLIN_SHA"; fi
if [[ ! "${CUSTOM_INTELLIJ_DIR:-}" ]]; then fetch_git_repo "$INTELLIJ_DIR" "$INTELLIJ_REMOTE" "$INTELLIJ_SHA"; fi

GRADLE_CLEAN_FLAGS=()
if [[ "$CLEAN_BUILD" = "true" ]]; then
    phase "Cleaning outputs"
    rm -rf "$LINT_PSI_DIR/build"
    git -C "$KOTLIN_DIR" clean -fdx
    git -C "$INTELLIJ_DIR" clean -fdx
    GRADLE_CLEAN_FLAGS+=(clean --no-daemon --no-build-cache)
fi

phase "Applying patches"
if [[ ! "${CUSTOM_KOTLIN_DIR:-}" ]]; then
    git -C "$KOTLIN_DIR" am "$LINT_PSI_DIR"/kotlin-patches/*.patch
fi

if [[ ! "${CUSTOM_INTELLIJ_DIR:-}" ]]; then
    git -C "$INTELLIJ_DIR" am "$LINT_PSI_DIR"/intellij-patches/*.patch
fi

phase "Building Kotlin compiler"
# This command is inspired by JetBrains/intellij-community/.idea/runConfigurations/Publish_compiler_for_ide_jars.xml
# which is itself generated by JetBrains/intellij-community/plugins/kotlin/util/project-model-updater.
# Note: the Kotlin compiler will auto-detect installed JDKs that can be used for building.
# We use -Pkotlin.build.isObsoleteJdkOverrideEnabled=true to avoid the need for JDK 1.6.
# We use -Dorg.gradle.dependency.verification=off because the build otherwise fails (if outside JetBrains CI environment?)
# We use -Pkotlin.build.jar.compression=true to ensure reasonable jar sizes.
# Additional options to investigate: isTeamcityBuild, kotlin.build.proguard, BuildPropertiesExt.kt, etc.
"$KOTLIN_DIR/gradlew" -p "$KOTLIN_DIR" \
    ${GRADLE_CLEAN_FLAGS[@]+"${GRADLE_CLEAN_FLAGS[@]}"} \
    publishIdeArtifacts \
    -PdeployVersion="$KOTLIN_VERSION-for-lint" \
    -Ppublish.ide.plugin.dependencies=true \
    -Pkotlin.build.isObsoleteJdkOverrideEnabled=true \
    -Pkotlin.build.jar.compression=true \
    -Dorg.gradle.dependency.verification=off

phase "Building IntelliJ modules"
pushd "$INTELLIJ_DIR"
./bazel.cmd build \
	//android-lint-deps:intellij-core_deploy.jar \
	//android-lint-deps:intellij-core_deploy-src.jar \
	//android-lint-deps:uast_deploy.jar \
	//android-lint-deps:uast_deploy-src.jar
popd

phase "Packaging Kotlin compiler jars"
"$WORKSPACE/tools/gradlew" -p "$LINT_PSI_DIR" ${GRADLE_CLEAN_FLAGS[@]+"${GRADLE_CLEAN_FLAGS[@]}"} assemble

phase "Copying artifacts to prebuilts"
cp "$INTELLIJ_DIR/out/bazel-bin/android-lint-deps/intellij-core_deploy.jar" "$LINT_PSI_DIR/intellij-core/intellij-core.jar"
cp "$INTELLIJ_DIR/out/bazel-bin/android-lint-deps/intellij-core_deploy-src.jar" "$LINT_PSI_DIR/intellij-core/intellij-core-sources.jar"
cp "$INTELLIJ_DIR/out/bazel-bin/android-lint-deps/uast_deploy.jar" "$LINT_PSI_DIR/uast/uast.jar"
cp "$INTELLIJ_DIR/out/bazel-bin/android-lint-deps/uast_deploy-src.jar" "$LINT_PSI_DIR/uast/uast-sources.jar"
cp "$LINT_PSI_DIR"/build/libs/kotlin-compiler{,-sources}.jar "$LINT_PSI_DIR/kotlin-compiler/"
cp "$LINT_PSI_DIR"/build/versions.txt "$LINT_PSI_DIR/"

phase "Rewriting kotlin-compiler.jar"
rm -f "${LINT_PSI_DIR}/kotlin-compiler/kotlin-compiler-before-rewrite.jar"
mv "${LINT_PSI_DIR}/kotlin-compiler/kotlin-compiler.jar" "${LINT_PSI_DIR}/kotlin-compiler/kotlin-compiler-before-rewrite.jar"
"${KOTLIN_DIR}/gradlew" -p "${JAR_REWRITER_DIR}" rewriteType "-PinputJarPath=${LINT_PSI_DIR}/kotlin-compiler/kotlin-compiler-before-rewrite.jar" "-PoutputJarPath=${LINT_PSI_DIR}/kotlin-compiler/kotlin-compiler.jar"

phase "Done"
