{
  "formatVersion": "1.1",
  "component": {
    "group": "com.anthropic",
    "module": "anthropic-java-core",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "anthropic-java-core-2.8.1.jar",
          "url": "anthropic-java-core-2.8.1.jar",
          "size": 6087170,
          "sha512": "c6b745c4bcbc214bbbf7efd34962e23255dbeca4be5226a68edc16c210504562e58c13ddd18e3caa1949024c038acaf4564e4e7d5e71c5fec1cb5f6c23d92f13",
          "sha256": "0420b2003d420aa1e683a67ca5c9543faa2a9ee268b8ce3a344e5b570b6420f6",
          "sha1": "2ffc8f769e1961c0df52fcf135a045e1835c358f",
          "md5": "20fc35d1e26b76ca670b2a0f7fe553b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "org.apache.httpcomponents.core5",
          "module": "httpcore5",
          "version": {
            "requires": "5.2.4"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.33.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "anthropic-java-core-2.8.1.jar",
          "url": "anthropic-java-core-2.8.1.jar",
          "size": 6087170,
          "sha512": "c6b745c4bcbc214bbbf7efd34962e23255dbeca4be5226a68edc16c210504562e58c13ddd18e3caa1949024c038acaf4564e4e7d5e71c5fec1cb5f6c23d92f13",
          "sha256": "0420b2003d420aa1e683a67ca5c9543faa2a9ee268b8ce3a344e5b570b6420f6",
          "sha1": "2ffc8f769e1961c0df52fcf135a045e1835c358f",
          "md5": "20fc35d1e26b76ca670b2a0f7fe553b7"
        }
      ]
    }
  ]
}
