{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler-hosted",
    "version": "1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6841119"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compiler-hosted-1.0.0-alpha04.jar",
          "url": "compiler-hosted-1.0.0-alpha04.jar",
          "size": 435343,
          "sha512": "04a523c9795f6d15427d8b4e764197f2aae4734f4e6d06af4ee7a6c4741a137f74e668328428a43fa770cf41aad89e234976b3955a77344a8ef5c9c6add4c9cc",
          "sha256": "69e4bfc3ba1e812c4b9bb08fefecf9dad25626603e84184b984d9af206be2b22",
          "sha1": "26436afcdd560c02823abf95069cac15c2013c73",
          "md5": "e38254557086d9609a7bf4aaad5caecf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compiler-hosted-1.0.0-alpha04.jar",
          "url": "compiler-hosted-1.0.0-alpha04.jar",
          "size": 435343,
          "sha512": "04a523c9795f6d15427d8b4e764197f2aae4734f4e6d06af4ee7a6c4741a137f74e668328428a43fa770cf41aad89e234976b3955a77344a8ef5c9c6add4c9cc",
          "sha256": "69e4bfc3ba1e812c4b9bb08fefecf9dad25626603e84184b984d9af206be2b22",
          "sha1": "26436afcdd560c02823abf95069cac15c2013c73",
          "md5": "e38254557086d9609a7bf4aaad5caecf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-hosted-1.0.0-alpha04-sources.jar",
          "url": "compiler-hosted-1.0.0-alpha04-sources.jar",
          "size": 103236,
          "sha512": "b22057e04d4f4ce14f981bcbb65a5cf380486e3c941c4f884360387bcd55b3be44dbd54cfadacf8390ef8d5fc5fc1f6b232d571b84883068c57645fbb817c912",
          "sha256": "90fe555a2053ac6f363a9d5440762980448e7d3cf9ec202db7a60bff4330a015",
          "sha1": "9b78506b86f9d93e8deae06de50338e8ec3ecbb4",
          "md5": "64238567301b3ef9b2b316024aa2f15e"
        }
      ]
    }
  ]
}
