{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-markdown-core-242",
    "version": "0.22.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-242",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.22.0"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-core-242-0.22.1.jar",
          "url": "jewel-markdown-core-242-0.22.1.jar",
          "size": 296453,
          "sha512": "cb7a77c6db40aed91e827b549220ac499323d2565fcdb29ad8c67cd6631529074f02f2273caa5a341406b5faf7544940ef208affae5042e2d566526149267198",
          "sha256": "4fc7147440e975f10133f8e6f0232c249ff9b07d03e7eaf6f86f4540fda62ac2",
          "sha1": "1dad4f37d6a4d6371c7a605f896742421e5d6945",
          "md5": "5c33946796891715f07b0be3bf462567"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-242",
          "version": {
            "requires": "0.22.1"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.22.0"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-core-242-0.22.1.jar",
          "url": "jewel-markdown-core-242-0.22.1.jar",
          "size": 296453,
          "sha512": "cb7a77c6db40aed91e827b549220ac499323d2565fcdb29ad8c67cd6631529074f02f2273caa5a341406b5faf7544940ef208affae5042e2d566526149267198",
          "sha256": "4fc7147440e975f10133f8e6f0232c249ff9b07d03e7eaf6f86f4540fda62ac2",
          "sha1": "1dad4f37d6a4d6371c7a605f896742421e5d6945",
          "md5": "5c33946796891715f07b0be3bf462567"
        }
      ]
    }
  ]
}
