{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-text/1.3.1/ui-text-1.3.1.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-text",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.54"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-desktop-1.3.1.jar",
          "url": "ui-text-desktop-1.3.1.jar",
          "size": 626849,
          "sha512": "9a0ceb27e2d85b231b634fdff467975a83d2fbc3352ba44fe706e09cfd2b20c01ef7e6990997903852007c7ee13d8dbe71bfe7493571fb393fd70756ca916897",
          "sha256": "a38a99430e9c7f641f419874be0aadc11bf056fcd54c09ad274eef6865bbf927",
          "sha1": "4e2299557168cac1d957bdc5da12d647f4e44089",
          "md5": "d8e00a3fcf7066919a313b2a4eb0b625"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.54"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-desktop-1.3.1.jar",
          "url": "ui-text-desktop-1.3.1.jar",
          "size": 626849,
          "sha512": "9a0ceb27e2d85b231b634fdff467975a83d2fbc3352ba44fe706e09cfd2b20c01ef7e6990997903852007c7ee13d8dbe71bfe7493571fb393fd70756ca916897",
          "sha256": "a38a99430e9c7f641f419874be0aadc11bf056fcd54c09ad274eef6865bbf927",
          "sha1": "4e2299557168cac1d957bdc5da12d647f4e44089",
          "md5": "d8e00a3fcf7066919a313b2a4eb0b625"
        }
      ]
    }
  ]
}