{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-gradle-plugin",
    "version": "2.0.20-RC2-1.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.0.20-RC2-1.0.24.jar",
          "url": "symbol-processing-gradle-plugin-2.0.20-RC2-1.0.24.jar",
          "size": 169485,
          "sha512": "ef0c6b3c5317b643ba1be25387ab950eecd9f67b49b5114728ec52367fa6060bffc7c3e824033054d94a82e7dab558b5ecd23b0c5938a0b51a78b3cbde9aab2a",
          "sha256": "1db620064eb714513d7615f412819d98d5979cd46f5edb1bc752a7c6d5a0268b",
          "sha1": "2894a0d9d5cc64177bf2b4a2074e52c0e5ef9064",
          "md5": "a1d3e28aadb0b15892e311607ecc3c7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.20-RC2-1.0.24"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.0.20-RC2-1.0.24"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-gradle-plugin-2.0.20-RC2-1.0.24.jar",
          "url": "symbol-processing-gradle-plugin-2.0.20-RC2-1.0.24.jar",
          "size": 169485,
          "sha512": "ef0c6b3c5317b643ba1be25387ab950eecd9f67b49b5114728ec52367fa6060bffc7c3e824033054d94a82e7dab558b5ecd23b0c5938a0b51a78b3cbde9aab2a",
          "sha256": "1db620064eb714513d7615f412819d98d5979cd46f5edb1bc752a7c6d5a0268b",
          "sha1": "2894a0d9d5cc64177bf2b4a2074e52c0e5ef9064",
          "md5": "a1d3e28aadb0b15892e311607ecc3c7b"
        }
      ]
    }
  ]
}
