{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.22.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.22.1.jar",
          "url": "checker-qual-3.22.1.jar",
          "size": 222171,
          "sha512": "ea9a72df6d215582282cbe33398697bbc95331b73b22f21200cfa370a9e4af8208e5e6d8465c1c2568b8ea0dc2c045b6f18a74c0a81e9b91550ead0d1b7ecefe",
          "sha256": "8dfb8247a3b90da2c12cba6d92cb4cc1a0919996aa8c171680862cfbf2307a93",
          "sha1": "c8069a56b461d656ec205f49526ee32c3ad60995",
          "md5": "994b138475cb86da03c612ec14bc4b80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.22.1.jar",
          "url": "checker-qual-3.22.1.jar",
          "size": 222171,
          "sha512": "ea9a72df6d215582282cbe33398697bbc95331b73b22f21200cfa370a9e4af8208e5e6d8465c1c2568b8ea0dc2c045b6f18a74c0a81e9b91550ead0d1b7ecefe",
          "sha256": "8dfb8247a3b90da2c12cba6d92cb4cc1a0919996aa8c171680862cfbf2307a93",
          "sha1": "c8069a56b461d656ec205f49526ee32c3ad60995",
          "md5": "994b138475cb86da03c612ec14bc4b80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.22.1-javadoc.jar",
          "url": "checker-qual-3.22.1-javadoc.jar",
          "size": 958110,
          "sha512": "1980b6b70346e0b4e71c817ee90aff6177964513b77dc2f97486531b29d09908b81972a4ad55deb66a9b0fa127040a0bbf29dade30d4181f65acfb52a0e2dab7",
          "sha256": "399e296fb88af2b92a36f7a9db99275e97c6a187e58b088297630bc0af523646",
          "sha1": "782f51d0af81abf52be7d83f4d916425b86b7ed7",
          "md5": "a9775a0ae9611473136d1dc068c597b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.22.1-sources.jar",
          "url": "checker-qual-3.22.1-sources.jar",
          "size": 252820,
          "sha512": "3055d5b2986c7b7833a557b55312ec69cc333a65db8235a2ca6d04fb2302243ca05724a29efba42fecd2f162f28b615ead1844fb0cbaf392fa7c85745d08489c",
          "sha256": "2c1126be8c04bb3d4a981584b0f47d02c0c77422430dddb5bab70867b9e44439",
          "sha1": "8829a165e9529c665b446a23fbc736cbaba3d2a3",
          "md5": "405217daef762fd223b6ebf1410211e2"
        }
      ]
    }
  ]
}
