{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.components",
    "module": "components-ui-tooling-preview",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-1.10.1.jar",
          "url": "components-ui-tooling-preview-1.10.1.jar",
          "size": 5635,
          "sha512": "29ae489c897eca52147f627e684f482b848687a93b5018ee29cd335e5cccbc6401dfac4431db72d90d49713dd0bc2caa61f68f290a3a82a1d240bacc5591bcb6",
          "sha256": "155ff009d276e227c1a5a59a7cd728d4eb589d0be4669a0b971702899ea6d7ec",
          "sha1": "04826a1ba0063f575a48c758edea366c34c266b5",
          "md5": "abc52b1f8e03352f680ecd930b4359e5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-kotlin-1.10.1-sources.jar",
          "url": "components-ui-tooling-preview-1.10.1-sources.jar",
          "size": 5820,
          "sha512": "d8a028913cab622cd5f1ed2c0ee905e29fa836e4127defd6b4285cc43a5f8078b4e52e8b6be68b9d2abe7fffd3f5b1800e326a6d6ad032073c2ec98005fc9046",
          "sha256": "cdb7f082fe84adc94c907f46dc001b57491ca37088bd2e9afdbb27b2970f6248",
          "sha1": "312821892b89a47489332ddd859a3bd9a3f58ca5",
          "md5": "90d26f6e9445c114eb73991276e67a02"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-android/1.10.1/components-ui-tooling-preview-android-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-android",
        "version": "1.10.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-android/1.10.1/components-ui-tooling-preview-android-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-android",
        "version": "1.10.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-android/1.10.1/components-ui-tooling-preview-android-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-android",
        "version": "1.10.1"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-desktop/1.10.1/components-ui-tooling-preview-desktop-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-desktop",
        "version": "1.10.1"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-desktop/1.10.1/components-ui-tooling-preview-desktop-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-desktop",
        "version": "1.10.1"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-desktop/1.10.1/components-ui-tooling-preview-desktop-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-desktop",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosArm64/1.10.1/components-ui-tooling-preview-iosArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosArm64/1.10.1/components-ui-tooling-preview-iosArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosArm64/1.10.1/components-ui-tooling-preview-iosArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosSimulatorArm64/1.10.1/components-ui-tooling-preview-iosSimulatorArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosSimulatorArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosSimulatorArm64/1.10.1/components-ui-tooling-preview-iosSimulatorArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosSimulatorArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosSimulatorArm64/1.10.1/components-ui-tooling-preview-iosSimulatorArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosSimulatorArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosX64/1.10.1/components-ui-tooling-preview-iosX64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosX64",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosX64/1.10.1/components-ui-tooling-preview-iosX64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosX64",
        "version": "1.10.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-iosX64/1.10.1/components-ui-tooling-preview-iosX64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-iosX64",
        "version": "1.10.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-js/1.10.1/components-ui-tooling-preview-js-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-js",
        "version": "1.10.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-js/1.10.1/components-ui-tooling-preview-js-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-js",
        "version": "1.10.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-js/1.10.1/components-ui-tooling-preview-js-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-js",
        "version": "1.10.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-macosArm64/1.10.1/components-ui-tooling-preview-macosArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-macosArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-macosArm64/1.10.1/components-ui-tooling-preview-macosArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-macosArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-macosArm64/1.10.1/components-ui-tooling-preview-macosArm64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-macosArm64",
        "version": "1.10.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-macosX64/1.10.1/components-ui-tooling-preview-macosX64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-macosX64",
        "version": "1.10.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-macosX64/1.10.1/components-ui-tooling-preview-macosX64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-macosX64",
        "version": "1.10.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-macosX64/1.10.1/components-ui-tooling-preview-macosX64-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-macosX64",
        "version": "1.10.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-wasmJs/1.10.1/components-ui-tooling-preview-wasmJs-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-wasmJs",
        "version": "1.10.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-wasmJs/1.10.1/components-ui-tooling-preview-wasmJs-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-wasmJs",
        "version": "1.10.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../components-ui-tooling-preview-wasmJs/1.10.1/components-ui-tooling-preview-wasmJs-1.10.1.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-ui-tooling-preview-wasmJs",
        "version": "1.10.1"
      }
    }
  ]
}
