{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.7.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-rc01.aar",
          "url": "activity-1.7.0-rc01.aar",
          "size": 142697,
          "sha512": "3233c87b0638ae1901c906e0bf177f0f972be80ee46d042d19b0eb6f6e16a896c9394486e0c621cb3db93d249f22fba789e080a2c8924dadde7fe41c29968d73",
          "sha256": "bd40dad0f83c04385d8e2dfe8d5a19b5d2670b6dd09f689c004881cae74fc72d",
          "sha1": "b9ea8d3467b9febdb4bb04ea9ee0bc1242562b44",
          "md5": "98a7b6d4109cf7cf67a114c829e72399"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-rc01.aar",
          "url": "activity-1.7.0-rc01.aar",
          "size": 142697,
          "sha512": "3233c87b0638ae1901c906e0bf177f0f972be80ee46d042d19b0eb6f6e16a896c9394486e0c621cb3db93d249f22fba789e080a2c8924dadde7fe41c29968d73",
          "sha256": "bd40dad0f83c04385d8e2dfe8d5a19b5d2670b6dd09f689c004881cae74fc72d",
          "sha1": "b9ea8d3467b9febdb4bb04ea9ee0bc1242562b44",
          "md5": "98a7b6d4109cf7cf67a114c829e72399"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-rc01-sources.jar",
          "url": "activity-1.7.0-rc01-sources.jar",
          "size": 49097,
          "sha512": "7741b8b4ceceba4b3302520bc4d28ed68429dbbccec0a330050a5b62c33ce4800c92a10424cf9ee7e76028ec0f00ab71cc8cb2bfda255ace7acadacd247a2d92",
          "sha256": "7a110b077cd607362f18e867cf0ed6106a7868b2ab60758a10f152da32449599",
          "sha1": "6f06f057eb5dedb1247cecd29b77a1ab826a0712",
          "md5": "1f5770f4781aa71b0ed6bed3832480ba"
        }
      ]
    }
  ]
}