{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-core",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08.jar",
          "url": "tools-core-1.0.0-alpha08.jar",
          "size": 310505,
          "sha512": "f902ffb8b9f44e993f14b2dcea76f6fa86d8fd8e9944bb49eee9698a76970d7d1fbf8c4c010e3e199191e789063a9ac3c647f16197208bb3e99653e784f68d6c",
          "sha256": "7b5527be66b0265381d60c64dc448f37528e01ff139f5bc25abe7bf2180d3c59",
          "sha1": "f668065c573d865c6742cb5b5c984e4349ca62a2",
          "md5": "3e1b4b202280e5ab40e08b08f1bb8015"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08.jar",
          "url": "tools-core-1.0.0-alpha08.jar",
          "size": 310505,
          "sha512": "f902ffb8b9f44e993f14b2dcea76f6fa86d8fd8e9944bb49eee9698a76970d7d1fbf8c4c010e3e199191e789063a9ac3c647f16197208bb3e99653e784f68d6c",
          "sha256": "7b5527be66b0265381d60c64dc448f37528e01ff139f5bc25abe7bf2180d3c59",
          "sha1": "f668065c573d865c6742cb5b5c984e4349ca62a2",
          "md5": "3e1b4b202280e5ab40e08b08f1bb8015"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08-sources.jar",
          "url": "tools-core-1.0.0-alpha08-sources.jar",
          "size": 51125,
          "sha512": "9c5bcd7e52fbec5b42ffef2d7643f0e7d7dc6b89907d4ca3bc9381c04925f532a33331bb0d23f082a6b5c2872bb6333dceac8a0ffe1a4bca88b6e80386f1f68c",
          "sha256": "e0fb925cee336d1c2b4a5abc0339e304435851beb2c8870b0be2308c05487052",
          "sha1": "ac55c52f2e2232004e189d791a14fb8355296a94",
          "md5": "fa1a72ddc8abe3b48a1bc96bb8894817"
        }
      ]
    }
  ]
}