{
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.17.2/atomicfu-0.17.2.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "jakhrwhozvgurdlblk5bmqk4qi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "atomicfu-jvm-0.17.2.jar",
          "url": "atomicfu-jvm-0.17.2.jar",
          "size": 36312,
          "sha512": "3d01b58c93dceeecb565888bcb5d8fd04f4a1b1dae087f03cdab193588c3739f666c567bca08b0b0e4d0ab04a927d661655902a304151937a104fc4225ff6d80",
          "sha256": "636968b47a6c31262ebc984255e56ca54a8dd16de7f17c35103aac88d827256e",
          "sha1": "7f2eae498c00cd33ef2a8eba4be72b284270aa16",
          "md5": "d6b6f3a195696acf1828b1f125125ed7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-jvm-0.17.2.jar",
          "url": "atomicfu-jvm-0.17.2.jar",
          "size": 36312,
          "sha512": "3d01b58c93dceeecb565888bcb5d8fd04f4a1b1dae087f03cdab193588c3739f666c567bca08b0b0e4d0ab04a927d661655902a304151937a104fc4225ff6d80",
          "sha256": "636968b47a6c31262ebc984255e56ca54a8dd16de7f17c35103aac88d827256e",
          "sha1": "7f2eae498c00cd33ef2a8eba4be72b284270aa16",
          "md5": "d6b6f3a195696acf1828b1f125125ed7"
        }
      ]
    }
  ]
}
