{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-util-1.0.0.aar",
          "url": "ui-util-1.0.0.aar",
          "size": 7866,
          "sha512": "e65a02b6088e7552619caed4f0b9570092fc10945b46f31a4ed3725940c0b85b97d118717cab1ea922a2bf2f4cf97b3a0dc8fe5ed727cb4efb0ed55c5e1397bc",
          "sha256": "06dc15e9cbb724bb1f4678af2a354acc5a15fb0ee5dcc6322e780caaf0559078",
          "sha1": "3735810c3ff713e363626cc4a8888cb0f8c352fb",
          "md5": "e8cf5c701f5fce15c03501db77c892cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-1.0.0.aar",
          "url": "ui-util-1.0.0.aar",
          "size": 7866,
          "sha512": "e65a02b6088e7552619caed4f0b9570092fc10945b46f31a4ed3725940c0b85b97d118717cab1ea922a2bf2f4cf97b3a0dc8fe5ed727cb4efb0ed55c5e1397bc",
          "sha256": "06dc15e9cbb724bb1f4678af2a354acc5a15fb0ee5dcc6322e780caaf0559078",
          "sha1": "3735810c3ff713e363626cc4a8888cb0f8c352fb",
          "md5": "e8cf5c701f5fce15c03501db77c892cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-util-1.0.0-sources.jar",
          "url": "ui-util-1.0.0-sources.jar",
          "size": 4574,
          "sha512": "0d0d4178392cad87a78875b6d4cfd2aa27860ddfc0115c3a7f13003e7834503f32697f885b0c1b4aad56d409e258480b0e891e0711fe019028bc96866f33be6e",
          "sha256": "c72c6cf6834497e42f09c61f4e3e17a8bdc1b2add6dce25b546fbe6176322b34",
          "sha1": "69426082fe7d7ebbd25c1f8f755d2ee2b65b46da",
          "md5": "26e3ab71e8414dd37d17637ab86d2d3d"
        }
      ]
    }
  ]
}
