{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-stdlib",
    "version": "2.3.20-dev-825",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.3.20-dev-825"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.3.20-dev-825.jar",
          "url": "kotlin-stdlib-2.3.20-dev-825.jar",
          "size": 1796814,
          "sha512": "e70be5bf267865bbe1d2e75467193608f2ebaaf9101d5c5ceef51c68d99f1c1336740e9a7249aab6be0edcd80bfa52d2e550101ef16c98482b6528327809af95",
          "sha256": "8f775462d30112f4058eb620c0803c8f753f7074876c04343a242331a5d203ca",
          "sha1": "bcc3501f02f3bbb5f8c45ac1acd4d108b7491ab4",
          "md5": "f7afd50647ecf480dda31247f03229d4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.3.20-dev-825"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.3.20-dev-825.jar",
          "url": "kotlin-stdlib-2.3.20-dev-825.jar",
          "size": 1796814,
          "sha512": "e70be5bf267865bbe1d2e75467193608f2ebaaf9101d5c5ceef51c68d99f1c1336740e9a7249aab6be0edcd80bfa52d2e550101ef16c98482b6528327809af95",
          "sha256": "8f775462d30112f4058eb620c0803c8f753f7074876c04343a242331a5d203ca",
          "sha1": "bcc3501f02f3bbb5f8c45ac1acd4d108b7491ab4",
          "md5": "f7afd50647ecf480dda31247f03229d4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-stdlib-2.3.20-dev-825-sources.jar",
          "url": "kotlin-stdlib-2.3.20-dev-825-sources.jar",
          "size": 727599,
          "sha512": "9ea3517c6aeb719b447c8ccdace66717c06d211383ab520605ba70b98beeb907418d08cf218ea6af6c795edc8a84881fa8ff12893b86065eed9e6f401f40d67b",
          "sha256": "1e7e15901e2a53eb09298743eab8a68ffdcce80a6d7d7d166aaa7f0a08a5ddfc",
          "sha1": "3654e7c3432d7a7c4552a83aeb7c1525d989f1f8",
          "md5": "0395f8152c27374fcdcd2ad63338550e"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.3.20-dev-825"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.3.20-dev-825-all.jar",
          "url": "kotlin-stdlib-2.3.20-dev-825-all.jar",
          "size": 213424,
          "sha512": "98d670c4fefac9f8d909b08c4448d332f2a1cc677ef64ed91f503fa2670b037a4a4397681b4fa12e84c827ebbed2a49eddbf3357c2eb2f34b348c8f55b0856f3",
          "sha256": "14c61afe46bff143347ba19cab42c2e90e38572642139e91bddda53b0c2fd980",
          "sha1": "71a6b0da6d573cc54b44251ad68a4f758d8b576e",
          "md5": "3af17790f605a9bc2f33782cec903f6a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-stdlib-2.3.20-dev-825-common-sources.jar",
          "url": "kotlin-stdlib-2.3.20-dev-825-common-sources.jar",
          "size": 458340,
          "sha512": "3723b83f1d73cdfa0896e4a1ab30b9992bed159f1f2a689d3cd052d9a79ae44f7a45119bd9e92fda7635b04c34236f81854f28f6e67c54f445497a9c94b7e1a8",
          "sha256": "52644cec7b2471e66cff2b62b305e0d56c916e5c80acd493c5a49bcc7bdf110c",
          "sha1": "1888a23e104f176a570f233968b95f958a3d2ed0",
          "md5": "d2a69f22fec6fa0f913043dbf2879acc"
        }
      ]
    },
    {
      "name": "nativeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.3.20-dev-825"
          }
        }
      ]
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.3.20-dev-825/kotlin-stdlib-js-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.3.20-dev-825"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.3.20-dev-825/kotlin-stdlib-js-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.3.20-dev-825"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.3.20-dev-825/kotlin-stdlib-js-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.3.20-dev-825"
      }
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.3.20-dev-825/kotlin-stdlib-wasm-js-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.3.20-dev-825"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.3.20-dev-825/kotlin-stdlib-wasm-js-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.3.20-dev-825"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.3.20-dev-825/kotlin-stdlib-wasm-js-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.3.20-dev-825"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.3.20-dev-825/kotlin-stdlib-wasm-wasi-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.3.20-dev-825"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.3.20-dev-825/kotlin-stdlib-wasm-wasi-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.3.20-dev-825"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.3.20-dev-825/kotlin-stdlib-wasm-wasi-2.3.20-dev-825.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.3.20-dev-825"
      }
    }
  ]
}
