{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle",
    "module": "gradle-tooling-api",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-tooling-api-9.3.1-sources.jar",
          "url": "gradle-tooling-api-9.3.1-sources.jar",
          "size": 6254939,
          "sha512": "2f5adb6ff57ee0063be1c7cd4aad205fc0c5c8b1895dfa7946dd6b4a8b4de16cd1c44c56626b894d100a9e9be2594f7a4f3c700944bf316f1ef55410ca8d60fc",
          "sha256": "a9c97ffacf17d98f8b78823980db6d1556b1a41f3b22bf5613f5c69175e084a2",
          "sha1": "684552db91c92c37b80b45da195c4daae9c91b21",
          "md5": "217764316810ffd55ca87257003a6128"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-tooling-api-9.3.1-javadoc.jar",
          "url": "gradle-tooling-api-9.3.1-javadoc.jar",
          "size": 1875796,
          "sha512": "2cffd6177127a34e41228c0d4af62cfeba864b982a2eab0958533e671a512687cd77fa043e5a6898b8d333255fd5b49c693cf0ad2f28d6cbf26adf3af5c6a025",
          "sha256": "b7fc0421cb2eff0277bfb658381389319f02dd74e6f39c8311484ed97cb1e3cc",
          "sha1": "843a0e0d1d941646c7d390da831eab7e37f265d4",
          "md5": "31e1b4f73e69f59c75e1ea2064367c53"
        }
      ]
    },
    {
      "name": "shadedRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-tooling-api-9.3.1.jar",
          "url": "gradle-tooling-api-9.3.1.jar",
          "size": 2985777,
          "sha512": "25995825269b32ae46cc3045c076cc0cf4c6a6e0f2b939605d64c6b637a79e241cf70a4f1f937b7a84a577e1e9a0484f3c2a06ec6cf228fa1ae5f7d0afb33101",
          "sha256": "c8dff5424eb5d6c4500c5ed3f04c41f42369adc0c289b67e171813decf26ff3e",
          "sha1": "e9116aa38a70efc52b08544cf9ac421a6a179331",
          "md5": "8eaaceaf58c06f38eb2aad51fead0f7e"
        }
      ]
    }
  ]
}
