{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-android",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-android-1.8.0.jar",
          "url": "kotlinx-coroutines-android-1.8.0.jar",
          "size": 20464,
          "sha512": "0dac7392e60619dff9d3bdde4d1be9da9c43eb646e51d54a25cb2f51c06c910224f736372f4988d00778c356f3f1edee3412616ea0d4f96d5f8d0b55d7db3226",
          "sha256": "aad1c54d3e4c2a0558a246e9e11610aa12bd7075756b7c39dea15ef84f9fff48",
          "sha1": "d908407315c91c64b461674aba3944a912456e8b",
          "md5": "459b348924dd816cd0d1c5e39380a587"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-android-1.8.0.jar",
          "url": "kotlinx-coroutines-android-1.8.0.jar",
          "size": 20464,
          "sha512": "0dac7392e60619dff9d3bdde4d1be9da9c43eb646e51d54a25cb2f51c06c910224f736372f4988d00778c356f3f1edee3412616ea0d4f96d5f8d0b55d7db3226",
          "sha256": "aad1c54d3e4c2a0558a246e9e11610aa12bd7075756b7c39dea15ef84f9fff48",
          "sha1": "d908407315c91c64b461674aba3944a912456e8b",
          "md5": "459b348924dd816cd0d1c5e39380a587"
        }
      ]
    }
  ]
}
