{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.7.0-dev1743/runtime-1.7.0-dev1743.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "1.7.0-dev1743",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.7.0-dev1743.jar",
          "url": "runtime-desktop-1.7.0-dev1743.jar",
          "size": 1367606,
          "sha512": "f2e08c132ee995c5f2028e46f8b1975d97032c74eb360cf4ec4fc3d0249a150171480acb83a9c1e5efdcbf0af4884a87566ae7ca8dc2d189431a775f68d42c8c",
          "sha256": "e55e98e7da0a42c8c5a05c7b78a6401e86f68e7ec970ed16a8584712f3853a67",
          "sha1": "7607e37833a6c6fe4ea56c0b24f93fd3cc861543",
          "md5": "1d3e7f4e73d04620909ca09c5e60862d"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.7.0-dev1743"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.7.0-dev1743.jar",
          "url": "runtime-desktop-1.7.0-dev1743.jar",
          "size": 1367606,
          "sha512": "f2e08c132ee995c5f2028e46f8b1975d97032c74eb360cf4ec4fc3d0249a150171480acb83a9c1e5efdcbf0af4884a87566ae7ca8dc2d189431a775f68d42c8c",
          "sha256": "e55e98e7da0a42c8c5a05c7b78a6401e86f68e7ec970ed16a8584712f3853a67",
          "sha1": "7607e37833a6c6fe4ea56c0b24f93fd3cc861543",
          "md5": "1d3e7f4e73d04620909ca09c5e60862d"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "runtime-desktop-1.7.0-dev1743-sources.jar",
          "url": "runtime-desktop-1.7.0-dev1743-sources.jar",
          "size": 376483,
          "sha512": "e22b84a5bff9d81aecb2ec580c8f1541205fefcb8b01f697b22d0186a89028093ba06c9d52b9323b21d967aba0ca5c5456e1a5042359d4daa07e333b7ef84895",
          "sha256": "ae8123019047530439ca51f3d196c3b05bef87bb5d00f236be8eddc126698fec",
          "sha1": "e7b3801cf37c06337ad4038bccf57e594ac9ad13",
          "md5": "9e279834e27e671410b907b542a1173e"
        }
      ]
    }
  ]
}