{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-complications-data-source-ktx",
    "version": "1.2.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-ktx-1.2.0-alpha08.aar",
          "url": "watchface-complications-data-source-ktx-1.2.0-alpha08.aar",
          "size": 9068,
          "sha512": "149a1950f6356d1e82ae95ce579d4f8b07b55cb850245f4f1058f961bb1c6faa7dcc19713c83a8c1916ceca0fde5f0c2857cb2e9165b4879a2984620e8ca65f0",
          "sha256": "8c190c44dd4956176386727ce6c4e16ed806d924512e8acb47f3670057b170b3",
          "sha1": "cf2cf1fde418ef3f93bae4126b8d66d32d02c5d8",
          "md5": "4e1f63ba134eb278e9328e4ced54d265"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-ktx-1.2.0-alpha08.aar",
          "url": "watchface-complications-data-source-ktx-1.2.0-alpha08.aar",
          "size": 9068,
          "sha512": "149a1950f6356d1e82ae95ce579d4f8b07b55cb850245f4f1058f961bb1c6faa7dcc19713c83a8c1916ceca0fde5f0c2857cb2e9165b4879a2984620e8ca65f0",
          "sha256": "8c190c44dd4956176386727ce6c4e16ed806d924512e8acb47f3670057b170b3",
          "sha1": "cf2cf1fde418ef3f93bae4126b8d66d32d02c5d8",
          "md5": "4e1f63ba134eb278e9328e4ced54d265"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-ktx-1.2.0-alpha08-sources.jar",
          "url": "watchface-complications-data-source-ktx-1.2.0-alpha08-sources.jar",
          "size": 2142,
          "sha512": "c3ca91c87272178541815111f04023c11276ce0f3c511cde7869594b7686e5af94fd514eb46efa6c2a24e6f4759f3e89d61f8277b1f5b476a5a25f7171d3583e",
          "sha256": "40f5bc9aa9fbcd3c30ca7ca0087fba16c31b88825c0d3c0e7eae7dbd58d36712",
          "sha1": "0a4f1e7f56f5888cf2902e32d9d904cd7c6138f5",
          "md5": "9c701923faf1cd67cb42dd6087ac26ec"
        }
      ]
    }
  ]
}