# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

metric_spec: {
  id: "total_runtime_per_thread_for_systemui_process"
  dimensions: "slice_name"
  dimensions: "thread_name"
  dimensions: "process_name"
  value: "total_runtime"
  query: {
    id: "duration_per_thread"
    inner_query: {
      simple_slices: {
        process_name_glob: "com.android.systemui"
      }
      select_columns: { column_name: "dur" }
      select_columns: { column_name: "slice_name" }
      select_columns: { column_name: "thread_name" }
      select_columns: { column_name: "process_name" }
    }
    group_by: {
      column_names: "slice_name"
      column_names: "thread_name"
      column_names: "process_name"
      aggregates: {
        column_name: "dur"
        op: SUM
        result_column_name: "total_runtime"
      }
    }
    select_columns: { column_name: "slice_name" }
    select_columns: { column_name: "thread_name" }
    select_columns: { column_name: "process_name" }
    select_columns: { column_name: "total_runtime" }
  }
}
