load("//tools/base/bazel:app_inspection.bzl", "app_inspection_proto")

app_inspection_proto(
    name = "workmanager_inspector_proto",
    jar = "workmanager-inspector.jar",
    proto_file_name = "workmanager_protocal.proto",
    visibility = ["//visibility:public"],
)
