{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-api-incubator",
    "version": "1.43.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.43.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-api-incubator-1.43.0-alpha.jar",
          "url": "opentelemetry-api-incubator-1.43.0-alpha.jar",
          "size": 64105,
          "sha512": "e15fa60be11bebc2fea3f957bb446d6cf144ee4f14ba843ab9883dc1ce2c5f5f2bcc2f523cb2097368d06e574b0434522db0e6f96a7804522205f26bdf2ee090",
          "sha256": "a64d48638cdd4324e5ffab80c85784173f8c5068f059c07d8380f428d7c39ec8",
          "sha1": "2dcee00ad7552d9190857e271f6066e655c6c719",
          "md5": "62db4305c89a1c2fd18507eefb0a62a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.43.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-api-incubator-1.43.0-alpha.jar",
          "url": "opentelemetry-api-incubator-1.43.0-alpha.jar",
          "size": 64105,
          "sha512": "e15fa60be11bebc2fea3f957bb446d6cf144ee4f14ba843ab9883dc1ce2c5f5f2bcc2f523cb2097368d06e574b0434522db0e6f96a7804522205f26bdf2ee090",
          "sha256": "a64d48638cdd4324e5ffab80c85784173f8c5068f059c07d8380f428d7c39ec8",
          "sha1": "2dcee00ad7552d9190857e271f6066e655c6c719",
          "md5": "62db4305c89a1c2fd18507eefb0a62a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-api-incubator-1.43.0-alpha-javadoc.jar",
          "url": "opentelemetry-api-incubator-1.43.0-alpha-javadoc.jar",
          "size": 179421,
          "sha512": "6998114c93b5172137d5e158cc1839336c4900da2770113d60d9228ed3e5ac3507a24537282d6fb4a52dc9bb45d355dda179b4df2ca97f8626a6714f422f2137",
          "sha256": "934aba97f76c8cdfd27aa78f2b19fe9dba1b91303240a1ca2a27a2b09e9b1791",
          "sha1": "de522da8627c8be0eb1933ff07ab7581c2e5056a",
          "md5": "e35189d4397624dda152914fa30f40b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-api-incubator-1.43.0-alpha-sources.jar",
          "url": "opentelemetry-api-incubator-1.43.0-alpha-sources.jar",
          "size": 31623,
          "sha512": "2430de18e6150ba837a512ca57ee92bf22ff2ea2c7b7744050c8cc2fc5bcf4efea6e2e7e2b7e78168ffb8fc2e26e64d879e1049bc43e5301b8606b2d6dfeaf48",
          "sha256": "871b4ef83803384b4a4ce794ea7b2384e0df70c8a15dc48afcf318525d7547f0",
          "sha1": "9a2eda9a15b3962caaab1dd3d92a799b3134ef34",
          "md5": "e53aab7ff404fdd33a6577435b343302"
        }
      ]
    }
  ]
}
