{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-lint",
    "version": "1.8.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-lint-1.8.0-alpha06.jar",
          "url": "animation-core-lint-1.8.0-alpha06.jar",
          "size": 1053865,
          "sha512": "94ba914f0bfb51e39cb2a766ab51f30d53890aa2776332cda75c262b66c34875c94288aa15bbd502ac4c3f5cbbdb9e5060df7cfd9db823ce5ead1cb5eb21a66f",
          "sha256": "dad0586ed4c3f9ca9e20164e1f249f088b44bb9e4f7d3c83fad767d45d9d3b25",
          "sha1": "b8cf6bf5da6856a33df2d5d40db8a3dcc279cf80",
          "md5": "09762e768e7d8c5aa701b0f41e316b7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-lint-1.8.0-alpha06.jar",
          "url": "animation-core-lint-1.8.0-alpha06.jar",
          "size": 1053865,
          "sha512": "94ba914f0bfb51e39cb2a766ab51f30d53890aa2776332cda75c262b66c34875c94288aa15bbd502ac4c3f5cbbdb9e5060df7cfd9db823ce5ead1cb5eb21a66f",
          "sha256": "dad0586ed4c3f9ca9e20164e1f249f088b44bb9e4f7d3c83fad767d45d9d3b25",
          "sha1": "b8cf6bf5da6856a33df2d5d40db8a3dcc279cf80",
          "md5": "09762e768e7d8c5aa701b0f41e316b7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha06"
          },
          "reason": "animation-core-lint is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-lint-1.8.0-alpha06-sources.jar",
          "url": "animation-core-lint-1.8.0-alpha06-sources.jar",
          "size": 12610,
          "sha512": "8ca2a2846f8ea0e5ed632c81caf1426d9a68da257a9d0fd1706fbd70faac48729a007306f13dc3a0038276a09d84850850c389ce90ad59aa42c0a0bc74466de2",
          "sha256": "d760e8a6aedd59de8cca9e15b0651a1c5f91ca5e4290cbf9686d9c3d9794787b",
          "sha1": "e252efe958d6e9983389f303c301d472d8ee1107",
          "md5": "d07377057bec8267a0e7b6490f9e3bc3"
        }
      ]
    }
  ]
}