{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-websockets/2.3.5/ktor-websockets-2.3.5.module",
    "group": "io.ktor",
    "module": "ktor-websockets",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-jvm-2.3.5.jar",
          "url": "ktor-websockets-jvm-2.3.5.jar",
          "size": 178455,
          "sha512": "432e3a3e391b400b7caf070d207fd3d9e471bb12cc6917305d4e2449e0506f6aae742817b1a5702a2001cd6b1e60ace744242ade49176b017f9dd1e19dc11885",
          "sha256": "601818e9984fe3ac65e4380d1a8a7e1f03b11efc3b942eda44897ed0b53a65ed",
          "sha1": "af65d672f48cd04fdf097aab1d7534687262fd61",
          "md5": "22ac75c88da024d1d9450385da917688"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websockets-jvm-2.3.5.jar",
          "url": "ktor-websockets-jvm-2.3.5.jar",
          "size": 178455,
          "sha512": "432e3a3e391b400b7caf070d207fd3d9e471bb12cc6917305d4e2449e0506f6aae742817b1a5702a2001cd6b1e60ace744242ade49176b017f9dd1e19dc11885",
          "sha256": "601818e9984fe3ac65e4380d1a8a7e1f03b11efc3b942eda44897ed0b53a65ed",
          "sha1": "af65d672f48cd04fdf097aab1d7534687262fd61",
          "md5": "22ac75c88da024d1d9450385da917688"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-websockets-jvm-2.3.5-sources.jar",
          "url": "ktor-websockets-jvm-2.3.5-sources.jar",
          "size": 33352,
          "sha512": "0855af045e2d7fcdb72723ac93e68b34e2c5d4f813478d74f8905f3a5126c2afae00259c59a372b4d5c542754bdf39e31b5bfc409a581507bd474a71213df691",
          "sha256": "0027c56f7c0d2b3272bbe47c5b53a8e3e47be673f72a86578aa6b87ab0f534b0",
          "sha1": "493c63ed88319d849bd4c7914f395e93c4abe9ea",
          "md5": "36f8db8c0bd61ac0718a8696f06eebc1"
        }
      ]
    }
  ]
}
