{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-test/1.6.20-dev1663/ui-test-1.6.20-dev1663.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-test",
    "version": "1.6.20-dev1663",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-desktop-1.6.20-dev1663.jar",
          "url": "ui-test-desktop-1.6.20-dev1663.jar",
          "size": 446261,
          "sha512": "9a4b073975d58cfe720c0d0ee8686c7c74570313873f26ac0decbf645a7a105b67b16385db74b6989edbc255f6d4582c918d79209850b0ce516b0c46f1f5eadf",
          "sha256": "9cd855d005014d3148361300e873701d032a2bbd5d549e63b0850c5fab7747d2",
          "sha1": "e5a88bc385db07772d0929ef0786dc3316273b81",
          "md5": "e9741ef407d6b4d4286a1c0a106eb559"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko-awt",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-desktop-1.6.20-dev1663.jar",
          "url": "ui-test-desktop-1.6.20-dev1663.jar",
          "size": 446261,
          "sha512": "9a4b073975d58cfe720c0d0ee8686c7c74570313873f26ac0decbf645a7a105b67b16385db74b6989edbc255f6d4582c918d79209850b0ce516b0c46f1f5eadf",
          "sha256": "9cd855d005014d3148361300e873701d032a2bbd5d549e63b0850c5fab7747d2",
          "sha1": "e5a88bc385db07772d0929ef0786dc3316273b81",
          "md5": "e9741ef407d6b4d4286a1c0a106eb559"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-test-desktop-1.6.20-dev1663-sources.jar",
          "url": "ui-test-desktop-1.6.20-dev1663-sources.jar",
          "size": 125062,
          "sha512": "9410f8e844457c2baea101cb45650cf085a6037bb0048c0b8b35718f712567f36bd049dfc0f7170e79738517b93b58baa5760a52bb77e51814163566e4697016",
          "sha256": "d01ad2e8645cfbac98c0350c848ba7511326485235007f6547dc7cfc6fe31e41",
          "sha1": "c30cb7430bf43bd270ca68c92e862d0e9d0c2ccc",
          "md5": "d7564078c092fb25d29f8f89037b8839"
        }
      ]
    }
  ]
}