filegroup(
    name = "kotlin-compose",
    srcs = glob(["*"]),
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "compose-compiler-hosted-0.1.0-dev03",
    jars = ["compose-compiler-hosted-0.1.0-dev03.jar"],
    visibility = ["//visibility:public"],
)
