{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.layoutlib",
    "module": "layoutlib-runtime",
    "version": "14.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.4.jar",
          "url": "layoutlib-runtime-14.0.4.jar",
          "size": 92823376,
          "sha512": "bbbf0e93c29811ba803bf07a49bd51e73f2ec3a86a143e69af823120e4239de99e4dd775cc610670f1328548b6f8a7ee65b68884f1e52bb5d7c5f795485f3274",
          "sha256": "6a5a9d3d5534050cfa7304794da2b2772098ac610cc0eaad0336a62a7ddb768c",
          "sha1": "29e10d40dbabaf80e2d21bdf4d76f19f012df1a0",
          "md5": "bdfdf27727c4d5209c434110bef588eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.4.jar",
          "url": "layoutlib-runtime-14.0.4.jar",
          "size": 92823376,
          "sha512": "bbbf0e93c29811ba803bf07a49bd51e73f2ec3a86a143e69af823120e4239de99e4dd775cc610670f1328548b6f8a7ee65b68884f1e52bb5d7c5f795485f3274",
          "sha256": "6a5a9d3d5534050cfa7304794da2b2772098ac610cc0eaad0336a62a7ddb768c",
          "sha1": "29e10d40dbabaf80e2d21bdf4d76f19f012df1a0",
          "md5": "bdfdf27727c4d5209c434110bef588eb"
        }
      ]
    },
    {
      "name": "linux",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.operatingSystem": "linux",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.4-linux.jar",
          "url": "layoutlib-runtime-14.0.4-linux.jar",
          "size": 76694959,
          "sha512": "8529e6430471ba2b156113969304b9bdf50af8bb58878aee61db25cf11e92d3ffaa17fbe9f070e1cb8d256728baf3f5bcf6e7f73f6b400a553b42348ca1902f2",
          "sha256": "37a3bf3d17ad680b2d3eb212dcfc34088266f62661be4da800cd5c1333526b00",
          "sha1": "9578cbaad8abb90b219607eb08ec68f2ab5b48c8",
          "md5": "3fde289d0222e1a806fa22e4716c0f85"
        }
      ]
    },
    {
      "name": "windows",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.operatingSystem": "windows",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.4-win.jar",
          "url": "layoutlib-runtime-14.0.4-win.jar",
          "size": 75217992,
          "sha512": "79e0e49f0aff245557e2895c8cd9c7f6683121cfc72540579dae44341462222760b28de0687ca4ca45407d4e3c040a57f01ee18349102f67fbf3bbeb16220077",
          "sha256": "6c6ebbb79dcfa92c6f2a56fb750bbfff30a50db8d8178d56fbada697af9a091c",
          "sha1": "7988c1c01dd05a1d0da4fafcea8bf595523e107b",
          "md5": "ad3c5bc8d94da6ff999f1652e85bfd19"
        }
      ]
    },
    {
      "name": "macX86",
      "attributes": {
        "org.gradle.native.architecture": "x86-64",
        "org.gradle.native.operatingSystem": "macos",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.4-mac.jar",
          "url": "layoutlib-runtime-14.0.4-mac.jar",
          "size": 75977548,
          "sha512": "290c403fc5f91bc34901474637efa4e2f3044e649900b0c372e755cff2240fb5f8dc13368a37ddbef6cb97bdcdb5cf9b1e116644761135c5b3ebeb1faad277c8",
          "sha256": "438588eab158f49818e25b1eaab404b1b987b80176f183a6bd4f91de62b405d3",
          "sha1": "ec984312484740f60ca2ddeb8c6ad714e86b9413",
          "md5": "de58bcc06b754ad95072034e1db98c63"
        }
      ]
    },
    {
      "name": "macArm",
      "attributes": {
        "org.gradle.native.architecture": "aarch64",
        "org.gradle.native.operatingSystem": "macos",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "layoutlib-runtime-14.0.4-mac-arm.jar",
          "url": "layoutlib-runtime-14.0.4-mac-arm.jar",
          "size": 75527102,
          "sha512": "797420e259d87aa5d6cbdb31a3a5773f48bcfbffd20fdd9b1db6e4808533ceb59a52b93ca1883e0c47afc9c78c71fc842456e4f99f2f33f0a089619bc08fd089",
          "sha256": "b4c740ba7eaf0600a026efdc4621598831fc5cf992dfbb3052e9929e5dbbc32f",
          "sha1": "ca9b84c42615f79aa48d49bfe57dcbb2d352e13a",
          "md5": "d9ce7b349759753b851c17b7ffb2b9bd"
        }
      ]
    }
  ]
}
