{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-common",
    "version": "7.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "databinding-common-7.0.0.jar",
          "url": "databinding-common-7.0.0.jar",
          "size": 16103,
          "sha512": "df9e97c39224bd46f5f7b572f80347d572d5058a16cc0d7a3e50ea49e34fc8a8f255e24b595a0d251943e777af4ad2857b5c4b8d08fe222db1c40a619d74cb58",
          "sha256": "aadbab43b320151554b83ef6c31205178dc2286e9592d1b731b64788bcd159eb",
          "sha1": "395b02d16f7d55443375d407c4758b2a2f8118e4",
          "md5": "e125c0b82358f7ad549f2a0f44bbd960"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.0.jar",
          "url": "databinding-common-7.0.0.jar",
          "size": 16103,
          "sha512": "df9e97c39224bd46f5f7b572f80347d572d5058a16cc0d7a3e50ea49e34fc8a8f255e24b595a0d251943e777af4ad2857b5c4b8d08fe222db1c40a619d74cb58",
          "sha256": "aadbab43b320151554b83ef6c31205178dc2286e9592d1b731b64788bcd159eb",
          "sha1": "395b02d16f7d55443375d407c4758b2a2f8118e4",
          "md5": "e125c0b82358f7ad549f2a0f44bbd960"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.0-javadoc.jar",
          "url": "databinding-common-7.0.0-javadoc.jar",
          "size": 451434,
          "sha512": "805065ad095c8ffb694f291be827e17533ad48f6398813119c2c70200171b48b907a03fa58a47fd22dc527fa48d0d2c70e0c773d667096a8b21a8473edfc782e",
          "sha256": "daee79d7c49038007b56e6bb9df152397e54e79069d882b450c23657a3b48653",
          "sha1": "059e9a0fa96958903e655898a40b7d280a04b6bc",
          "md5": "07102cce6e06b40a4861bec7b09ea937"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.0-sources.jar",
          "url": "databinding-common-7.0.0-sources.jar",
          "size": 45950,
          "sha512": "fbd39dbfb2b9092b3cf5f4edd7f23e0b889c4b592fdb3e3abe5ddeb7b49756a82b35cdef76629641c42df48297f87b7d2fbc2c659495676e34806f4fdc025553",
          "sha256": "29bf7dd7e6c772ec470cdb967a3d400a30eda6445044eb500eee0a65a422888d",
          "sha1": "71c4588c86c34cf85b05a3751d9638b467a5aa73",
          "md5": "db774d2413f28746d0a2348188261118"
        }
      ]
    }
  ]
}
