{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.4.1.aar",
          "url": "animation-core-1.4.1.aar",
          "size": 1370337,
          "sha512": "80419e71891bae4e9b9f066f7c169b0a034ecbdbf057a65c1832cc6a3e54cf475a06a11563eae64353990039850849426a0bb53f8ccb4679d16941748bd9a54b",
          "sha256": "ae056480eec40e27dc34a61e9f4e616beb2f6f206b53b794a6e0ebd51db07af5",
          "sha1": "01d96c08610023770049972a67c500b48d78489d",
          "md5": "b56d1dde37727c096d6d9731c07e27e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.4.1.aar",
          "url": "animation-core-1.4.1.aar",
          "size": 1370337,
          "sha512": "80419e71891bae4e9b9f066f7c169b0a034ecbdbf057a65c1832cc6a3e54cf475a06a11563eae64353990039850849426a0bb53f8ccb4679d16941748bd9a54b",
          "sha256": "ae056480eec40e27dc34a61e9f4e616beb2f6f206b53b794a6e0ebd51db07af5",
          "sha1": "01d96c08610023770049972a67c500b48d78489d",
          "md5": "b56d1dde37727c096d6d9731c07e27e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.4.1-sources.jar",
          "url": "animation-core-1.4.1-sources.jar",
          "size": 76758,
          "sha512": "b7230eee13102007572238982afcdc4c4347fd769e4107144d6752440ee3f92382d018f90924eac57e50e2f342b38b5ab8203caeee21b13847ca06186f15d295",
          "sha256": "f1c70ee5bb0e98daf704c4c3273cbde56e89591ced3a9bc8ac81a312729e7c81",
          "sha1": "3957e6971f325ed39642690069e47954e0fa88a3",
          "md5": "efe397b93b8e07dc004b0361c7c9f933"
        }
      ]
    }
  ]
}