{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-int-ui-standalone-242",
    "version": "0.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-242",
          "version": {
            "requires": "0.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-int-ui-standalone-242-0.26.0.jar",
          "url": "jewel-int-ui-standalone-242-0.26.0.jar",
          "size": 5902761,
          "sha512": "097e875aab7770af7c579e691ac05fca18817c1060a61beab5cdbe5064ee9eb1031f84ee8742d74d300f44689919d557ed68aaffbfea785f086cb11a7f838545",
          "sha256": "4812b41ef82b906ae8af6cd3b50127aa9deb3ed6bdc80dbf5c4518e85670d5f4",
          "sha1": "92d63cea78f45b9d648a5963fe58552c9d23a406",
          "md5": "f7b97a21d14f7fd8b2bf1fa91ec1a2d0"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-242",
          "version": {
            "requires": "0.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-int-ui-standalone-242-0.26.0.jar",
          "url": "jewel-int-ui-standalone-242-0.26.0.jar",
          "size": 5902761,
          "sha512": "097e875aab7770af7c579e691ac05fca18817c1060a61beab5cdbe5064ee9eb1031f84ee8742d74d300f44689919d557ed68aaffbfea785f086cb11a7f838545",
          "sha256": "4812b41ef82b906ae8af6cd3b50127aa9deb3ed6bdc80dbf5c4518e85670d5f4",
          "sha1": "92d63cea78f45b9d648a5963fe58552c9d23a406",
          "md5": "f7b97a21d14f7fd8b2bf1fa91ec1a2d0"
        }
      ]
    }
  ]
}
