{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-core",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-1.3.0-multiplatform-sources.jar",
          "url": "window-core-1.3.0-multiplatform-sources.jar",
          "size": 6928,
          "sha512": "07b29f581d45a5046495c2df126d3e6b0235d066c101e3f62ec00ab3244000f980c5537e1d32f353a2ff5760a385e6550216da195fcb862a0ea2474a68993a2c",
          "sha256": "5feb6a06cbb88f3cb90e9126f02445fc964a28b7a61dd2b7291c0f99735252ea",
          "sha1": "621098619086181b671f24614fed75e3e31e8e27",
          "md5": "e0b94cbdfaea4fcf0ff9b11468e4feb2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "window-core-1.3.0-versionMetadata.json",
          "size": 1419,
          "sha512": "b49f81c8bc6bbcdf34e822614a2d2af148af319ab223726342cc96b2e97d3f9d54ce13a449f4915db44e92eccc155461b8240e5bd37e0b789d74355c1641028d",
          "sha256": "963a43c481d19c1802aaabad466e3b478a4624db33ae92b0520c8160396f6e7b",
          "sha1": "f749102324e22675f35ee15dd82e269525fb3139",
          "md5": "303ee5130d810b3be8e6bf808be6a456"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-metadata-1.3.0.jar",
          "url": "window-core-1.3.0.jar",
          "size": 712,
          "sha512": "03ec0aa32acc1111d0757951d3f8cdb1605e622eb76b5812ce87319849c5c8af7407859d78a68579a74dcac19649d4a06bdbf4128afbfa290cf2a280ee139edc",
          "sha256": "3cc622558f9fe0dce8af12224f3ec921df332f67a416714bb66aea7faa6b21dc",
          "sha1": "b7681a3589145c47343475c0d21afd3fe9d774e6",
          "md5": "5104c291bea52a0d064b2b52d1ccc0e7"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-kotlin-1.3.0-sources.jar",
          "url": "window-core-1.3.0-sources.jar",
          "size": 6622,
          "sha512": "898195ac76629ed47cff61b4639fddfdfa9d5a3bf87da1c518d32b34ec436cd686d5bc832ef5633310a7f39ee0599f2d9439ec3445258c43879b3146551009ef",
          "sha256": "e4d610026c5948895c432870c7b5398887c00d8c531810e051248498d47fec14",
          "sha1": "8d965c472ab77d3235e76a505df297e61f967796",
          "md5": "c0b654c2ed276d43cb1344d8dcc0af59"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../window-core-android/1.3.0/window-core-android-1.3.0.module",
        "group": "androidx.window",
        "module": "window-core-android",
        "version": "1.3.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../window-core-android/1.3.0/window-core-android-1.3.0.module",
        "group": "androidx.window",
        "module": "window-core-android",
        "version": "1.3.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../window-core-android/1.3.0/window-core-android-1.3.0.module",
        "group": "androidx.window",
        "module": "window-core-android",
        "version": "1.3.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-jvm/1.3.0/window-core-jvm-1.3.0.module",
        "group": "androidx.window",
        "module": "window-core-jvm",
        "version": "1.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-jvm/1.3.0/window-core-jvm-1.3.0.module",
        "group": "androidx.window",
        "module": "window-core-jvm",
        "version": "1.3.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-jvm/1.3.0/window-core-jvm-1.3.0.module",
        "group": "androidx.window",
        "module": "window-core-jvm",
        "version": "1.3.0"
      }
    }
  ]
}