{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-proto",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.0.0-alpha08.jar",
          "url": "protolayout-proto-1.0.0-alpha08.jar",
          "size": 1709725,
          "sha512": "9184602c7f98898ec4b450ed5599eb1261743f993f8e2485556f6ed7d6777074a12c4a7e58d97154c347d56a4f957ba6e426f139c56e37a943b3dd127c8c32e5",
          "sha256": "7f5507d53bdb2de69fad8df75d04a3d10ce1138b5ff82261f38b8ba48cf53ef6",
          "sha1": "ce8443d8fd1af98d89790f91a406b964fcae6379",
          "md5": "3f0d2574fe3b37aa3eecdb398035b521"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.0.0-alpha08.jar",
          "url": "protolayout-proto-1.0.0-alpha08.jar",
          "size": 1709725,
          "sha512": "9184602c7f98898ec4b450ed5599eb1261743f993f8e2485556f6ed7d6777074a12c4a7e58d97154c347d56a4f957ba6e426f139c56e37a943b3dd127c8c32e5",
          "sha256": "7f5507d53bdb2de69fad8df75d04a3d10ce1138b5ff82261f38b8ba48cf53ef6",
          "sha1": "ce8443d8fd1af98d89790f91a406b964fcae6379",
          "md5": "3f0d2574fe3b37aa3eecdb398035b521"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.0.0-alpha08.jar",
          "url": "protolayout-proto-1.0.0-alpha08.jar",
          "size": 1709725,
          "sha512": "9184602c7f98898ec4b450ed5599eb1261743f993f8e2485556f6ed7d6777074a12c4a7e58d97154c347d56a4f957ba6e426f139c56e37a943b3dd127c8c32e5",
          "sha256": "7f5507d53bdb2de69fad8df75d04a3d10ce1138b5ff82261f38b8ba48cf53ef6",
          "sha1": "ce8443d8fd1af98d89790f91a406b964fcae6379",
          "md5": "3f0d2574fe3b37aa3eecdb398035b521"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.0.0-alpha08-sources.jar",
          "url": "protolayout-proto-1.0.0-alpha08-sources.jar",
          "size": 472047,
          "sha512": "3b3402a6dd72614589cd7422831684e41e0ce996aadfff5d6977059f6dab53c90fb8d5ff706cba34299687cc8fd453a03305e0dbbf82638c59de56fdfeac11e2",
          "sha256": "4cb4035ac44cf17bd74d650528bedeba1cc593ad2d725b8ae33b6a6b0f90833d",
          "sha1": "f30aba6e2cfaaeb44f0ec1470177a9dd7f932bb6",
          "md5": "329d8100c869ef84eb3609b4d8fb4af0"
        }
      ]
    }
  ]
}