{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-apicompiler",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13243833"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core-external-protobuf",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-apicompiler-1.0.0-alpha13.jar",
          "url": "tools-apicompiler-1.0.0-alpha13.jar",
          "size": 72333,
          "sha512": "56323ff80ef796dfd63bcd30f3d70e58eae7bc01794e3772a0fe810e5f82713d67b883af25252b2e45fe8aef7bd0a0d94c0a60f64bcd2a4245d8c8f67319e2ff",
          "sha256": "a1ec4dd48f240866615ea8f99ca61a45518b8437f18f2c65ff083dfdc41fe1b7",
          "sha1": "37b38f4ac3e992237fbf93d671c9713892b5db30",
          "md5": "9eb43ba077c24376e8ecb41e55545774"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.10-1.0.24"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core-external-protobuf",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apicompiler-1.0.0-alpha13.jar",
          "url": "tools-apicompiler-1.0.0-alpha13.jar",
          "size": 72333,
          "sha512": "56323ff80ef796dfd63bcd30f3d70e58eae7bc01794e3772a0fe810e5f82713d67b883af25252b2e45fe8aef7bd0a0d94c0a60f64bcd2a4245d8c8f67319e2ff",
          "sha256": "a1ec4dd48f240866615ea8f99ca61a45518b8437f18f2c65ff083dfdc41fe1b7",
          "sha1": "37b38f4ac3e992237fbf93d671c9713892b5db30",
          "md5": "9eb43ba077c24376e8ecb41e55545774"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core-external-protobuf",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apicompiler-1.0.0-alpha13-sources.jar",
          "url": "tools-apicompiler-1.0.0-alpha13-sources.jar",
          "size": 20802,
          "sha512": "74a2b68a3d099022d5d3311aa3d66c9eabea2231035213647aa8fe15fb2141330ff652d141beef4846e26410e1d1196ed6048b9d0b38a6a4aeb0bc3dc4abc7ea",
          "sha256": "7e213d5391ff8d9e9e7c203d5813f73ea9b9a93a9eac4ee26e8560d1aa4be1d8",
          "sha1": "a86f0076572f5da2a00d24d4eff3f1e65f240bee",
          "md5": "4371f7e8ed398ff02160e0b26ebe2dba"
        }
      ]
    }
  ]
}