{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.1.0-beta01.aar",
          "url": "runtime-1.1.0-beta01.aar",
          "size": 1891942,
          "sha512": "3b3a86e863c7e614e881301e1564e40d76da436bcbb8805af87249cf49e7532c12f8ba6236d89e05e7a4d4460c29dfad9dc3df3662ab98ee0e1f182ffbdc40e2",
          "sha256": "53a98768dcbf801f647043f214927470d2488bcdb92114e448234733b0579f65",
          "sha1": "6d5c5e2b803c97d7ba9e90b0967735820deef8e0",
          "md5": "5fbc0f4daa79de479fe73de21f04acb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.1.0-beta01.aar",
          "url": "runtime-1.1.0-beta01.aar",
          "size": 1891942,
          "sha512": "3b3a86e863c7e614e881301e1564e40d76da436bcbb8805af87249cf49e7532c12f8ba6236d89e05e7a4d4460c29dfad9dc3df3662ab98ee0e1f182ffbdc40e2",
          "sha256": "53a98768dcbf801f647043f214927470d2488bcdb92114e448234733b0579f65",
          "sha1": "6d5c5e2b803c97d7ba9e90b0967735820deef8e0",
          "md5": "5fbc0f4daa79de479fe73de21f04acb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.1.0-beta01-sources.jar",
          "url": "runtime-1.1.0-beta01-sources.jar",
          "size": 257626,
          "sha512": "ccb0c0705dbd797b5543e0d8668c610d4ca47851eb8750e30bb9f28b70192b94064b02b6db7eff3556c93afb2d3d4fd48776d450a10b98511ce85f2c24e31832",
          "sha256": "92fedc7936795248f6a3b9194c141c0a362ee1fc0bee0e524eae37510e2da079",
          "sha1": "f9ad128b8992ca70e4a1cdc983a03ed6516fab78",
          "md5": "7e40eb147c31c65679718b8e2e2d6250"
        }
      ]
    }
  ]
}
