{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.7.8/material-ripple-1.7.8.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.8"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.7.8.aar",
          "size": 96135,
          "sha512": "5c1a4a002264392b8fa7ecfed451c7fa0b4bd76a9e642e7dab4a83aa7e0e2c2cb0d04d37b2846001b9bb33e4c039a3ad3038eb08b8552bd4d2ed01d0229fd26f",
          "sha256": "e163a0f5ddc9ef0e232444b8bfd16476453eb685508be0df0785eb4fc43feb4d",
          "sha1": "e877fb65f8c9209e8f21078396b68bb8c2087740",
          "md5": "a22e0a8dc07f05cfd38a13e6b6159c0d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.8"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.7.8.aar",
          "size": 96135,
          "sha512": "5c1a4a002264392b8fa7ecfed451c7fa0b4bd76a9e642e7dab4a83aa7e0e2c2cb0d04d37b2846001b9bb33e4c039a3ad3038eb08b8552bd4d2ed01d0229fd26f",
          "sha256": "e163a0f5ddc9ef0e232444b8bfd16476453eb685508be0df0785eb4fc43feb4d",
          "sha1": "e877fb65f8c9209e8f21078396b68bb8c2087740",
          "md5": "a22e0a8dc07f05cfd38a13e6b6159c0d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-ripple-android-1.7.8-sources.jar",
          "url": "material-ripple-android-1.7.8-sources.jar",
          "size": 26493,
          "sha512": "cf75021625684728c83771b88735b3c52e328994c7adca1b415f16d3a433253c8775f06626aa791bfaa025a992577e661fd2645eab2fa4ad264e86352921ec52",
          "sha256": "ef8710a7152243363ce61099827c5e07618dd2911032311da38b0275cdebea4e",
          "sha1": "7850da88009864d77e29340230e91bcb270656d9",
          "md5": "fb144e81bbdee600bd3575d47e6c4d76"
        }
      ]
    }
  ]
}