{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-common-deps",
    "version": "2.0.20-RC2-1.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.0.20-RC2-1.0.24.jar",
          "url": "symbol-processing-common-deps-2.0.20-RC2-1.0.24.jar",
          "size": 112928,
          "sha512": "6dd8fa6548d175d7a73977ca04e2aaa00ebfffb941d2625537ec2449421ddfb97f6eefcbbe6ab59fa5b1150c7397bbacffd5bba75dbd6860ea4877ffdc786f76",
          "sha256": "50ebbcee8bd26a02abf41dcc19bcc19a0924e86417be6a87ddeff1f9acd87a12",
          "sha1": "12a92c6cd587ef655554b91377678e4f6e5b2baa",
          "md5": "df937fa38940b322de5fe750185ea176"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-2.0.20-RC2-1.0.24.jar",
          "url": "symbol-processing-common-deps-2.0.20-RC2-1.0.24.jar",
          "size": 112928,
          "sha512": "6dd8fa6548d175d7a73977ca04e2aaa00ebfffb941d2625537ec2449421ddfb97f6eefcbbe6ab59fa5b1150c7397bbacffd5bba75dbd6860ea4877ffdc786f76",
          "sha256": "50ebbcee8bd26a02abf41dcc19bcc19a0924e86417be6a87ddeff1f9acd87a12",
          "sha1": "12a92c6cd587ef655554b91377678e4f6e5b2baa",
          "md5": "df937fa38940b322de5fe750185ea176"
        }
      ]
    }
  ]
}
