{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-swing",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-swing-1.7.3.jar",
          "url": "kotlinx-coroutines-swing-1.7.3.jar",
          "size": 9964,
          "sha512": "2f8b3ac41da336c3094220444f2fdb686b7cd8f90d333e8e9cb068ec0c92da51bcb24169bfecab01afdfe3266096be2518e2e28de3c9f73618febea43fea859b",
          "sha256": "3145fd68ad71ec6100924f74f1b6d52d22250dc2771a56b4f164c2a22fb50cac",
          "sha1": "c3975fa866818bde607ed16bbae9ad52bb5972b8",
          "md5": "9d786da62547d2853d641e5a65f8355d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-swing-1.7.3.jar",
          "url": "kotlinx-coroutines-swing-1.7.3.jar",
          "size": 9964,
          "sha512": "2f8b3ac41da336c3094220444f2fdb686b7cd8f90d333e8e9cb068ec0c92da51bcb24169bfecab01afdfe3266096be2518e2e28de3c9f73618febea43fea859b",
          "sha256": "3145fd68ad71ec6100924f74f1b6d52d22250dc2771a56b4f164c2a22fb50cac",
          "sha1": "c3975fa866818bde607ed16bbae9ad52bb5972b8",
          "md5": "9d786da62547d2853d641e5a65f8355d"
        }
      ]
    }
  ]
}
