{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-material",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-material-1.2.0-sources.jar",
          "url": "protolayout-material-1.2.0-sources.jar",
          "size": 63225,
          "sha512": "aa9b17fe7f7d58352b418a8bca83116441c044cc18b308b046e1828e897ab924ef281621c382056169b16aff74473a1e7ccf9055986b2ebb627d6d528cb8a082",
          "sha256": "7cdcb2e79f3bb79eea387990f0afe986a0b8d79661326c1ddaf17bf7c3df4d8f",
          "sha1": "576e8070e73bd4bf6d9b44d1d952d7ec2739cae0",
          "md5": "9a2a42d96277832566890b62b0a4a41f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-material-1.2.0.aar",
          "url": "protolayout-material-1.2.0.aar",
          "size": 90199,
          "sha512": "bca2090ab4180b3af90a27491db090f8d6d9a66f8d029e06675bc4627142ddbea1a3d7dde69502f29363ddebeba0e0ed960cbf327ee273cafdb27c85e3a5f573",
          "sha256": "02cebc0fbdee629b23f68ccf4b07e40bba4d1625be08eb85fbfdc5436e178c50",
          "sha1": "15a5dc347da9bca65a0a87dcb1cceec092466adb",
          "md5": "5df4c3aea3b81c61994ddb3be6c58ce8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-material-1.2.0.aar",
          "url": "protolayout-material-1.2.0.aar",
          "size": 90199,
          "sha512": "bca2090ab4180b3af90a27491db090f8d6d9a66f8d029e06675bc4627142ddbea1a3d7dde69502f29363ddebeba0e0ed960cbf327ee273cafdb27c85e3a5f573",
          "sha256": "02cebc0fbdee629b23f68ccf4b07e40bba4d1625be08eb85fbfdc5436e178c50",
          "sha1": "15a5dc347da9bca65a0a87dcb1cceec092466adb",
          "md5": "5df4c3aea3b81c61994ddb3be6c58ce8"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-material-1.2.0-versionMetadata.json",
          "url": "protolayout-material-1.2.0-versionMetadata.json",
          "size": 20064,
          "sha512": "d674d6c708ed539904814e6ea2d2c61028d029600d1ba77b402e1dcf9ba48640c4fb5a10a9f2c88f040a95c63086098abf644ca822d207057317838f85492cf4",
          "sha256": "909236d5a74894776b3a61da2d0c3af282507b8a8f524cf65de16c894219ab0f",
          "sha1": "8452c185344e4430c6b3a3080571fee131d11227",
          "md5": "07bcb25de380846e4c688c92f8cdcf0c"
        }
      ]
    }
  ]
}