{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ui",
    "module": "ui-vector",
    "version": "0.1.0-dev13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6519275"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-runtime",
          "version": {
            "requires": "0.1.0-dev13"
          }
        }
      ],
      "files": [
        {
          "name": "ui-vector-0.1.0-dev13.aar",
          "url": "ui-vector-0.1.0-dev13.aar",
          "size": 29698,
          "sha512": "8e55c0f8bd219cc048cc75733b2f4c4a00ba13f12fb4bbd69ff55cdbfc046133c47b2dcb89ada4fae3bec5fc3ec7d479668526e5c220d33dd3451f579f3d539c",
          "sha256": "f79dd7f7a191f6cd3304f31b7a34883bfa99780d0de8ab524b57a6c8af670480",
          "sha1": "e0a31f80802a31ad231a5e5dc3b871e2e6bbd492",
          "md5": "c05308eeb03f7522bf583812d67f0c51"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-runtime",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-util",
          "version": {
            "requires": "0.1.0-dev13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "ui-vector-0.1.0-dev13.aar",
          "url": "ui-vector-0.1.0-dev13.aar",
          "size": 29698,
          "sha512": "8e55c0f8bd219cc048cc75733b2f4c4a00ba13f12fb4bbd69ff55cdbfc046133c47b2dcb89ada4fae3bec5fc3ec7d479668526e5c220d33dd3451f579f3d539c",
          "sha256": "f79dd7f7a191f6cd3304f31b7a34883bfa99780d0de8ab524b57a6c8af670480",
          "sha1": "e0a31f80802a31ad231a5e5dc3b871e2e6bbd492",
          "md5": "c05308eeb03f7522bf583812d67f0c51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-vector-0.1.0-dev13-sources.jar",
          "url": "ui-vector-0.1.0-dev13-sources.jar",
          "size": 5628,
          "sha512": "11fbc65e221172bbc356acdac20cebb2281100fca1ddaada6efc57291493d46f5a06a89a153364780cd227ebeebfa0141b513c79632e2bb3cd06f71fb07495c9",
          "sha256": "aeaca8b15a89af658e31611da23b9fe788d27e338741072eabfdd30ddb872a38",
          "sha1": "0d595a83f825526227085a20bdebae8003e35bbe",
          "md5": "48b2333d232d929a056865dcc426ed2d"
        }
      ]
    }
  ]
}
