{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.1.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.1.0-rc01.aar",
          "url": "runtime-1.1.0-rc01.aar",
          "size": 1899155,
          "sha512": "838edb2202619c180e66df08243fa0820dcec2a4579278900b5051673df6d0c76b3266bfd03a2f903c997e27695e656d4c9b5a306e27c5134d3e2afb25d5e7de",
          "sha256": "2d9c023f6cd67de5c9d46df2d51beb8ad52c0edbaa91154f2178edea737c6ec8",
          "sha1": "0b86c7e98ac7ed922e61b21637b50a59f6ba0e80",
          "md5": "7eed06f3df725e6fbc73391096de59ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.1.0-rc01.aar",
          "url": "runtime-1.1.0-rc01.aar",
          "size": 1899155,
          "sha512": "838edb2202619c180e66df08243fa0820dcec2a4579278900b5051673df6d0c76b3266bfd03a2f903c997e27695e656d4c9b5a306e27c5134d3e2afb25d5e7de",
          "sha256": "2d9c023f6cd67de5c9d46df2d51beb8ad52c0edbaa91154f2178edea737c6ec8",
          "sha1": "0b86c7e98ac7ed922e61b21637b50a59f6ba0e80",
          "md5": "7eed06f3df725e6fbc73391096de59ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.1.0-rc01-sources.jar",
          "url": "runtime-1.1.0-rc01-sources.jar",
          "size": 261653,
          "sha512": "4944adef5d3cc5ffb60de5873eb41895fe326f5c29918117681542089350d30911a25a3d3281aa34b6e7a98b7dfea8853891c2b2905c934252350f645836fbef",
          "sha256": "f6bb44395e7491b111f9d5cbfc03e643f3422f4e8051f3d4c98ce9cb104b98fd",
          "sha1": "66e27f29dcf818e88cec9fe9a478a00ba1ee1278",
          "md5": "61d8f4fe36251545eb58ddd601e6fc31"
        }
      ]
    }
  ]
}
