{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-markdown-ide-laf-bridge-styling-242",
    "version": "0.24.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-markdown-core-242",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ide-laf-bridge-242",
          "version": {
            "requires": "0.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-ide-laf-bridge-styling-242-0.24.2.jar",
          "url": "jewel-markdown-ide-laf-bridge-styling-242-0.24.2.jar",
          "size": 29076,
          "sha512": "e9c462b6de747c145ac0ce54769d28105ec054624783baf54872317cff8f5dc1ae5b490bcdbc478c5db95a490adbe729f20d7c5aaf0107d9c579448a982c26cb",
          "sha256": "3c0a2c524222dcbabeb3eebf544013a0aa0d036a2fedd14759c5f99b7c9ce68a",
          "sha1": "591dc5fdf7bb6169a72a034c67c5509c32f5849f",
          "md5": "c6b9bc2b412ea196529000148c6111f4"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-markdown-core-242",
          "version": {
            "requires": "0.24.2"
          }
        },
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ide-laf-bridge-242",
          "version": {
            "requires": "0.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-ide-laf-bridge-styling-242-0.24.2.jar",
          "url": "jewel-markdown-ide-laf-bridge-styling-242-0.24.2.jar",
          "size": 29076,
          "sha512": "e9c462b6de747c145ac0ce54769d28105ec054624783baf54872317cff8f5dc1ae5b490bcdbc478c5db95a490adbe729f20d7c5aaf0107d9c579448a982c26cb",
          "sha256": "3c0a2c524222dcbabeb3eebf544013a0aa0d036a2fedd14759c5f99b7c9ce68a",
          "sha1": "591dc5fdf7bb6169a72a034c67c5509c32f5849f",
          "md5": "c6b9bc2b412ea196529000148c6111f4"
        }
      ]
    }
  ]
}
