{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark-android",
    "version": "2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark",
          "version": {
            "requires": "2.14"
          }
        }
      ],
      "files": [
        {
          "name": "shark-android-2.14.jar",
          "url": "shark-android-2.14.jar",
          "size": 396374,
          "sha512": "32b9675d60b4b05e38da3ab974531c9d60d774d3d97f816762f1511d150f368fa421b7fe4711c0d6c78cf548501a20ade6272d14490ec6a82f4be8519d9ef580",
          "sha256": "b79dfb05903e69018d598bb4da4f41e0f7732a585cb66a0a5ffb5b89d2076c72",
          "sha1": "6fb0b4ab27c085678a3d26ce2b9350fb77c32407",
          "md5": "928a29af8139429c51cb1dc36e523363"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark",
          "version": {
            "requires": "2.14"
          }
        }
      ],
      "files": [
        {
          "name": "shark-android-2.14.jar",
          "url": "shark-android-2.14.jar",
          "size": 396374,
          "sha512": "32b9675d60b4b05e38da3ab974531c9d60d774d3d97f816762f1511d150f368fa421b7fe4711c0d6c78cf548501a20ade6272d14490ec6a82f4be8519d9ef580",
          "sha256": "b79dfb05903e69018d598bb4da4f41e0f7732a585cb66a0a5ffb5b89d2076c72",
          "sha1": "6fb0b4ab27c085678a3d26ce2b9350fb77c32407",
          "md5": "928a29af8139429c51cb1dc36e523363"
        }
      ]
    }
  ]
}
