{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-int-ui-standalone-241",
    "version": "0.19.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-241",
          "version": {
            "requires": "0.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-int-ui-standalone-241-0.19.3.jar",
          "url": "jewel-int-ui-standalone-241-0.19.3.jar",
          "size": 3789765,
          "sha512": "03a65918905365993894b95341689ac82075d529f55d74695880ebfe77eab5f961c9db345cde2a0d20a490b1e46312172a3571a81197bc1183c61091588a14de",
          "sha256": "951ce29027723cd263b25c6f926b9c48a57d3f48fd3470b14c559835ef843e8c",
          "sha1": "7da5da906e28fb950477f127a10ccbd0b0e18ac7",
          "md5": "033f4f58cd8de4dbf583b973ab0e26b2"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-241",
          "version": {
            "requires": "0.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-int-ui-standalone-241-0.19.3.jar",
          "url": "jewel-int-ui-standalone-241-0.19.3.jar",
          "size": 3789765,
          "sha512": "03a65918905365993894b95341689ac82075d529f55d74695880ebfe77eab5f961c9db345cde2a0d20a490b1e46312172a3571a81197bc1183c61091588a14de",
          "sha256": "951ce29027723cd263b25c6f926b9c48a57d3f48fd3470b14c559835ef843e8c",
          "sha1": "7da5da906e28fb950477f127a10ccbd0b0e18ac7",
          "md5": "033f4f58cd8de4dbf583b973ab0e26b2"
        }
      ]
    }
  ]
}
