{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.concurrent",
    "module": "concurrent-futures-ktx",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "concurrent-futures-ktx is in atomic group androidx.concurrent"
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-ktx-1.2.0-alpha03.jar",
          "url": "concurrent-futures-ktx-1.2.0-alpha03.jar",
          "size": 11675,
          "sha512": "02179de20860b20531a433bfc45671fc938d6c45479ae328801a70f5c12984e6fa6289c777cf614ee87a508f7fa94c8ac25bc03cd16ca4ddf9a838087ed68775",
          "sha256": "2945609993b3e5e712c2cb1b08ab1bac4d60702f079d4d7d74544019ae44d1bd",
          "sha1": "33bfff0b4d1b25c76bd2d355fec8f188d7bae241",
          "md5": "f455cf7fc3cc2d0736f6c19da476ef67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "concurrent-futures-ktx is in atomic group androidx.concurrent"
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-ktx-1.2.0-alpha03.jar",
          "url": "concurrent-futures-ktx-1.2.0-alpha03.jar",
          "size": 11675,
          "sha512": "02179de20860b20531a433bfc45671fc938d6c45479ae328801a70f5c12984e6fa6289c777cf614ee87a508f7fa94c8ac25bc03cd16ca4ddf9a838087ed68775",
          "sha256": "2945609993b3e5e712c2cb1b08ab1bac4d60702f079d4d7d74544019ae44d1bd",
          "sha1": "33bfff0b4d1b25c76bd2d355fec8f188d7bae241",
          "md5": "f455cf7fc3cc2d0736f6c19da476ef67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "concurrent-futures-ktx is in atomic group androidx.concurrent"
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-ktx-1.2.0-alpha03-sources.jar",
          "url": "concurrent-futures-ktx-1.2.0-alpha03-sources.jar",
          "size": 4902,
          "sha512": "313dc67422afa5c07c65ece97866f1ee38b6c8c200fc1180b67e7224d9a71a961d8ab3ecb8fa0428536700305699194c2b7a51f49635b9b280720d8b2aa75c07",
          "sha256": "149e92668921f354e3f3f19d856647217676e4871215e2c933a1f074968e3aa2",
          "sha1": "75a821870ee27c8257e4201a07a65bc03e99ee6c",
          "md5": "2968089ea98972378ac688c4204c440b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "concurrent-futures-ktx is in atomic group androidx.concurrent"
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-ktx-1.2.0-alpha03-versionMetadata.json",
          "url": "concurrent-futures-ktx-1.2.0-alpha03-versionMetadata.json",
          "size": 623,
          "sha512": "c14e9d171cf7e6bde5b2b185607fd1680ffa29ee32679a3d3d0ca4b4c6db2210cb218fb50e8e03d2636bd6a5983146eb079a9f79d116b7120bdab99f473e63b8",
          "sha256": "368ee43424c7997b93fa9ad602546fa189cd506992af5a767f56b9f5dfafedf7",
          "sha1": "fb758bd1d8510c19793e7ecf1b8028b58f0e0e6e",
          "md5": "07aeef731248277f1e3d6760e489b5a8"
        }
      ]
    }
  ]
}