{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "tiles-1.1.0.aar",
          "url": "tiles-1.1.0.aar",
          "size": 213450,
          "sha512": "72430904ae075f692061fe76dd632e3904432951439b59102bd205aed40ff88d39c5b675c55565ed5454747ab2e836bcbd0a9cdddfc7370e3ce1719043ba88d7",
          "sha256": "d869b13f1b1cdccc1bb302fa965fbe7e4a609d018b7e4d08d75bdf490b440d6b",
          "sha1": "945da6d1b23268a49c85909bc21e994d26c11272",
          "md5": "74893f7ce667435a12d28ad2822127d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "tiles-1.1.0.aar",
          "url": "tiles-1.1.0.aar",
          "size": 213450,
          "sha512": "72430904ae075f692061fe76dd632e3904432951439b59102bd205aed40ff88d39c5b675c55565ed5454747ab2e836bcbd0a9cdddfc7370e3ce1719043ba88d7",
          "sha256": "d869b13f1b1cdccc1bb302fa965fbe7e4a609d018b7e4d08d75bdf490b440d6b",
          "sha1": "945da6d1b23268a49c85909bc21e994d26c11272",
          "md5": "74893f7ce667435a12d28ad2822127d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiles-1.1.0-sources.jar",
          "url": "tiles-1.1.0-sources.jar",
          "size": 59421,
          "sha512": "669a5b8cbcb1c7f2687fe184ca1be3fdb5beb59835c9203d5b21198f00c5401826bef1d0854642729e660c6a7ad0edf074b5f4cb24d8a43348581f93ba088a9e",
          "sha256": "a72d68689c9169333e6c1daf083e105fda8cfa65e18ddab77688da39d45e6e81",
          "sha1": "3e83914891dc79f15d479f30c821c2e1560e41c4",
          "md5": "f0b57464e8e3e05676a11085c70ace48"
        }
      ]
    }
  ]
}