{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.6.20-dev1663/runtime-1.6.20-dev1663.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "1.6.20-dev1663",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.6.20-dev1663.jar",
          "url": "runtime-desktop-1.6.20-dev1663.jar",
          "size": 1316944,
          "sha512": "1775bfadc9dffee89c7b52a955cc31354c1adc0fe71edab956df78288948cdbd304db62f3a032033c5be08a7465e8d3489ec9e23722670a50e6040e8d501dcd3",
          "sha256": "66c97d0d48ac8852ed2780de5a747ea94a26c29b37196e23e6225502a2a09c96",
          "sha1": "328c18df89b7bf14a52d2d39e20065b029cdfeeb",
          "md5": "c40c7435bd1b5e7358975e707f9755b4"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.collection-internal",
          "module": "collection",
          "version": {
            "requires": "1.6.20-dev1663"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.6.20-dev1663.jar",
          "url": "runtime-desktop-1.6.20-dev1663.jar",
          "size": 1316944,
          "sha512": "1775bfadc9dffee89c7b52a955cc31354c1adc0fe71edab956df78288948cdbd304db62f3a032033c5be08a7465e8d3489ec9e23722670a50e6040e8d501dcd3",
          "sha256": "66c97d0d48ac8852ed2780de5a747ea94a26c29b37196e23e6225502a2a09c96",
          "sha1": "328c18df89b7bf14a52d2d39e20065b029cdfeeb",
          "md5": "c40c7435bd1b5e7358975e707f9755b4"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "runtime-desktop-1.6.20-dev1663-sources.jar",
          "url": "runtime-desktop-1.6.20-dev1663-sources.jar",
          "size": 369613,
          "sha512": "57317fe7c26228a5ceee2edbd445148adfce4183caeee6b2a4fb007f8024bf11abde68ddb1ac4e1e19cd6579aefa17ae232ad66ce2249997a154c948a9c7ea95",
          "sha256": "a58044ad619e3fe9fb913552a18dbc3b2ef0622ad0acf88a28bb293f5de26d48",
          "sha1": "7ab3ddeb8d14867ab8a220e09592ee6792cd7c7f",
          "md5": "0dda92ca4d2d90d3b9a07ee0448849d5"
        }
      ]
    }
  ]
}