{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.2.0.aar",
          "url": "animation-core-1.2.0.aar",
          "size": 1317063,
          "sha512": "fb906ae2b12cc740981d4de49ecb9588a9668dbdb580f63dbcced60d7e4f77886b3215a19b7e9f5a1e2a57434252addf1118e1dca5188c68286740842a68baa4",
          "sha256": "2f96f81b1487c459aa6edbfc4cc8b69560b318b0535a909bdd81a4b679ca5a04",
          "sha1": "64d07983ef4d26f1ef7b4ed07a116cc56b6953ba",
          "md5": "c6958319b5e62c3894e010a230047688"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.2.0.aar",
          "url": "animation-core-1.2.0.aar",
          "size": 1317063,
          "sha512": "fb906ae2b12cc740981d4de49ecb9588a9668dbdb580f63dbcced60d7e4f77886b3215a19b7e9f5a1e2a57434252addf1118e1dca5188c68286740842a68baa4",
          "sha256": "2f96f81b1487c459aa6edbfc4cc8b69560b318b0535a909bdd81a4b679ca5a04",
          "sha1": "64d07983ef4d26f1ef7b4ed07a116cc56b6953ba",
          "md5": "c6958319b5e62c3894e010a230047688"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-1.2.0-sources.jar",
          "url": "animation-core-1.2.0-sources.jar",
          "size": 74207,
          "sha512": "32c9c2e608bc7e1c9e625430705532231afbde5aaebd5297522515872b565b2ac740db28f5f6199b090abff82d641e72c8bb0ce0af659834cc3c163319f683bf",
          "sha256": "5a78ea0c21fcec353224df92a183e3f3d9cae2edf0a1bdd9e064f66c5256736a",
          "sha1": "b26878d76e40d5669dd2e7081c64b3fbf9520a37",
          "md5": "37c7d6dd654de519a51d7f3eb020c47c"
        }
      ]
    }
  ]
}