{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.0.0.aar",
          "url": "runtime-1.0.0.aar",
          "size": 1859197,
          "sha512": "7a5c0fe977a5bbe25dd54dde58fa73a1c8d491dd2f1aed48bab334f2ff77e60036a659cbe8b56859123ac1f4b09f9624d5eb414c8c3b1df8e8b8652eee04ca4f",
          "sha256": "6f1b4762fb8db93506aae72555ed2da1ee6bcfe0acb80dd9053868807422a5f1",
          "sha1": "d6d05d9b71518aa284f2aae5c6079f661fc9877c",
          "md5": "42e1765574771860841ecfbf5ce27fa9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.0.0.aar",
          "url": "runtime-1.0.0.aar",
          "size": 1859197,
          "sha512": "7a5c0fe977a5bbe25dd54dde58fa73a1c8d491dd2f1aed48bab334f2ff77e60036a659cbe8b56859123ac1f4b09f9624d5eb414c8c3b1df8e8b8652eee04ca4f",
          "sha256": "6f1b4762fb8db93506aae72555ed2da1ee6bcfe0acb80dd9053868807422a5f1",
          "sha1": "d6d05d9b71518aa284f2aae5c6079f661fc9877c",
          "md5": "42e1765574771860841ecfbf5ce27fa9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.0.0-sources.jar",
          "url": "runtime-1.0.0-sources.jar",
          "size": 254697,
          "sha512": "8a5512217883632bd2deea8dca1ffc892d341943d9db0f97a8d0163ff4c3fc313c87024e4523dc3269f81d9e49e7076fb6c5fe7c4a07e03508bf433000023994",
          "sha256": "bfcdc6358bd9ec196081c03f5e658b1e37889d727c81603dfe0ea082c16cbe2c",
          "sha1": "41ccda0746740fa72d5f42b1f456478ebc677938",
          "md5": "116985eddc13fe5bb559b31c39b8fe07"
        }
      ]
    }
  ]
}
