{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ui",
    "module": "ui-test",
    "version": "1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6841119"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-dispatch",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-1.0.0-alpha04.aar",
          "url": "ui-test-1.0.0-alpha04.aar",
          "size": 293633,
          "sha512": "a02c12ab9ef76c494a314294604c7cf11bafc4f357644608e6e7df16949dd38d93d64ebd7697359a00dc8d5f3f43b815d2371fbab26d799682912f3accf79b6a",
          "sha256": "b2686b474f8943e27eae3b5142e24bc8bfd48b2f21557731f2949c43cd9b24ad",
          "sha1": "9d81ad3079ef8f9cf5bc46446d9be32d18cd2b9f",
          "md5": "2de38c2898ecc2efa5229620e60b2372"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-dispatch",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-text",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saved-instance-state",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-1.0.0-alpha04.aar",
          "url": "ui-test-1.0.0-alpha04.aar",
          "size": 293633,
          "sha512": "a02c12ab9ef76c494a314294604c7cf11bafc4f357644608e6e7df16949dd38d93d64ebd7697359a00dc8d5f3f43b815d2371fbab26d799682912f3accf79b6a",
          "sha256": "b2686b474f8943e27eae3b5142e24bc8bfd48b2f21557731f2949c43cd9b24ad",
          "sha1": "9d81ad3079ef8f9cf5bc46446d9be32d18cd2b9f",
          "md5": "2de38c2898ecc2efa5229620e60b2372"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-1.0.0-alpha04-sources.jar",
          "url": "ui-test-1.0.0-alpha04-sources.jar",
          "size": 220083,
          "sha512": "b62c5439a85e1d8c831a92c95e7f4bd8df7e0c2d5cf3e0d72e8548467a6e1eb1eb94888409991d88247f7596e662ea34ad0d280db6e9eb6c161a703d518c6207",
          "sha256": "dc40b2077d72c4c2af5e9b43543e024caaf1eaa195d0bbf98692346e73b348ec",
          "sha1": "ab1686e10692995952e16917df755d53cf870ca5",
          "md5": "a99f9e4a4bcd2253dc4c801111831325"
        }
      ]
    }
  ]
}
