{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools",
    "module": "common",
    "version": "30.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "common-30.0.0.jar",
          "url": "common-30.0.0.jar",
          "size": 355248,
          "sha512": "f8a747ce22608e6750a9216e0b7cfc98058742f7b13dbfe68324bbccda577b12968759faff685aac631063aa60a1e6f2ca885bdab4b18a1b4fc7317d786549e2",
          "sha256": "a10ee126f298184a14694cb4a73cfa9b6ba1d39b1e0d086bfed91c04547b0c4a",
          "sha1": "b4fa93251c2f6d0ff6b87ddff8f35301cb9508f4",
          "md5": "976552201f56bfc8ad34612c18f16f7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "common-30.0.0.jar",
          "url": "common-30.0.0.jar",
          "size": 355248,
          "sha512": "f8a747ce22608e6750a9216e0b7cfc98058742f7b13dbfe68324bbccda577b12968759faff685aac631063aa60a1e6f2ca885bdab4b18a1b4fc7317d786549e2",
          "sha256": "a10ee126f298184a14694cb4a73cfa9b6ba1d39b1e0d086bfed91c04547b0c4a",
          "sha1": "b4fa93251c2f6d0ff6b87ddff8f35301cb9508f4",
          "md5": "976552201f56bfc8ad34612c18f16f7b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-30.0.0-javadoc.jar",
          "url": "common-30.0.0-javadoc.jar",
          "size": 892205,
          "sha512": "6648657bc8906f897e30f42fc78bb51ff272fc0028181e9117b170a2bd9aabcaf03f06d55c6d741fff9d2bb36a51e357bcfc431ea69c7e13ba6110947b1e0f94",
          "sha256": "38b1d283ec7d38aab2105dc5d88581e125943bf704c492b723d057d69de11792",
          "sha1": "8000629073cf98e0b2e500ec187aa8462b57e42a",
          "md5": "ff5b283ece0ce42a4bfecae05fce0426"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-30.0.0-sources.jar",
          "url": "common-30.0.0-sources.jar",
          "size": 213404,
          "sha512": "acce093269d91f1bdba99ecd54f080f6be089d2481d97761bbcb8712475dcfd6cba2abed9dbb9a4e99c2f644dedf35b1d59ccaced9771e04893bb159a103deef",
          "sha256": "4fc8609841c192a5fa99b49def5438ac7bd7aced7bc11337ddf6554189b5faa2",
          "sha1": "c20088b46958a43bbc7b370b6de63ec2b631b933",
          "md5": "a196013b0db44ae0e9fe5e09e4da7606"
        }
      ]
    }
  ]
}
