{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tv",
    "module": "tv-foundation",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tv",
          "module": "tv-material",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "tv-foundation-1.0.0-alpha07.aar",
          "url": "tv-foundation-1.0.0-alpha07.aar",
          "size": 480123,
          "sha512": "904bee6f5304c89c5cb7d7a7229793bc980a4e80612bca858dd5d58e46390e3bb2d9cb64b225ef8913d852bcf8955003aa2f3bca92db8b4478e97cb8989c9214",
          "sha256": "ca2a37d401a76834b0ad543240ab9ca0e8512fd599e2765403174f157f6b33de",
          "sha1": "6bf70ab837febad0b2fb5e875ecb63c1785208c9",
          "md5": "e8a6e413715d9533cefd92ff1e40067d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tv",
          "module": "tv-material",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "tv-foundation-1.0.0-alpha07.aar",
          "url": "tv-foundation-1.0.0-alpha07.aar",
          "size": 480123,
          "sha512": "904bee6f5304c89c5cb7d7a7229793bc980a4e80612bca858dd5d58e46390e3bb2d9cb64b225ef8913d852bcf8955003aa2f3bca92db8b4478e97cb8989c9214",
          "sha256": "ca2a37d401a76834b0ad543240ab9ca0e8512fd599e2765403174f157f6b33de",
          "sha1": "6bf70ab837febad0b2fb5e875ecb63c1785208c9",
          "md5": "e8a6e413715d9533cefd92ff1e40067d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tv",
          "module": "tv-material",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "tv-foundation-1.0.0-alpha07-sources.jar",
          "url": "tv-foundation-1.0.0-alpha07-sources.jar",
          "size": 117328,
          "sha512": "4ebf90d8e3e89787fc7b96d2ba103fd0d6a2f7df53fa19dfb011dfe114631e921ed41ec7515c73724cd9cb3a91819b7555ff26eb98170af9e2dff106b438b63d",
          "sha256": "f9cda66ea961525977b0c8f69ba9a59b4ec10459c1d254b09cccaf63e724cd4a",
          "sha1": "3d61cd82e77e20a54d3c86b573e3eb3f41e78077",
          "md5": "a2e9fa68f085907817b3c8e14f5c52bf"
        }
      ]
    }
  ]
}