{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.3.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.5.0-rc01.aar",
          "url": "room-runtime-2.5.0-rc01.aar",
          "size": 237010,
          "sha512": "407a1c33bd10ed08f6b130b63007386b8e054bb14d6734404dadb60b25ae1ad2c72873418d6578dc9eaca2bfffb46dcc2ab479b58220174b3597c0d7511c9ac7",
          "sha256": "66bafa7bc6e9570e97aec05541fc766a9cf6a556afe005de4b78a3f8e9369841",
          "sha1": "cd9ef617de14a1813be568e1461acd1815554e5f",
          "md5": "da43fe833182a65eae08f422206549b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.3.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.5.0-rc01.aar",
          "url": "room-runtime-2.5.0-rc01.aar",
          "size": 237010,
          "sha512": "407a1c33bd10ed08f6b130b63007386b8e054bb14d6734404dadb60b25ae1ad2c72873418d6578dc9eaca2bfffb46dcc2ab479b58220174b3597c0d7511c9ac7",
          "sha256": "66bafa7bc6e9570e97aec05541fc766a9cf6a556afe005de4b78a3f8e9369841",
          "sha1": "cd9ef617de14a1813be568e1461acd1815554e5f",
          "md5": "da43fe833182a65eae08f422206549b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.5.0-rc01-sources.jar",
          "url": "room-runtime-2.5.0-rc01-sources.jar",
          "size": 88585,
          "sha512": "3a19e8fe505a248709e5e7aea4701366e7e23191babea856632338cc50ebc92742ba262a06feb88329f8510f9acf4663ec7112cff3748b7faa2e37974bb6641f",
          "sha256": "972bd3b112dd84dedb58d7ee26ac62f8b821b36e7ba215ff98557bf48ac46f3d",
          "sha1": "8ba2410a7a67667a7cb11ca0a9be8db5237d8942",
          "md5": "deb9656bbcad99b1054acdd54320aa95"
        }
      ]
    }
  ]
}