{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-graphics/1.5.11/ui-graphics-1.5.11.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "1.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.85.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-desktop-1.5.11.jar",
          "url": "ui-graphics-desktop-1.5.11.jar",
          "size": 417793,
          "sha512": "ae7a732777764e2e55b394c3075267b0b17c4e3d1cec7738342755f03acdf6f9472c03f2a23ffd76465f7bb8ba83cb3c7ca8bfa84614c8b23e61f5ba6c15ba98",
          "sha256": "94cb91181e016926ffcd519ec7ac9f3d5f9378f94111f176f4034ae8d12cdcdf",
          "sha1": "694e3a460d5fc15245b2502ae4025113f132abb2",
          "md5": "4fb9044ccc44d19adb5b511fb18acd82"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.5.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.85.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-desktop-1.5.11.jar",
          "url": "ui-graphics-desktop-1.5.11.jar",
          "size": 417793,
          "sha512": "ae7a732777764e2e55b394c3075267b0b17c4e3d1cec7738342755f03acdf6f9472c03f2a23ffd76465f7bb8ba83cb3c7ca8bfa84614c8b23e61f5ba6c15ba98",
          "sha256": "94cb91181e016926ffcd519ec7ac9f3d5f9378f94111f176f4034ae8d12cdcdf",
          "sha1": "694e3a460d5fc15245b2502ae4025113f132abb2",
          "md5": "4fb9044ccc44d19adb5b511fb18acd82"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-graphics-desktop-1.5.11-sources.jar",
          "url": "ui-graphics-desktop-1.5.11-sources.jar",
          "size": 179082,
          "sha512": "1a831e0255ff1995bc6381c923ec386cb14f79b3b71bd36a92db80d862aa03ed015561a20572ae60626a295459522cb26f7ca638d8b6cea0e784476a5333853a",
          "sha256": "576374897d92fd259290d1cff851bf359be17135a72f7c33661769ad2f36e460",
          "sha1": "ad1693683af5f1051a6ddc83e46f2c35adf8c07b",
          "md5": "421c1cc096ce7f35a808649750b68b46"
        }
      ]
    }
  ]
}