{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-markdown-extension-gfm-alerts-242",
    "version": "0.26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jewel-markdown-extension-gfm-alerts-242-0.26.2.jar",
          "url": "jewel-markdown-extension-gfm-alerts-242-0.26.2.jar",
          "size": 70653,
          "sha512": "926ac1c743b993c9a676b1153838f56eac527ba1b73ad4bf0e03cac3a8420316445d56dc0086b1303c1560bac80d97db4fc1d90c358cfe17b3c93103bd348f5d",
          "sha256": "2cbad497aec25c2927597d7ceab220dd6d113fdd4340df02e336635743f8743e",
          "sha1": "1a5fbac4f06b4eec89ef4f427165db4dda0e5112",
          "md5": "e0a76a08101f8506c1c76814acaec1d4"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-markdown-core-242",
          "version": {
            "requires": "0.26.2"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-extension-gfm-alerts-242-0.26.2.jar",
          "url": "jewel-markdown-extension-gfm-alerts-242-0.26.2.jar",
          "size": 70653,
          "sha512": "926ac1c743b993c9a676b1153838f56eac527ba1b73ad4bf0e03cac3a8420316445d56dc0086b1303c1560bac80d97db4fc1d90c358cfe17b3c93103bd348f5d",
          "sha256": "2cbad497aec25c2927597d7ceab220dd6d113fdd4340df02e336635743f8743e",
          "sha1": "1a5fbac4f06b4eec89ef4f427165db4dda0e5112",
          "md5": "e0a76a08101f8506c1c76814acaec1d4"
        }
      ]
    }
  ]
}
