{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.components",
    "module": "components-resources",
    "version": "1.8.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-1.8.0-alpha04.jar",
          "url": "components-resources-1.8.0-alpha04.jar",
          "size": 30377,
          "sha512": "e419012420863d86fc2d629967c6696f6f6d42ad3130d84b586b0fe9667ac775def1574d6f524908857bc25ca38f1a548951c05de696d7f6e08148045d8e6484",
          "sha256": "7bc14c3ea620289907b3bc666999005ceda75c4da407bc8596d0965cf06990fe",
          "sha1": "f9e2596406aee305b7c7729a8a9a18ffb71a7d1c",
          "md5": "edde1e4fe9a7532ece6855efd21f188b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-kotlin-1.8.0-alpha04-sources.jar",
          "url": "components-resources-1.8.0-alpha04-sources.jar",
          "size": 48402,
          "sha512": "c8495079bb46259a3c3a94baf626c45d35074173d4544d50d47c589200e280c44c4d16e17f195a596c1d56a7462ac8ef976b3672948af36e0554c71a33de1c28",
          "sha256": "c3378781d24a69ad1dd8955cf8888d6b68fe03a34695fa26772be3af9e56cee4",
          "sha1": "5981d4390c8a08429b3976a5e8dfaa7402bc9d14",
          "md5": "ccca90292cdfc89e0e904e1ce48ff3dd"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../components-resources-android/1.8.0-alpha04/components-resources-android-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-android",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../components-resources-android/1.8.0-alpha04/components-resources-android-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-android",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../components-resources-android/1.8.0-alpha04/components-resources-android-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-android",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../components-resources-desktop/1.8.0-alpha04/components-resources-desktop-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-desktop",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../components-resources-desktop/1.8.0-alpha04/components-resources-desktop-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-desktop",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../components-resources-desktop/1.8.0-alpha04/components-resources-desktop-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-desktop",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosArm64/1.8.0-alpha04/components-resources-iosArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosArm64/1.8.0-alpha04/components-resources-iosArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosArm64/1.8.0-alpha04/components-resources-iosArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosArm64/1.8.0-alpha04/components-resources-iosArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosSimulatorArm64/1.8.0-alpha04/components-resources-iosSimulatorArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosSimulatorArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosSimulatorArm64/1.8.0-alpha04/components-resources-iosSimulatorArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosSimulatorArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosSimulatorArm64/1.8.0-alpha04/components-resources-iosSimulatorArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosSimulatorArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosSimulatorArm64/1.8.0-alpha04/components-resources-iosSimulatorArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosSimulatorArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosX64/1.8.0-alpha04/components-resources-iosX64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosX64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosX64/1.8.0-alpha04/components-resources-iosX64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosX64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosX64/1.8.0-alpha04/components-resources-iosX64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosX64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-iosX64/1.8.0-alpha04/components-resources-iosX64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-iosX64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-resources-js/1.8.0-alpha04/components-resources-js-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-js",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-resources-js/1.8.0-alpha04/components-resources-js-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-js",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-resources-js/1.8.0-alpha04/components-resources-js-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-js",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../components-resources-js/1.8.0-alpha04/components-resources-js-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-js",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosArm64/1.8.0-alpha04/components-resources-macosArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosArm64/1.8.0-alpha04/components-resources-macosArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosArm64/1.8.0-alpha04/components-resources-macosArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosArm64/1.8.0-alpha04/components-resources-macosArm64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosArm64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosX64/1.8.0-alpha04/components-resources-macosX64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosX64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosX64/1.8.0-alpha04/components-resources-macosX64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosX64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosX64/1.8.0-alpha04/components-resources-macosX64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosX64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../components-resources-macosX64/1.8.0-alpha04/components-resources-macosX64-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-macosX64",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../components-resources-wasmJs/1.8.0-alpha04/components-resources-wasmJs-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-wasmJs",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../components-resources-wasmJs/1.8.0-alpha04/components-resources-wasmJs-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-wasmJs",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../components-resources-wasmJs/1.8.0-alpha04/components-resources-wasmJs-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-wasmJs",
        "version": "1.8.0-alpha04"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../components-resources-wasmJs/1.8.0-alpha04/components-resources-wasmJs-1.8.0-alpha04.module",
        "group": "org.jetbrains.compose.components",
        "module": "components-resources-wasmJs",
        "version": "1.8.0-alpha04"
      }
    }
  ]
}
