{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.groovy",
    "module": "groovy-xml",
    "version": "4.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "groovydocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "groovydoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.29-groovydoc.jar",
          "url": "groovy-xml-4.0.29-groovydoc.jar",
          "size": 260231,
          "sha512": "a826e2bae9134ed395948e0e0f73feaf2584cf44a6abba9864d9e335934a7752fae70b3332ce78b40e6b4d39edc0e153e8cc2acd3c21c1b94f479968dcc2ecb9",
          "sha256": "031f8b8015422e14e722f81142238f99186b092ce564a0bcee16a428676423d8",
          "sha1": "4145153dd708bd10b298e92f725d8ecb02f8f3db",
          "md5": "784e238fc4a3641732ed470a8faf5392"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.29-javadoc.jar",
          "url": "groovy-xml-4.0.29-javadoc.jar",
          "size": 284043,
          "sha512": "86dcd435ed4a9a2b0cd7b80429a6bd233ca394f51df107218653b2870026583927fcb4a296801afe27eedf386a40fc9c47ccd10c1d932869ef2770c7a0407996",
          "sha256": "5be6944c0d60d3a7b9a61225d1ec4bb343da00e106b6a815147a6345a04d7b9e",
          "sha1": "e714fe21b607896e781362594e6a67f0b3dbfed0",
          "md5": "570aae7beeee212385d5367ee2959521"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.29-sources.jar",
          "url": "groovy-xml-4.0.29-sources.jar",
          "size": 98908,
          "sha512": "dcf6ea5ff4395eda1b930ac176129954b97dc63da849e533872c44862200ef01ba0f8ab87d9064f658054dadb3e0a08cd82edb37b445addf9efd2a3193fcc992",
          "sha256": "c401a63c6e01054fccceffe9ba10accec8303d3cb1759dfa21760388c9c0fa44",
          "sha1": "2d0016a804d645673ecd75dc503b8e5c2bfe234b",
          "md5": "47bd2472a95b1d8616015189003651b7"
        }
      ]
    },
    {
      "name": "groovyApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.29"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-xml-4.0.29.jar",
          "url": "groovy-xml-4.0.29.jar",
          "size": 216158,
          "sha512": "61e29bf3a76d97c83a4adb4e4b1263fd45dba4372ac08838bf1d3ac6515d0c585c103f63e3d35f2b2de62bdf8859253db6ba9140a79a65d46e490f91dd71ec65",
          "sha256": "30ce3967fd87d4ba6b9c433dc6082ae6a63007a7f8e8c464fb00714505f1950f",
          "sha1": "f6ccda36f8fdc3959a181b1a14d9dc2785dc230c",
          "md5": "baa6e3671d4535c099ded226ac5f3623"
        }
      ],
      "capabilities": [
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-xml",
          "version": "4.0.29"
        },
        {
          "group": "org.apache.groovy",
          "name": "groovy-xml",
          "version": "4.0.29"
        }
      ]
    },
    {
      "name": "groovyRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.29"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-xml-4.0.29.jar",
          "url": "groovy-xml-4.0.29.jar",
          "size": 216158,
          "sha512": "61e29bf3a76d97c83a4adb4e4b1263fd45dba4372ac08838bf1d3ac6515d0c585c103f63e3d35f2b2de62bdf8859253db6ba9140a79a65d46e490f91dd71ec65",
          "sha256": "30ce3967fd87d4ba6b9c433dc6082ae6a63007a7f8e8c464fb00714505f1950f",
          "sha1": "f6ccda36f8fdc3959a181b1a14d9dc2785dc230c",
          "md5": "baa6e3671d4535c099ded226ac5f3623"
        }
      ],
      "capabilities": [
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-xml",
          "version": "4.0.29"
        },
        {
          "group": "org.apache.groovy",
          "name": "groovy-xml",
          "version": "4.0.29"
        }
      ]
    }
  ]
}
