{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-core",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.2.1.aar",
          "url": "compose-material-core-1.2.1.aar",
          "size": 68051,
          "sha512": "65b8698dab730c6c1e68a43ccfcc1fed88afaafaedcfa9533f5ea94ce94347b7fec3cb476f194652a459012facfb857f46d948e688422c3a3234ce6fe6556341",
          "sha256": "45e0a525ae31de90d65e5588dbed796f01834322832c2d6d9290b45679dc0801",
          "sha1": "7069de301dc58f186a8cedde1b24556b5cef76f1",
          "md5": "0907e65dbb62d022a3f8d50a9124d0d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.2.1.aar",
          "url": "compose-material-core-1.2.1.aar",
          "size": 68051,
          "sha512": "65b8698dab730c6c1e68a43ccfcc1fed88afaafaedcfa9533f5ea94ce94347b7fec3cb476f194652a459012facfb857f46d948e688422c3a3234ce6fe6556341",
          "sha256": "45e0a525ae31de90d65e5588dbed796f01834322832c2d6d9290b45679dc0801",
          "sha1": "7069de301dc58f186a8cedde1b24556b5cef76f1",
          "md5": "0907e65dbb62d022a3f8d50a9124d0d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.2.1-sources.jar",
          "url": "compose-material-core-1.2.1-sources.jar",
          "size": 14193,
          "sha512": "d56f64a39f47998bb9d0f72394eac2e0d2dbb35b7af4418399e3c7ca6f408b5078c5f70b046aa32c130adf7c0674e38878b452039d154a63ebadbe381d7e0536",
          "sha256": "34433101ca238f8f426c4e5fcda4be9ed5ac5c3365afbd8ae553a67f399f5794",
          "sha1": "ad211126dccfb3a331d794693ceb6c6fd804cf4d",
          "md5": "3e8c9634ea178763f334d03225deaa48"
        }
      ]
    }
  ]
}