{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.9.3/foundation-layout-1.9.3.module",
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14184138"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout.aar",
          "url": "foundation-layout-android-1.9.3.aar",
          "size": 590370,
          "sha512": "b0a106ee34357262369a61da468eee77017dd5eccda128072d455ef83ef4bb35ec1f4c0c4e7faefec07db19656fc771b9060f56b48a7e9a22227b8c86cb23726",
          "sha256": "6dee097fcc27e0d9281f4df27c3c8f92716155a0df229835cd5a38d30fbbd165",
          "sha1": "67f5dfe725135b3114351e93c031d4a1f38fd348",
          "md5": "60aafe71742fe6bbb4218fcd819b40bd"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout.aar",
          "url": "foundation-layout-android-1.9.3.aar",
          "size": 590370,
          "sha512": "b0a106ee34357262369a61da468eee77017dd5eccda128072d455ef83ef4bb35ec1f4c0c4e7faefec07db19656fc771b9060f56b48a7e9a22227b8c86cb23726",
          "sha256": "6dee097fcc27e0d9281f4df27c3c8f92716155a0df229835cd5a38d30fbbd165",
          "sha1": "67f5dfe725135b3114351e93c031d4a1f38fd348",
          "md5": "60aafe71742fe6bbb4218fcd819b40bd"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.3"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-android-1.9.3-sources.jar",
          "url": "foundation-layout-android-1.9.3-sources.jar",
          "size": 108196,
          "sha512": "c2fd5384503111fea42fee04cdbabbed2b11640e5f6d2b2533e0e85696dd9f3d12aaea3073223e742db49e7b2f05251e7c1dae076e1935b431dc45de530293a6",
          "sha256": "0eb54d12eea32a1fdeb120417f7ea3f8def0e9707673bc752e2dab508b7023d8",
          "sha1": "59f899b03e2bc8e62b3d3cdfc1ecffab0efbcba7",
          "md5": "e528feee351fd492c656506d481da400"
        },
        {
          "name": "foundation-layout-1.9.3-samples-sources.jar",
          "url": "foundation-layout-android-1.9.3-samples-sources.jar",
          "size": 32462,
          "sha512": "e7b041cbea40e601edbf342cd3ade516841a076ab97f1158b1df9f58e4d5f5d5906bc42f7286e1dbf6ad302d69e277fe65cd7ba6cc4bbf487a65e3b9c9249264",
          "sha256": "0d6c4ce79232dd01c1d5321436598c5fcfad349f075b1bb655f420e0a8f745ba",
          "sha1": "d11ffc32b63523b42e060501814ca1b3c060c9f6",
          "md5": "ac6f89ae92fe8a65ef7cdf26b6ca0d98"
        }
      ]
    }
  ]
}