{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.5.11/runtime-1.5.11.module",
    "group": "org.jetbrains.compose.runtime",
    "module": "runtime",
    "version": "1.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.5.11.jar",
          "url": "runtime-desktop-1.5.11.jar",
          "size": 1165520,
          "sha512": "4eab82eb3eabefc4455b8b505d7366334d059cc1a40b37f8777c73469e6b38e651842b54dfcdfbfcb995f95720e52f7c6d0db876f6024fbdbffac664755822c3",
          "sha256": "6e67a4ed8e1aaa9ec5d275b24c5456e82d492ad5710aa28f425da09678016033",
          "sha1": "b73456ee05b2ed483fbcf4796a5ccc871577f430",
          "md5": "1698bf91f4fdffbbb15d2b84e7e0f69e"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.5.11.jar",
          "url": "runtime-desktop-1.5.11.jar",
          "size": 1165520,
          "sha512": "4eab82eb3eabefc4455b8b505d7366334d059cc1a40b37f8777c73469e6b38e651842b54dfcdfbfcb995f95720e52f7c6d0db876f6024fbdbffac664755822c3",
          "sha256": "6e67a4ed8e1aaa9ec5d275b24c5456e82d492ad5710aa28f425da09678016033",
          "sha1": "b73456ee05b2ed483fbcf4796a5ccc871577f430",
          "md5": "1698bf91f4fdffbbb15d2b84e7e0f69e"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "runtime-desktop-1.5.11-sources.jar",
          "url": "runtime-desktop-1.5.11-sources.jar",
          "size": 338633,
          "sha512": "36ab1247d25481e41410a50c8a26c484c6acf1fe4a4f2eaebf467e0181e19821b6a39f7f70d3ffa014d81261da937df16f8747675eb566882cdfe500ed0d45df",
          "sha256": "d1276a4a0b25d0a1e4ad06e48ba8dcac0504150d10f834e021d49a6fe553f31b",
          "sha1": "bcfedeeaac16f17bcab89fcc8cecec2255894b4b",
          "md5": "49a7fee8ccef73a0df120a336be16ebe"
        }
      ]
    }
  ]
}