{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.2.0.aar",
          "url": "ui-graphics-1.2.0.aar",
          "size": 1395353,
          "sha512": "8ed4756180e8c5f30682ed9d48275d290ba32199c11889d7e8ec008fd3c65929c69ca4a9d409de6193af9cd844793ed726340007d0dab819bb11bc2af4b07586",
          "sha256": "58606617a8e71e58eba56bd79410c77c6df79017bb058cf64cce1def3af463de",
          "sha1": "7a6673f31e030e1276f0a294308e7d1d5ec026aa",
          "md5": "0ca48afc836b0d06fa2877dc4dd979d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.2.0.aar",
          "url": "ui-graphics-1.2.0.aar",
          "size": 1395353,
          "sha512": "8ed4756180e8c5f30682ed9d48275d290ba32199c11889d7e8ec008fd3c65929c69ca4a9d409de6193af9cd844793ed726340007d0dab819bb11bc2af4b07586",
          "sha256": "58606617a8e71e58eba56bd79410c77c6df79017bb058cf64cce1def3af463de",
          "sha1": "7a6673f31e030e1276f0a294308e7d1d5ec026aa",
          "md5": "0ca48afc836b0d06fa2877dc4dd979d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-1.2.0-sources.jar",
          "url": "ui-graphics-1.2.0-sources.jar",
          "size": 159099,
          "sha512": "cc99ea4983fa64a05f04305b070f01bc3336a672d7707eb7915553c4cfd88c7d255ee0e648c70a8cabd28a14356f7932d4ade8edf6bd039f768965d4144d185d",
          "sha256": "b3a3ec4c3f21d75794ad5a9f29854fcf97bfd4ddf6889e7dcf98f199b663cbc4",
          "sha1": "7396c4fb60dcf72c51ddefeb38bf359217edc2cb",
          "md5": "df0c772d0efd90178a9c172e60ae7aae"
        }
      ]
    }
  ]
}