{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.jewel",
    "module": "jewel-markdown-core-242",
    "version": "0.26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-242",
          "version": {
            "requires": "0.26.2"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.22.0"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-core-242-0.26.2.jar",
          "url": "jewel-markdown-core-242-0.26.2.jar",
          "size": 270538,
          "sha512": "a391a8a1211c4f90be2e13d98ad643385f1bc3a1bcb1dfa01462574930000a3989ecba09775f79577be2f5fac91eaa55d56dd65e92aafa83a51c6971a5e85ff8",
          "sha256": "12b5154ed75781f9343b561c89941ae893c3918dd125e0aa74add52dc353f217",
          "sha1": "f978a9675046c6342538e59dc9931e2838f18329",
          "md5": "31d19aa1662f3d93fc258c03b75a5cb5"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.jewel",
          "module": "jewel-ui-242",
          "version": {
            "requires": "0.26.2"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.22.0"
          }
        }
      ],
      "files": [
        {
          "name": "jewel-markdown-core-242-0.26.2.jar",
          "url": "jewel-markdown-core-242-0.26.2.jar",
          "size": 270538,
          "sha512": "a391a8a1211c4f90be2e13d98ad643385f1bc3a1bcb1dfa01462574930000a3989ecba09775f79577be2f5fac91eaa55d56dd65e92aafa83a51c6971a5e85ff8",
          "sha256": "12b5154ed75781f9343b561c89941ae893c3918dd125e0aa74add52dc353f217",
          "sha1": "f978a9675046c6342538e59dc9931e2838f18329",
          "md5": "31d19aa1662f3d93fc258c03b75a5cb5"
        }
      ]
    }
  ]
}
