{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.6.10-dev1584/foundation-layout-1.6.10-dev1584.module",
    "group": "org.jetbrains.compose.foundation",
    "module": "foundation-layout",
    "version": "1.6.10-dev1584",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.10-dev1584"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-desktop-1.6.10-dev1584.jar",
          "url": "foundation-layout-desktop-1.6.10-dev1584.jar",
          "size": 528249,
          "sha512": "20b7dfeb8449b0ccd680b40f52bdaed5460ee65b0ea1b208647c504eb45dc3d2ddfe33894f710892cbe6bab202e593c0abdb4ae0860996567d2e9ba8089e3c62",
          "sha256": "27a1967846584e5be8ad7c95c2fc291ff99a4dbbe010789b35366296cf931095",
          "sha1": "9d639e56f127b36e0a2889af30b534ef713717d5",
          "md5": "2023f30a92e28e2356c9460c1db309a8"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.annotation-internal",
          "module": "annotation",
          "version": {
            "requires": "1.6.10-dev1584"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.10-dev1584"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.10-dev1584"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.10-dev1584"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-desktop-1.6.10-dev1584.jar",
          "url": "foundation-layout-desktop-1.6.10-dev1584.jar",
          "size": 528249,
          "sha512": "20b7dfeb8449b0ccd680b40f52bdaed5460ee65b0ea1b208647c504eb45dc3d2ddfe33894f710892cbe6bab202e593c0abdb4ae0860996567d2e9ba8089e3c62",
          "sha256": "27a1967846584e5be8ad7c95c2fc291ff99a4dbbe010789b35366296cf931095",
          "sha1": "9d639e56f127b36e0a2889af30b534ef713717d5",
          "md5": "2023f30a92e28e2356c9460c1db309a8"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "foundation-layout-desktop-1.6.10-dev1584-sources.jar",
          "url": "foundation-layout-desktop-1.6.10-dev1584-sources.jar",
          "size": 66881,
          "sha512": "9ff331e997a33e196726c29e8a33d437c57df4e2b0faa48442e59ef15cebbe81d33066f194c7108862140d7e7ae4a26b682bc5aa97022a7639ae2569d06a1bee",
          "sha256": "4c9a4e067bb30d2e0010e964ea81674f8ff8f23ccab9df7189ba588b22c9cf7e",
          "sha1": "17d7300a50abcfb3dc106d8b8ac2c94f8da95004",
          "md5": "8f0eb2fac15580a4fb197add48e5da1a"
        }
      ]
    }
  ]
}